'use strict';
let session,users=[],requests=[],saveEditor;
const content=document.querySelector('#content'),status=document.querySelector('#status'),dialog=document.querySelector('#editor'),form=document.querySelector('#editor-form');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={contacts:'People, ministries & requests',trips:'Trip operations & budgets',destinations:'Public destinations',finances:'Organization finances',documents:'Documents',inbox:'Inbox'};
const field=(name,label,value='',type='text',extra='')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const profile=u=>field('first_name','First name',u.first_name,'text','required maxlength="70"')+field('last_name','Last name',u.last_name,'text','required maxlength="70"')+field('email','Email address',u.email,'email','required maxlength="254"')+field('phone','Phone number',u.phone,'tel','required maxlength="40"')+field('country','Country',u.country||'US','text','required maxlength="60"');
const matrix=u=>`<label><input name="is_admin" type="checkbox" ${u.is_admin?'checked':''}> Administrator — full access and user management</label><p>For other users, choose access below. Trip operations includes that trip’s participants and budget. Contact access controls the separate directory; bulk trip import/export also requires contact access.</p><label>Apply a starting point<select id="preset"><option value="custom">Custom access</option><option value="read">Read only everywhere</option><option value="blocked">Block all sections</option><option value="edit">Edit all sections (no user administration)</option></select></label><div class="access-matrix">${Object.entries(names).map(([key,label])=>`<label>${label}<select name="permission_${key}">${[['blocked','Blocked'],['read','Read only'],['edit','Edit']].map(([v,t])=>`<option value="${v}" ${v===(u.permissions?.[key]||'blocked')?'selected':''}>${t}</option>`).join('')}</select></label>`).join('')}</div>`;
async function api(path,body,method){const r=await fetch('/api/interest/admin'+path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json','X-CSRF-Token':session?.csrfToken||''},body:body?JSON.stringify(body):undefined});const data=await r.json();window.HSPhones?.records(data);if(!r.ok)throw new Error(data.error||'Unable to complete this action.');return data;}
function editor(title,html,save){document.querySelector('#editor-title').textContent=title;document.querySelector('#editor-fields').innerHTML=html;document.querySelector('#editor-status').textContent='';saveEditor=save;form.querySelector('[type=submit]').hidden=!save;dialog.showModal();const preset=document.querySelector('#preset');if(preset)preset.onchange=()=>{if(preset.value!=='custom')form.querySelectorAll('[name^=permission_]').forEach(s=>s.value=preset.value);};}
function accessValues(v){return {...v,is_admin:form.elements.is_admin?.checked||false,permissions:Object.fromEntries(Object.keys(names).map(k=>[k,v['permission_'+k]]))};}
function showResult(result){if(result.setupLink||result.temporaryPassword)editor('Access instructions',`<p>${esc(result.message)}</p><p class="account-secret">${esc(result.setupLink||result.temporaryPassword)}</p><p>This is shown only now. Share it privately with the verified user.</p>`,null);else status.textContent=result.message||'Saved.';}
async function render(){session=await api('/session');const u=session.user;const forced=u.must_change_password;
 document.querySelector('#account-nav').innerHTML=forced?'<a href="#password">Change temporary password</a>':`<a href="#profile">My profile</a><a href="#password">Change password</a>${u.is_admin?'<a href="#users">Users & access requests</a>':''}${Object.entries(names).filter(([k])=>u.is_admin||['read','edit'].includes(u.permissions[k])).map(([k,label])=>`<a href="${({contacts:'/admin/#people',trips:'/admin/trips/',destinations:'/admin/destinations/',finances:'/admin/finance/',documents:'/admin/ministry/#documents',inbox:'/admin/ministry/#inbox'})[k]}" data-admin-link>${label}</a>`).join('')}<button id="signout" type="button">Sign out</button>`;
 document.querySelector('#signout')?.addEventListener('click',async()=>{await api('/logout',{});location.href='/admin/';});
 const route=forced?'password':location.hash.slice(1)||'profile';document.querySelector('#title').textContent=route==='users'?'Users & access requests':route==='password'?'Change password':'My profile';
 if(route==='password'){content.innerHTML=`<p>${forced?'Change your temporary password before continuing.':'Changing your password signs out your other sessions.'} Use at least 12 characters and three character types.</p><form id="password-form">${field('currentPassword','Current password','','password','required autocomplete="current-password"')}${field('newPassword','New password','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}${field('confirmPassword','Confirm new password','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}<button class="primary">Save password</button></form>`;document.querySelector('#password-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('/password',Object.fromEntries(new FormData(e.target)));location.hash='profile';await render();status.textContent='Password saved.';}catch(error){status.textContent=error.message;}finally{b.disabled=false;}};return;}
 if(route!=='users'){content.innerHTML=`<p>User name: <strong>${esc(u.username)}</strong> · Registered: ${esc(u.registered_at.slice(0,10))}</p><p>${u.is_admin?'Administrator':Object.entries(u.permissions).map(([k,v])=>names[k]+': '+v).join(' · ')}</p><form id="profile-form">${profile(u)}<button class="primary">Save my profile</button></form>`;document.querySelector('#profile-form').onsubmit=async e=>{e.preventDefault();try{const result=await api('/account/profile',{...Object.fromEntries(new FormData(e.target)),revision:u.revision},'PUT');session.user=result.user;await render();status.textContent='Profile saved.';}catch(error){status.textContent=error.message;}};return;}
 const data=await api('/account/users');users=data.users;requests=data.requests;
 content.innerHTML=`<p>Each person should have a unique user name so changes can be attributed to them. User names cannot be changed after creation.</p>${data.emailReady?'':'<p class="warning">Automatic email is not enabled in this environment. Setup links can be shared privately; emails are not marked as sent.</p>'}<button id="add-user" class="primary">Add user</button><h2>Users</h2><div class="table-wrap"><table><thead><tr><th>User</th><th>Access</th><th>Status</th><th>Actions</th></tr></thead><tbody>${users.map(x=>`<tr><td>${esc(x.first_name+' '+x.last_name)}<small>${esc(x.username)} · ${esc(x.email)}</small></td><td>${x.is_admin?'Administrator':'Custom section access'}</td><td>${esc(x.status)}</td><td><button data-action="edit" data-id="${esc(x.id)}">Edit</button><button data-action="invite" data-id="${esc(x.id)}">Send instructions</button><button data-action="temporary" data-id="${esc(x.id)}">Temporary password</button></td></tr>`).join('')}</tbody></table></div><h2>Access and recovery requests</h2>${requests.length?requests.map(r=>`<article class="card"><h3>${esc(r.first_name+' '+r.last_name)} — ${r.kind==='access'?'Access request':'Account recovery'}</h3><p>${esc(r.username)} · ${esc(r.email)} · ${esc(r.phone)}</p><p>${esc(r.message)}</p><p>${esc(r.status)}</p>${r.status==='pending'?`<button data-action="request" data-id="${esc(r.id)}">Review request</button>`:''}</article>`).join(''):'<p>No requests.</p>'}<h2>Email delivery</h2>${data.emailEvents.map(e=>`<p>${esc(e.created_at)} · ${esc(e.recipient)} · ${esc(e.kind)} · ${esc(e.status)}</p>`).join('')||'<p>No account emails yet.</p>'}`;
 document.querySelector('#add-user').onclick=()=>editUser({});
}
function editUser(u){editor(u.id?'Edit user':'Add user',`${u.id?`<p>User name: ${esc(u.username)}</p><p>Saving here signs this user out so the updated access takes effect.</p>`:field('username','User name','','text','required pattern="[a-zA-Z][a-zA-Z0-9._-]{2,59}" maxlength="60"')}${profile(u)}${matrix(u)}${u.id?`<label>Status<select name="status"><option value="active" ${u.status==='active'?'selected':''}>Active</option><option value="disabled" ${u.status==='disabled'?'selected':''}>Disabled</option></select></label>`:'<p>The user receives a one-use link to set their own password. No password is stored in readable form.</p>'}`,v=>api('/account/users'+(u.id?'/'+u.id:''),{...accessValues(v),revision:u.revision},u.id?'PUT':'POST'));}
document.addEventListener('click',async e=>{if(e.target.closest('[data-admin-link]'))sessionStorage.setItem('hope-sojourns-admin-navigation','true');const b=e.target.closest('[data-action]');if(!b)return;const u=users.find(x=>x.id===b.dataset.id);try{
 if(b.dataset.action==='edit')editUser(u);
 if(b.dataset.action==='invite')editor('Send account instructions',`<p>Send a new one-use setup link to ${esc(u.email)}? Earlier setup links will expire.</p>`,()=>api('/account/users/'+u.id+'/invite',{}));
 if(b.dataset.action==='temporary')editor('Reset to a temporary password',`<p>Verify ${esc(u.first_name)}’s identity using trusted contact information. This signs the user out and requires a password change before portal access.</p><label><input name="verified" type="checkbox" required> I verified this user’s identity</label>`,()=>api('/account/users/'+u.id+'/temporary-password',{}));
 if(b.dataset.action==='request'){const r=requests.find(x=>x.id===b.dataset.id);editor('Review '+(r.kind==='access'?'access request':'account recovery'),`<p>${esc(r.first_name+' '+r.last_name)} · ${esc(r.username)} · ${esc(r.email)}</p><p>${esc(r.message)}</p><label>Decision<select name="action"><option value="reject">Reject</option><option value="approve">Approve</option></select></label>${r.kind==='access'?profile(r)+matrix({}):`<label>Existing account<select name="user_id" required><option value="">Choose the verified account</option>${users.map(x=>`<option value="${esc(x.id)}">${esc(x.username+' — '+x.first_name+' '+x.last_name)}</option>`).join('')}</select></label><label><input name="identityVerified" type="checkbox"> I independently verified identity against trusted records</label><p>Approval does not automatically change the email or password. After approval, edit the verified user’s profile if needed and issue a temporary password.</p>`}`,v=>api('/account/requests/'+r.id,{...v,...(r.kind==='access'?accessValues(v):{}),identityVerified:form.elements.identityVerified?.checked||false},'PUT'));}
 }catch(error){status.textContent=error.message;}});
form.onsubmit=async e=>{e.preventDefault();if(!saveEditor)return;const b=form.querySelector('[type=submit]');b.disabled=true;try{const result=await saveEditor(Object.fromEntries(new FormData(form)));dialog.close();try{await render();showResult(result);}catch{content.innerHTML='<p>Saved. Your session ended because your account was updated.</p><a href="/admin/">Sign in again</a>';status.textContent='';}}catch(error){document.querySelector('#editor-status').textContent=error.message;}finally{b.disabled=false;}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());window.addEventListener('hashchange',()=>render().catch(e=>status.textContent=e.message));render().catch(e=>{status.textContent=e.message;content.innerHTML='<a href="/admin/">Sign in to continue</a>';});
