'use strict';
const portal=document.body.dataset.portal||'hs',base=portal==='hs'?'/api/interest/admin':'/api/admin';
const labels={hs:'Hope Sojourns',csm:'Christian Steps Ministries'};
const sections={hs:{contacts:'People, ministries & requests',trips:'Trip operations & budgets',destinations:'Public destinations',finances:'Organization finances',documents:'Documents',inbox:'Inbox'},csm:{giving:'PayPal, giving & distribution',finances:'Bookkeeping, invoices, mileage & files'}};
const links=portal==='hs'?{contacts:'/admin/#people',trips:'/admin/trips/',destinations:'/admin/destinations/',finances:'/admin/finance/',documents:'/admin/ministry/#documents',inbox:'/admin/ministry/#inbox'}:{giving:'/admin/',finances:'/admin/ledger/'};
const content=document.querySelector('#content'),status=document.querySelector('#status'),dialog=document.querySelector('#editor'),form=document.querySelector('#editor-form');
let session,users=[],requests=[],saveEditor;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(name,label,value='',type='text',extra='')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const profile=u=>field('first_name','First name',u.first_name,'text','required maxlength="70"')+field('last_name','Last name',u.last_name,'text','required maxlength="70"')+field('email','Email address',u.email,'email','required maxlength="254"')+field('phone','Phone number',u.phone,'tel','required maxlength="40"')+field('country','Country',u.country||'US','text','required maxlength="60"');
const localTime=v=>v?esc(new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'long'})):'Never logged in';
async function api(path,body,method){const r=await fetch(base+path,{method:method||(body?'POST':'GET'),cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':session?.csrfToken||''},body:body?JSON.stringify(body):undefined});const data=await r.json();window.HSPhones?.records(data);if(!r.ok)throw new Error(data.error||'Unable to complete this action.');return data;}
function editor(title,html,save){document.querySelector('#editor-title').textContent=title;document.querySelector('#editor-fields').innerHTML=html;document.querySelector('#editor-status').textContent='';saveEditor=save;form.querySelector('[type=submit]').hidden=!save;dialog.showModal();}
function matrix(u={},requestedPortal=portal){
 return `${session.user.is_org_admin?`<label><input name="is_org_admin" type="checkbox" ${u.is_org_admin?'checked':''}> Organization Administrator — shared accounts and both portals</label>`:''}${(session.user.is_org_admin?['hs','csm']:[portal]).map(p=>{
 const m=u.memberships?.[p]||{enabled:!u.id&&p===requestedPortal};
 return `<fieldset><legend>${labels[p]}</legend><label><input type="checkbox" name="${p}_enabled" ${m.enabled?'checked':''}> Allow access to this portal</label><label><input type="checkbox" name="${p}_admin" ${m.is_admin?'checked':''}> Portal Administrator — manage this portal’s users and all sections</label><label>Apply a starting point<select data-preset="${p}"><option value="">Custom access</option><option value="read">Read only everywhere</option><option value="edit">Edit everywhere</option><option value="blocked">Block all sections</option></select></label><div class="access-matrix">${Object.entries(sections[p]).map(([k,label])=>`<label>${label}<select name="${p}_${k}">${['blocked','read','edit'].map(v=>`<option value="${v}" ${m.permissions?.[k]===v?'selected':''}>${{blocked:'Blocked',read:'Read only',edit:'Edit'}[v]}</option>`).join('')}</select></label>`).join('')}</div></fieldset>`;
 }).join('')}`;
}
function accessValues(v){const memberships={};for(const p of session.user.is_org_admin?['hs','csm']:[portal])memberships[p]={enabled:form.elements[p+'_enabled'].checked,is_admin:form.elements[p+'_admin'].checked,permissions:Object.fromEntries(Object.keys(sections[p]).map(k=>[k,v[p+'_'+k]]))};return {memberships,...(session.user.is_org_admin?{is_org_admin:form.elements.is_org_admin.checked}:{})};}
function profileValues(v){return Object.fromEntries(['first_name','last_name','email','phone','country'].filter(k=>v[k]!==undefined).map(k=>[k,v[k]]));}
function showResult(r){if(r.setupLink||r.temporaryPassword)editor('Access instructions',`<p>${esc(r.message)}</p><p class="account-secret">${esc(r.setupLink||r.temporaryPassword)}</p><p>Shown only now. Share privately with the verified user.</p>`,null);else status.textContent=r.message||'Saved.';}
async function render(){
 session=await api('/session');const u=session.user,forced=u.must_change_password;
 document.querySelector('#account-nav').innerHTML=forced?'<a href="#password">Change temporary password</a>':`<a href="#profile">My profile</a><a href="#password">Change password</a>${u.is_admin?'<a href="#users">Users & access requests</a>':''}${Object.entries(sections[portal]).filter(([k])=>u.is_admin||['read','edit'].includes(u.permissions[k])).map(([k,label])=>`<a href="${links[k]}">${label}</a>`).join('')}${u.can_switch&&u.switch_url?`<a href="${esc(u.switch_url+'?sourceOrigin='+encodeURIComponent(location.origin))}">Switch to ${labels[portal==='hs'?'csm':'hs']}</a>`:''}<button id="signout" type="button">Sign out</button>`;
 document.querySelector('#signout')?.addEventListener('click',async()=>{await api('/logout',{});location.href='/admin/';});
 const route=forced?'password':location.hash.slice(1)||'profile';document.querySelector('#title').textContent=route==='users'?'Users & access requests':route==='password'?'Change shared password':'My shared profile';
 if(route==='password'){
  content.innerHTML=`<p>${forced?'Change your temporary password before continuing.':'This password is used for both portals. Changing it signs out your other sessions.'} Use at least 12 characters and three character types.</p><form id="password-form">${field('currentPassword','Current password','','password','required autocomplete="current-password"')}${field('newPassword','New password','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}${field('confirmPassword','Confirm new password','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}<button class="primary">Save password</button></form>`;
  document.querySelector('#password-form').onsubmit=async e=>{e.preventDefault();try{await api('/password',Object.fromEntries(new FormData(e.target)));location.hash='profile';await render();status.textContent='Password saved.';}catch(error){status.textContent=error.message;}};return;
 }
 if(route!=='users'){
  content.innerHTML=`<p>User name: <strong>${esc(u.username)}</strong> · Registered: ${esc(u.registered_at.slice(0,10))}</p><p>${u.is_org_admin?'Organization Administrator':u.is_admin?'Portal Administrator':'Member'} · Last logged in: ${localTime(u.last_login_at)}</p><p>Contact changes apply to both portals. Portal permissions are managed separately.</p><form id="profile-form">${profile(u)}<button class="primary">Save my profile</button></form>`;
  document.querySelector('#profile-form').onsubmit=async e=>{e.preventDefault();try{await api('/account/profile',{...profileValues(Object.fromEntries(new FormData(e.target))),revision:u.revision},'PUT');await render();status.textContent='Profile saved.';}catch(error){status.textContent=error.message;}};return;
 }
 const data=await api('/account/users');users=data.users;requests=data.requests;
 content.innerHTML=`<p>${u.is_org_admin?'Manage one shared account and independent access to each portal. Suspending or deleting the shared account affects both portals.':'Manage access to this portal. Shared identity, other-portal access, and global suspension belong to an Organization Administrator.'}</p>${data.emailReady?'':'<p class="warning">Automatic email is unavailable. An Organization Administrator can share setup instructions privately.</p>'}<button id="add-user" class="primary">Add user</button><h2>Users</h2><p>Last logged in uses your local time zone.</p><div class="table-wrap"><table><thead><tr><th>User</th><th>Portal access</th><th>Status</th><th>Last logged in</th><th>Actions</th></tr></thead><tbody>${users.map(x=>`<tr><td>${esc(x.first_name+' '+x.last_name)}<small>${esc(x.username)} · ${esc(x.email)}</small>${x.is_org_admin?'<strong>Organization Administrator</strong>':''}</td><td>${Object.entries(x.memberships).map(([p,m])=>`${labels[p]}: ${m.enabled?(m.is_admin?'Portal Administrator':'Member'):'No access'}`).join('<br>')}</td><td>${x.status==='active'?'Active':'Suspended across both portals'}</td><td>${localTime(x.last_login_at)}</td><td>${u.is_org_admin||!x.is_org_admin?`<button data-action="edit" data-id="${esc(x.id)}">Edit</button><button data-action="invite" data-id="${esc(x.id)}">Send instructions</button>${u.is_org_admin?`<button data-action="temporary" data-id="${esc(x.id)}">Temporary password</button>${x.id!==u.id?`<button data-action="delete" data-id="${esc(x.id)}">Delete account</button>`:''}`:''}`:''}</td></tr>`).join('')}</tbody></table></div><h2>Access and recovery requests</h2>${requests.map(r=>`<article class="card"><h3>${esc(r.first_name+' '+r.last_name)} — ${labels[r.portal||portal]}</h3><p>${esc(r.kind)} · ${esc(r.username)} · ${esc(r.email)}</p><p>${esc(r.message)}</p><p>${esc(r.status)}</p>${r.status==='pending'?`<button data-action="request" data-id="${esc(r.id)}">Review request</button>`:''}</article>`).join('')||'<p>No requests.</p>'}<h2>Email delivery</h2>${data.emailEvents.map(e=>`<p>${localTime(e.created_at)} · ${esc(e.recipient)} · ${esc(e.kind)} · ${esc(e.status)}</p>`).join('')||'<p>No account emails yet.</p>'}`;
 document.querySelector('#add-user').onclick=()=>editUser({});
}
function editUser(u){
 const sharedEditable=session.user.is_org_admin||!u.id;
 editor(u.id?'Edit portal access & account':'Add user',`${u.id?`<p>User name: ${esc(u.username)}</p>`:field('username','User name','','text','required pattern="[a-zA-Z][a-zA-Z0-9._-]{2,59}" maxlength="60"')}${sharedEditable?profile(u):`<p>${esc(u.first_name+' '+u.last_name)} · ${esc(u.email)}</p><p>The user can change their own shared profile.</p>`}${matrix(u)}${u.id&&session.user.is_org_admin?`<label>Shared account status<select name="status"><option value="active" ${u.status==='active'?'selected':''}>Active</option><option value="disabled" ${u.status==='disabled'?'selected':''}>Suspended in both portals</option></select></label>`:''}<p>To remove access to only one portal, uncheck that portal’s access. Existing accounts keep their password when you grant another portal.</p>`,v=>api('/account/users'+(u.id?'/'+u.id:''),{...profileValues(v),...accessValues(v),...(u.id?{revision:u.revision}:{username:v.username}),...(v.status?{status:v.status}:{})},u.id?'PUT':'POST'));
}
document.addEventListener('change',e=>{if(e.target.matches('[data-preset]')&&e.target.value)for(const k of Object.keys(sections[e.target.dataset.preset]))form.elements[e.target.dataset.preset+'_'+k].value=e.target.value;});
document.addEventListener('click',async e=>{
 const button=e.target.closest('[data-action]');if(!button)return;const u=users.find(x=>x.id===button.dataset.id);
 try{
  if(button.dataset.action==='edit')editUser(u);
  if(button.dataset.action==='invite')editor('Send account instructions',`<p>Send a one-use password setup link to ${esc(u.email)}? Earlier links will expire. This changes the shared password when the user redeems it.</p>`,()=>api('/account/users/'+u.id+'/invite',{}));
  if(button.dataset.action==='temporary')editor('Temporary shared password',`<p>This ends sign-in sessions in both portals.</p><label><input type="checkbox" required> I independently verified this person’s identity</label>`,()=>api('/account/users/'+u.id+'/temporary-password',{}));
  if(button.dataset.action==='delete')editor('Delete shared account',`<p>Delete ${esc(u.username)} from both portals? Historical records remain attributed to this account.</p>${field('confirmUsername','Type '+u.username+' to confirm','','text','required')}`,v=>api('/account/users/'+u.id,{confirmUsername:v.confirmUsername,revision:u.revision},'DELETE'));
  if(button.dataset.action==='request'){
   const r=requests.find(x=>x.id===button.dataset.id),org=session.user.is_org_admin;
   editor('Review request',`<p>${esc(r.kind)} for ${labels[r.portal||portal]}: ${esc(r.username)} · ${esc(r.email)}</p><p>${esc(r.message)}</p><label>Decision<select name="action"><option value="reject">Reject</option><option value="approve">Approve</option></select></label>${r.kind==='access'?profile(r)+matrix({},r.portal||portal):''}${org?`<label>${r.kind==='access'?'Link an existing account (optional)':'Verified existing account'}<select name="user_id"><option value="">${r.kind==='access'?'Create a new account':'Choose an account'}</option>${users.map(x=>`<option value="${esc(x.id)}">${esc(x.username+' — '+x.email)}</option>`).join('')}</select></label><label><input name="identityVerified" type="checkbox"> I verified identity before linking an existing account or approving recovery</label>`:r.kind==='recovery'?'<p>An Organization Administrator must approve recovery requests.</p>':''}`,v=>api('/account/requests/'+r.id,{action:v.action,...(r.kind==='access'?{...profileValues(v),...accessValues(v)}:{}),user_id:v.user_id||undefined,identityVerified:form.elements.identityVerified?.checked||false},'PUT'));
  }
 }catch(error){status.textContent=error.message;}
});
form.onsubmit=async e=>{e.preventDefault();if(!saveEditor)return;const b=form.querySelector('[type=submit]');b.disabled=true;try{const result=await saveEditor(Object.fromEntries(new FormData(form)));dialog.close();try{await render();showResult(result);}catch{content.innerHTML='<p>Saved. Your session ended because your account was updated.</p><a href="/admin/">Sign in again</a>';status.textContent='';}}catch(error){document.querySelector('#editor-status').textContent=error.message;}finally{b.disabled=false;}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());window.addEventListener('hashchange',()=>render().catch(e=>status.textContent=e.message));render().catch(e=>{status.textContent=e.message;content.innerHTML='<a href="/admin/">Sign in to continue</a>';});
