(()=>{
 const el=(tag,text,className)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(className)n.className=className;return n;};
 function playVideo(m,trigger){
  const dialog=el('dialog',null,'memory-video-player'),close=el('button','Close video'),heading=el('h2',m.title),video=el('video'),status=el('p');
  close.type='button';dialog.setAttribute('aria-label',m.title);video.src=m.image_url;video.controls=true;video.playsInline=true;video.preload='metadata';status.setAttribute('role','status');
  video.addEventListener('error',()=>{status.textContent='This browser cannot play this video. Try another browser or ask the trip organizer for an MP4 version.';});
  dialog.append(close,heading,video,status);document.body.append(dialog);close.onclick=()=>dialog.close();
  dialog.addEventListener('close',()=>{video.pause();video.removeAttribute('src');video.load();dialog.remove();trigger.focus();});dialog.showModal();video.play().catch(()=>{if(!video.error)status.textContent='Press Play to start the video.';});
 }
 function memory(m){const f=el(m.kind!=='note'?'figure':'article',null,'memory-card');if(m.kind==='photo'){const a=el('a');a.href=m.image_url;a.target='_blank';a.rel='noopener';a.setAttribute('aria-label',`View full-size photo: ${m.title} (opens in a new tab)`);const img=el('img');img.src=m.image_url;img.alt=m.alt_text||m.title;img.loading='lazy';a.append(img);f.append(a);}else if(m.kind==='video'){const button=el('button',null,'memory-video-tile'),preview=el('video'),label=el('span','▶ Play video','memory-play-label');button.type='button';button.setAttribute('aria-label',`Play video: ${m.title}`);preview.src=m.image_url+'#t=0.1';preview.preload='metadata';preview.muted=true;preview.playsInline=true;preview.setAttribute('aria-hidden','true');preview.tabIndex=-1;button.append(preview,label);button.onclick=()=>playVideo(m,button);f.append(button);}f.append(el('h3',m.title));if(m.event_date)f.append(el('p',m.event_date,'memory-date'));if(m.caption)f.append(el('p',m.caption));if(m.content)f.append(window.HSJourneyContent.render(m.content));if(m.credit)f.append(el('p',m.credit,'memory-credit'));return f;}
 function collection(container,items){container.replaceChildren();const photos=items.filter(m=>['photo','video'].includes(m.kind)).sort((a,b)=>(a.event_date||'9999-12-31').localeCompare(b.event_date||'9999-12-31')||(a.created_at||'').localeCompare(b.created_at||'')||String(a.id||'').localeCompare(String(b.id||''))),notes=items.filter(m=>m.kind==='note');if(photos.length){container.append(el('h2',photos.some(m=>m.kind==='video')?'Trip photos & videos':'Trip photos'));const grid=el('div',null,'memory-gallery');photos.forEach(m=>grid.append(memory(m)));container.append(grid);}if(notes.length){container.append(el('h2','Notes from the journey'));notes.forEach(m=>container.append(memory(m)));}}
 function story(container,s){container.replaceChildren(el('h1',s.title),el('p',[s.location,s.start_date,s.end_date].filter(Boolean).join(' · '),'memory-date'),el('p',s.summary));if(s.story)container.append(window.HSJourneyContent.render(s.story));const studies=el('section');s.content.forEach(c=>{const d=el('details',null,'memory-study');d.append(el('summary',[c.event_date,c.title].filter(Boolean).join(' · ')));d.append(window.HSJourneyContent.render(c.content,{study:c.content_type==='devotional'}));if(c.link_url&&/^https:\/\//i.test(c.link_url)){const a=el('a','Open related resource');a.href=c.link_url;a.target='_blank';a.rel='noopener';d.append(a);}studies.append(d);});if(s.content.length)container.append(el('h2','Devotionals and trip resources'),studies);const memories=el('section');collection(memories,s.memories);container.append(memories);}
 window.HSTripMemoriesView={collection,story};
})();
