/* Download an escaped, self-contained traveler packet for offline reading or printing. */
(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function download(trip,content,members=[]){
 const items=content.filter(c=>c.publication_status==='published'&&c.visibility!=='admin').slice().sort((a,b)=>(a.event_date||'9999').localeCompare(b.event_date||'9999')||(a.event_time||'').localeCompare(b.event_time||'')||(a.sort_order||0)-(b.sort_order||0));
 const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(trip.title)} — Traveler packet</title><style>body{font:18px/1.6 Georgia,serif;max-width:850px;margin:2rem auto;padding:1rem}article{break-inside:avoid;margin:2rem 0}article div{white-space:pre-wrap}h1,h2,h3{line-height:1.2}a{overflow-wrap:anywhere}@media print{body{font-size:11pt;margin:0}.print-help{display:none}h2,h3{break-after:avoid}article{break-inside:auto}}</style><h1>${esc(trip.title)}</h1><p>${esc([trip.start_date,trip.end_date,trip.location].filter(Boolean).join(' · '))}</p><p class="print-help">Saved for offline use. Use your browser’s Print command to print or save as PDF. External resource links need an internet connection.</p><p>Prepared ${esc(new Date().toLocaleDateString())}. This copy does not update automatically.</p>${items.map(c=>`<article><h2>${esc(c.title)}</h2><p>${esc([c.event_date,c.event_time,c.location].filter(Boolean).join(' · '))}</p><div>${esc(c.content)}</div>${/^https:\/\//i.test(c.link_url||'')?`<p><a href="${esc(c.link_url)}">Open resource</a></p>`:''}</article>`).join('')}${members.length?'<h2>Selected team contacts</h2>'+members.map(p=>`<article><h3>${esc((p.preferred_name||p.first_name)+' '+p.last_name)}</h3><p>${esc([p.role,p.email,p.phone].filter(Boolean).join(' · '))}</p></article>`).join(''):''}</html>`;
 const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=(trip.code||'trip').replace(/[^a-z0-9_-]/gi,'-')+'-traveler-packet.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 window.HSTravelerPacket={download};
})();
