'use strict';
let csrf='',destinations=[],saveEditor;
const content=document.querySelector('#content'),status=document.querySelector('#status'),dialog=document.querySelector('#editor'),form=document.querySelector('#editor-form');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(name,label,value='',type='text',extra='')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(name,label,value='',limit=5000)=>`<label>${esc(label)}<textarea name="${name}" rows="3" maxlength="${limit}">${esc(value)}</textarea></label>`;
const publicUrl=d=>['athens','kenya','belize','nice','arkansas','mexico-city','others'].includes(d.slug)?'/trips/'+d.slug+'/':'/destination/?destination='+encodeURIComponent(d.slug);
async function api(path='',body,method){const r=await fetch('/api/interest/admin'+path,{method:method||(body?'POST':'GET'),credentials:'same-origin',headers:{'X-CSRF-Token':csrf,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to save.');return data;}
async function refresh(){const result=await api('/destinations');destinations=result.destinations;content.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Display order</th><th>Destination</th><th>Dates / planning</th><th>Visibility</th><th>Actions</th></tr></thead><tbody>${destinations.map(d=>`<tr><td>${d.sort_order}</td><td><strong>${esc(d.title)}</strong><small>${esc(d.location)}</small></td><td>${esc(d.dates_text||'Dates not announced')}</td><td><span class="tag">${d.status==='archived'?'Hidden':esc(d.status)}</span></td><td><button type="button" data-action="edit" data-slug="${esc(d.slug)}">Edit</button><button type="button" data-action="photo" data-slug="${esc(d.slug)}">Photo</button><button type="button" data-action="preview" data-slug="${esc(d.slug)}">Preview</button>${d.status==='published'?`<a class="button" href="${esc(publicUrl(d))}" target="_blank" rel="noopener">View public page</a>`:''}</td></tr>`).join('')}</tbody></table></div>`;status.textContent='';}
function editor(title,html,save){document.querySelector('#editor-title').textContent=title;document.querySelector('#editor-fields').innerHTML=html;document.querySelector('#editor-status').textContent='';saveEditor=save;form.querySelector('[type=submit]').hidden=!save;dialog.showModal();}
function edit(d={}){editor(d.id?'Edit destination':'Add destination',`${field('title','Destination name',d.title||'','text','required maxlength="150"')}${!d.id?field('slug','Page address — lowercase words with hyphens','','text','required maxlength="70" pattern="[a-z0-9]+(-[a-z0-9]+)*"'):`<p class="muted">Page address: ${esc(d.slug)}. Existing links stay unchanged.</p>`}<div class="grid">${field('location','Location / region',d.location||'','text','required maxlength="150"')}${field('sort_order','Display order — lower numbers first',d.sort_order??(destinations.length?Math.max(...destinations.map(x=>x.sort_order))+10:10),'number','required min="0" max="100000" step="1"')}</div><p class="muted">If the number is already used, that destination and all higher-numbered destinations move up by one automatically.</p><label>Visibility<select name="status">${[['draft','Draft — private'],['published','Published — show publicly'],['archived','Hidden — keep history']].map(([v,t])=>`<option value="${v}" ${v===(d.status||'draft')?'selected':''}>${t}</option>`).join('')}</select></label>${area('summary','Tile summary',d.summary,500)}${field('eyebrow','Page subtitle',d.eyebrow||'','text','maxlength="150"')}${area('introduction','Page introduction',d.introduction)}${area('dates_text','Public dates and planning notes — one line per departure',d.dates_text,1500)}<p class="muted">These are the dates shown on the tile. Manage traveler assignments and specific departures under Dated trips.</p>${area('partners','Ministry partners — one per line',d.partners,3000)}${area('service','How the team may serve',d.service)}<div class="grid">${field('focus','Ministry focus',d.focus||'','text','maxlength="300"')}${field('setting','Setting',d.setting||'','text','maxlength="300"')}</div>${area('notes','Additional public information',d.notes,3000)}${field('image_alt','Photo description for accessibility',d.image_alt||'','text','maxlength="300"')}${area('image_credit','Photo credit and license information',d.image_credit,1000)}<p class="warning">Publishing makes this content visible on the website. To add a photo to a new destination, save as Draft, then choose Photo.</p>`,v=>api('/destinations'+(d.id?'/'+d.slug:''),{...v,revision:d.revision},d.id?'PUT':'POST'));}
function photo(d){editor('Destination photo',`${d.image_url?`<img src="${esc(d.image_url)}" alt="${esc(d.image_alt)}" width="400">`:''}${field('file','Choose a JPEG, PNG, or WebP photo','','file','required accept="image/jpeg,image/png,image/webp"')}<p>Up to 6 MB. Use a photo you have permission to publish. Replacing a published destination’s photo updates the website immediately.</p>`,()=>{const data=new FormData(form);data.set('revision',String(d.revision));return api('/destinations/'+d.slug+'/image',data);});}
function preview(d){editor('Destination preview',`${d.image_url?`<img src="${esc(d.image_url)}" alt="${esc(d.image_alt)}" width="400">`:''}<p class="eyebrow">${esc(d.eyebrow)}</p><h2>${esc(d.title)}</h2><p><strong>Display order: ${d.sort_order}</strong> · ${esc(d.status)}</p><p>${esc(d.summary)}</p>${['dates_text','introduction','partners','service','notes','image_credit'].map(key=>d[key]?`<div class="details">${esc(d[key])}</div>`:'').join('')}<p class="muted">Private preview. Only published destinations appear publicly.</p>`,null);}
form.onsubmit=async e=>{e.preventDefault();if(!saveEditor)return;const button=form.querySelector('[type=submit]');button.disabled=true;try{await saveEditor(Object.fromEntries(new FormData(form)));dialog.close();await refresh();}catch(error){document.querySelector('#editor-status').textContent=error.message;}finally{button.disabled=false;}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());document.querySelector('#add').onclick=()=>edit();document.querySelector('#refresh').onclick=()=>refresh().catch(e=>status.textContent=e.message);
document.addEventListener('click',e=>{if(e.target.closest('[data-admin-link]'))sessionStorage.setItem('hope-sojourns-admin-navigation','true');const b=e.target.closest('[data-action]');if(!b)return;const d=destinations.find(d=>d.slug===b.dataset.slug);if(b.dataset.action==='edit')edit(d);if(b.dataset.action==='photo')photo(d);if(b.dataset.action==='preview')preview(d);});
(async()=>{try{const session=await api('/session');csrf=session.csrfToken;await refresh();}catch(error){status.textContent=error.message;content.innerHTML='<a href="/admin/" data-admin-link>Sign in through the admin portal</a>';}})();
