'use strict';
const content=document.querySelector('#content'),status=document.querySelector('#status');
const input=(name,label,type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" required ${extra}></label>`;
let resetToken=new URLSearchParams(location.hash.slice(1)).get('token');
if(resetToken)history.replaceState(null,'',location.pathname+'#reset');
function render(){status.textContent='';const mode=resetToken?'reset':location.hash.slice(1)||'request';document.querySelector('#account-nav').innerHTML='<a href="/admin/">Sign in</a><a href="#request">Request access</a><a href="#forgot">Forgot password</a><a href="#recovery">Request administrator help</a>';
 document.querySelector('#title').textContent=({request:'Request MMT access',forgot:'Forgot password',recovery:'Request administrator help',reset:'Set your password'})[mode]||'Request MMT access';
 const profile=input('first_name','First name','text','maxlength="70" autocomplete="given-name"')+input('last_name','Last name','text','maxlength="70" autocomplete="family-name"')+input('username','User name','text','maxlength="60" autocomplete="username" pattern="[a-zA-Z][a-zA-Z0-9._-]{2,59}"')+input('email',mode==='recovery'?'Email where the administrator can reach you':'Email address','email','maxlength="254" autocomplete="email"')+input('phone','Phone number','tel','maxlength="40" autocomplete="tel"')+'<label>Country<input name="country" value="US" required maxlength="60"></label><label>Message<textarea name="message" maxlength="1500" rows="3"></textarea></label>';
 content.innerHTML=`<form id="access-form">${mode==='reset'?'<p>Use at least 12 characters with three of: uppercase letters, lowercase letters, numbers, and symbols.</p>'+input('password','New password','password','minlength="12" maxlength="128" autocomplete="new-password"')+input('confirmPassword','Confirm new password','password','minlength="12" maxlength="128" autocomplete="new-password"'):mode==='forgot'?'<p>Enter the email address on your account.</p>'+input('email','Email address','email','maxlength="254" autocomplete="email"'):`<p>${mode==='recovery'?'Tell the administrator why you cannot use your account email. They must verify your identity before resetting access.':'An administrator must approve your access. You will set your own password after approval.'}</p>`+profile}<button class="primary" type="submit">${mode==='reset'?'Save password':'Send request'}</button></form>`;
 document.querySelector('#access-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));if(mode==='reset')body.token=resetToken;const r=await fetch('/api/interest/public/account/'+(mode==='reset'?'reset':mode==='forgot'?'forgot':mode==='recovery'?'recovery':'request'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw new Error(data.error);status.textContent=data.message;content.replaceChildren();if(mode==='reset'){resetToken=null;const link=document.createElement('a');link.href='/admin/';link.textContent='Sign in to the MMT';content.append(link);}}catch(error){status.textContent=error.message;button.disabled=false;}};
}
window.addEventListener('hashchange',()=>{resetToken=null;render();});render();
