/* Illustrative catalog only; never writes to the MMT portal or submits applications. */
(async()=>{
 const results=document.querySelector('#ministry-results'),status=document.querySelector('#results-status');
 const search=document.querySelector('#ministry-search'),destination=document.querySelector('#destination-filter'),areas=document.querySelector('#area-filters'),shortlistButton=document.querySelector('#shortlist-filter');
 const dialog=document.querySelector('#ministry-dialog'),content=document.querySelector('#ministry-dialog-content');
 const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let ministries=[],selectedAreas=new Set(),saved=new Set(),onlySaved=false,lastTrigger=null;
 try{saved=new Set(JSON.parse(sessionStorage.getItem('hs-sample-shortlist')||'[]'));}catch{}
 const save=()=>{try{sessionStorage.setItem('hs-sample-shortlist',JSON.stringify([...saved]));}catch{}};
 function toggle(id){saved.has(id)?saved.delete(id):saved.add(id);save();render();}
 function render(){
  const term=search.value.trim().toLowerCase();
  const filtered=ministries.filter(m=>(!destination.value||m.destination===destination.value)&&(!selectedAreas.size||m.areas.some(a=>selectedAreas.has(a)))&&(!onlySaved||saved.has(m.id))&&(!term||[m.name,m.destination,m.country,m.summary,m.role,...m.areas,...m.skills,m.areas.includes('Women & exploitation recovery')?'prostitution trafficking sex work':''].join(' ').toLowerCase().includes(term)));
  status.textContent=`${filtered.length} sample ${filtered.length===1?'ministry':'ministries'}${onlySaved?' in your shortlist':''}`;
  shortlistButton.textContent=`${onlySaved?'Showing shortlist':'My shortlist'} (${saved.size})`;shortlistButton.setAttribute('aria-pressed',String(onlySaved));
  results.innerHTML=filtered.length?filtered.map(m=>`<article class="ministry-card"><div class="ministry-card-photo"><img src="/assets/${esc(m.image)}" alt="Illustrative destination photo: ${esc(m.destination)}" loading="lazy"><span>Sample ministry</span><button type="button" class="save-ministry" data-save="${esc(m.id)}" aria-pressed="${saved.has(m.id)}" aria-label="${saved.has(m.id)?'Remove':'Save'} ${esc(m.name)}">${saved.has(m.id)?'Saved ✓':'Save +'}</button></div><div class="ministry-card-copy"><p class="ministry-place">${esc(m.destination)} · ${esc(m.country)}</p><h3>${esc(m.name)}</h3><p>${esc(m.summary)}</p><div class="service-tags">${m.areas.map(a=>`<span>${esc(a)}</span>`).join('')}</div><p class="sample-duration">Illustrative stay · ${esc(m.duration)}</p><button type="button" class="ministry-open" data-open="${esc(m.id)}">Explore this ministry ↗</button></div></article>`).join(''):'<div class="empty-results"><h3>No matches yet.</h3><p>Try another destination or area of service, or clear the filters. Your saved examples stay in your shortlist.</p><button type="button" data-reset>Show all sample ministries</button></div>';
  const params=new URLSearchParams();if(search.value)params.set('q',search.value);if(destination.value)params.set('destination',destination.value);selectedAreas.forEach(a=>params.append('area',a));if(onlySaved)params.set('saved','1');history.replaceState(null,'',location.pathname+(params.size?'?'+params:'')+location.hash);
 }
 function reset(){search.value='';destination.value='';selectedAreas.clear();areas.querySelectorAll('input').forEach(i=>i.checked=false);onlySaved=false;render();}
 function open(id,trigger){const m=ministries.find(m=>m.id===id);lastTrigger=trigger;content.innerHTML=`<p class="overline">Sample ministry · ${esc(m.destination)}</p><h2 id="ministry-dialog-title">${esc(m.name)}</h2><p class="dialog-summary">${esc(m.summary)}</p><p class="dialog-sample">Fictional ministry profile for this prototype. This is not an available placement or a confirmed partner.</p><h3>How you might contribute</h3><p>${esc(m.role)}</p><h3>Skills to bring or develop</h3><div class="service-tags">${m.skills.map(s=>`<span>${esc(s)}</span>`).join('')}</div><h3>Learning & support</h3><p>${esc(m.support)}</p><p><strong>Illustrative duration:</strong> ${esc(m.duration)}. Timing, costs, eligibility, supervision, and any academic credit would need to be confirmed for a real opportunity.</p><div class="dialog-actions"><button class="path-button" data-dialog-save="${esc(m.id)}" aria-pressed="${saved.has(id)}">${saved.has(id)?'Remove from shortlist':'Save to shortlist'}</button><a href="https://hopesojourns.com/schedule/">Discuss my internship interests ↗</a></div>`;dialog.showModal();}
 document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{const id=lastTrigger?.dataset.open;document.querySelector(`[data-open="${id}"]`)?.focus();});
 content.addEventListener('click',e=>{const b=e.target.closest('[data-dialog-save]');if(b){toggle(b.dataset.dialogSave);b.textContent=saved.has(b.dataset.dialogSave)?'Remove from shortlist':'Save to shortlist';b.setAttribute('aria-pressed',String(saved.has(b.dataset.dialogSave)));}});
 results.addEventListener('click',e=>{const openButton=e.target.closest('[data-open]'),saveButton=e.target.closest('[data-save]');if(openButton)open(openButton.dataset.open,openButton);if(saveButton){const id=saveButton.dataset.save;toggle(id);document.querySelector(`[data-save="${id}"]`)?.focus();}if(e.target.closest('[data-reset]'))reset();});
 search.addEventListener('input',render);destination.addEventListener('change',render);areas.addEventListener('change',e=>{e.target.checked?selectedAreas.add(e.target.value):selectedAreas.delete(e.target.value);render();});shortlistButton.addEventListener('click',()=>{onlySaved=!onlySaved;render();});document.querySelector('.reset-filters').addEventListener('click',reset);
 try{const r=await fetch('/internships/opportunities.json');if(!r.ok)throw Error();ministries=(await r.json()).ministries;saved=new Set([...saved].filter(id=>ministries.some(m=>m.id===id)));const places=[...new Set(ministries.map(m=>m.destination))].sort();places.forEach(place=>{const o=new Option(place,place);destination.add(o);});const allAreas=[...new Set(ministries.flatMap(m=>m.areas))].sort();areas.innerHTML=allAreas.map(a=>`<label><input type="checkbox" value="${esc(a)}"><span>${esc(a)}</span></label>`).join('');const params=new URLSearchParams(location.search);search.value=params.get('q')||'';destination.value=places.includes(params.get('destination'))?params.get('destination'):'';selectedAreas=new Set(params.getAll('area').filter(a=>allAreas.includes(a)));areas.querySelectorAll('input').forEach(i=>i.checked=selectedAreas.has(i.value));onlySaved=params.get('saved')==='1';render();}catch{status.textContent='The sample explorer could not load. Please refresh or talk with Brent about your interests.';}
})();
