'use strict';
window.DonationSplits={async open({load,save,onSaved}){
 const data=await load();const choices=data.people||data.knownDonors?.map((p,i)=>({...p,id:'known-'+i}))||[];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=c=>(c/100).toLocaleString(undefined,{style:'currency',currency:'USD'});
 const dialog=document.createElement('dialog');dialog.className='donation-split-dialog record-dialog';dialog.setAttribute('aria-label','Split donation');
 dialog.innerHTML=`<form><h2>Split donation</h2><p>Original payment: <strong>${esc(data.parent.name)}</strong> · ${esc(data.parent.transaction_date.slice(0,10))}</p><p>Allocate <strong>${money(data.totalCents)}</strong> before fees. The original payment stays in the ledger and is counted once.</p>${data.parent.fee?`<p>Processing fee: ${money(Math.abs(Math.round(data.parent.fee*100)))} · Net deposit: ${money(Math.round(data.parent.net*100))}</p>`:''}<div class="donation-split-rows"></div><button class="search-button" type="button" data-add>Add donor</button><p role="status" data-total></p><p role="alert" data-error></p><details><summary>Change history</summary>${data.history.map(h=>`<p>${esc(new Date(h.updated_at).toLocaleString())} · ${esc(h.actor)} · Revision ${h.revision}<br>${esc(JSON.parse(h.allocations_json).map(a=>`${a.firstName} ${a.lastName}: ${money(a.amountCents)} (${a.date})`).join('; ')||'Split undone')}</p>`).join('')||'<p>No changes yet.</p>'}</details><footer><button class="search-button" type="button" data-cancel>Cancel</button>${data.allocations.length?'<button class="search-button" type="button" data-undo>Undo split</button>':''}<button class="button primary" type="submit">Save split</button></footer></form>`;
 const form=dialog.querySelector('form'),container=dialog.querySelector('.donation-split-rows');
 const input=(key,label,value='',type='text',extra='')=>`<label class="field">${label}<input name="${key}" type="${type}" value="${esc(value)}" ${extra}></label>`;
 function add(a={}){
  const row=document.createElement('fieldset');row.innerHTML=`<legend>Donor</legend>${choices.length?`<label class="field">Choose existing donor or enter a new donor<select name="personId"><option value="">New donor</option>${choices.map(p=>`<option value="${esc(p.id)}" ${p.id===a.personId?'selected':''}>${esc(p.first_name+' '+p.last_name+' · '+p.email)}</option>`).join('')}</select></label>`:a.personId?`<input type="hidden" name="personId" value="${esc(a.personId)}">`:''}${input('firstName','First name',a.firstName,'text','required maxlength="70"')}${input('lastName','Last name',a.lastName,'text','required maxlength="70"')}${input('email','Email (if available)',a.email,'email','maxlength="254"')}${input('date','Original donation date',a.date||data.parent.transaction_date.slice(0,10),'date','required')}${input('amount','Donation amount',a.amountCents?(a.amountCents/100).toFixed(2):'','number','required min="0.01" step="0.01"')}${input('note','Notes',a.note,'text','maxlength="1000"')}<button class="search-button" type="button" data-remove>Remove donor</button>`;
  row.querySelector('[data-remove]').onclick=()=>{row.remove();totals();};
  const select=row.querySelector('select');const lock=()=>{for(const key of ['firstName','lastName','email'])row.querySelector(`[name=${key}]`).readOnly=!!(data.people&&select?.value);};if(select)select.onchange=()=>{const p=choices.find(p=>p.id===select.value);for(const [k,v] of Object.entries({firstName:p?.first_name||'',lastName:p?.last_name||'',email:p?.email||''})){row.querySelector(`[name=${k}]`).value=v;}lock();};lock();
  container.append(row);totals();
 }
 function totals(){const sum=[...container.querySelectorAll('[name=amount]')].reduce((n,e)=>n+Math.round(Number(e.value||0)*100),0);dialog.querySelector('[data-total]').textContent='Amount remaining: '+money(data.totalCents-sum);}
 const close=()=>{dialog.close();dialog.remove();};dialog.querySelector('[data-cancel]').onclick=close;dialog.addEventListener('cancel',()=>dialog.remove());dialog.querySelector('[data-add]').onclick=()=>{if(container.children.length<100)add();};form.addEventListener('input',()=>{dialog.querySelector('[data-error]').textContent='';totals();});
 async function submit(allocations){const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await save({revision:data.revision,parentVersion:data.parent.updated_at,allocations});close();await onSaved?.();}catch(e){dialog.querySelector('[data-error]').textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}}
 form.onsubmit=e=>{e.preventDefault();const allocations=[...container.children].map(row=>{const a=Object.fromEntries([...row.querySelectorAll('input,select')].map(e=>[e.name,e.value]));a.amountCents=Math.round(Number(a.amount)*100);delete a.amount;if(a.personId?.startsWith('known-'))delete a.personId;return a;});if(allocations.length<2||allocations.reduce((n,a)=>n+a.amountCents,0)!==data.totalCents){dialog.querySelector('[data-error]').textContent='Add at least two donors and allocate the full amount.';return;}submit(allocations);};
 dialog.querySelector('[data-undo]')?.addEventListener('click',()=>{if(confirm('Undo this split? Giving statements will use the original payer again.'))submit([]);});
 document.body.append(dialog);(data.allocations.length?data.allocations:[{},{}]).forEach(add);dialog.showModal();
}};
