(()=>{
 const fields=[['firstName','First name','first_name'],['lastName','Last name','last_name'],['email','Email','email'],['phone','Phone','phone'],['contactPreference','Preferred contact','contact_preference'],['fieldOfStudy','Background / skills','field_of_study']];
 let generation=0;
 async function call(id,body){const session=body?await (await fetch('/api/interest/admin/session',{cache:'no-store'})).json():null;const r=await fetch('/api/interest/admin/interest-reviews/'+encodeURIComponent(id),{method:body?'POST':'GET',cache:'no-store',headers:{'Content-Type':'application/json',...(session?{'X-CSRF-Token':session.csrfToken}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to load review.');return data;}
 async function open(host,id){const token=++generation,esc=window.HSPlanning.esc;host.textContent='Loading submitted information and matching contacts…';try{const d=await call(id);if(token!==generation||!host.isConnected)return;const s=d.intake.submitted;
 host.innerHTML=`<p><a href="/admin/ministry/#inbox">← Inbox</a></p><p>${d.intake.status==='pending'?'No contact or interest relationships have been changed by this submission.':'This submission is resolved: '+esc(d.intake.decision)+'.'}</p><div class="planning-grid"><article class="planning-card"><h2>Submitted information</h2>${fields.map(([key,label])=>`<p><strong>${label}:</strong> ${esc(s[key]||'Not supplied')}</p>`).join('')}<p><strong>Interests:</strong> ${esc(s.opportunities.join(', '))}</p><p><strong>Preferred timing:</strong> ${esc(s.preferredTiming)}</p><p><strong>Message:</strong> ${esc(s.message)}</p><p>Received ${esc(window.HSPlanning.date(d.intake.createdAt))}</p></article><section><h2>Matching contacts (${d.matches.length})</h2>${d.matches.map(m=>`<article class="planning-card"><h3>${esc(m.first_name+' '+m.last_name)}</h3><p><strong>Matches by ${m.matchBy==='both'?'email and phone':esc(m.matchBy)}</strong></p>${fields.map(([,label,key])=>`<p>${label}: ${esc(m[key]||'Not recorded')}</p>`).join('')}<p>Organization: ${esc(m.organization)}</p><p>Contact ID: ${esc(m.id)}</p></article>`).join('')||'<p>No contacts currently match. You can explicitly approve a new contact.</p>'}</section></div><p role="status"></p>${d.intake.status==='pending'&&d.canReview?`<fieldset><legend>Choose a review decision</legend><p><button type="button" data-action="new">Add as a new contact</button></p><label>Existing contact<select data-contact><option value="">Choose a matching contact</option>${d.matches.map(m=>`<option value="${esc(m.id)}">${esc(m.first_name+' '+m.last_name+' · '+m.email+' · '+m.phone)}</option>`).join('')}</select></label><div data-fields></div><button type="button" data-action="update" disabled>Update an existing contact</button><p><button type="button" data-action="reject">Reject</button></p></fieldset>`:''}<details><summary>Review history</summary>${d.history.map(h=>{let m={};try{m=JSON.parse(h.metadata_json||'{}');}catch{}return `<p>${esc(h.created_at)} · ${esc(h.event_type)} · ${esc(m.decision||'')} · Reviewer: ${esc(m.reviewerId||'System')} · Resulting contact: ${esc(m.personId||'None')}</p>`;}).join('')}</details>`;
 const select=host.querySelector('[data-contact]');if(select)select.onchange=()=>{const m=d.matches.find(m=>m.id===select.value);host.querySelector('[data-action=update]').disabled=!m;host.querySelector('[data-fields]').innerHTML=m?`<p>Select only the fields to replace. Unchecked fields and unrelated history remain unchanged; submitted interests will be attached.</p>${fields.map(([key,label,column])=>`<label class="planning-check"><input type="checkbox" name="applyField" value="${key}"><span><strong>${label}</strong>: ${esc(m[column]||'Empty')} → ${esc(s[key]||'Empty')}</span></label>`).join('')}`:'';};
 host.querySelectorAll('[data-action]').forEach(button=>button.onclick=async()=>{const action=button.dataset.action,personId=select?.value;if(action==='update'&&!personId)return;const chosen=[...host.querySelectorAll('[name=applyField]:checked')].map(i=>i.value);
 const question=action==='new'?'Create a separate contact even if email, phone, or name matches? The submitted interests will be attached to the new contact.':action==='reject'?'Reject this submission without creating or changing a contact?':'Apply the selected '+chosen.length+' fields and attach the submitted interests to this contact?';if(!confirm(question))return;
 host.querySelectorAll('[data-action]').forEach(b=>b.disabled=true);try{await call(id,{action,personId,fields:chosen,revision:d.revision,confirmSeparate:action==='new'});await open(host,id);}catch(e){host.querySelector('[role=status]').textContent=e.message+' Reopen this review from Inbox to refresh.';host.querySelectorAll('[data-action]').forEach(b=>b.disabled=false);}});
 }catch(e){if(token===generation)host.textContent=e.message;}}
 window.HSInterestReview={open};
})();
