/* Shared task and follow-up workspace. Permissions are checked again by the API. */
(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=v=>v?new Date(String(v).includes('T')?v:String(v).slice(0,10)+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'No date';
 let csrf='',data=null;
 async function api(path,body){if(body&&!csrf)csrf=(await (await fetch('/api/interest/admin/session',{cache:'no-store'})).json()).csrfToken;const r=await fetch('/api/interest/admin/planning'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load planning tools.');return d;}
 function dialog(title,html,save){const d=document.createElement('dialog');d.className='planning-dialog';d.innerHTML=`<form><header><h2>${esc(title)}</h2><button type="button" data-close aria-label="Close">×</button></header>${html}<p role="status"></p><footer><button type="button" data-close>Cancel</button><button type="submit">Save</button></footer></form>`;document.body.append(d);let dirty=false;d.addEventListener('input',()=>dirty=true);const close=()=>{if(!dirty||confirm('Discard unsaved changes?'))d.close();};d.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('close',()=>d.remove());d.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=d.querySelector('[type=submit]');b.disabled=true;try{await save(Object.fromEntries(new FormData(e.target)),e.target);dirty=false;d.close();}catch(error){d.querySelector('[role=status]').textContent=error.message;b.disabled=false;}};d.showModal();return d;}
 const options=(items,value)=>'<option value="">None</option>'+items.map(([id,name])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(name)}</option>`).join('');
 function editTask(task={},defaults={},reload){const t={...defaults,...task};dialog(t.id?'Edit task':'Add task',`<label>Task<input name="title" required maxlength="180" value="${esc(t.title)}"></label><label>Details<textarea name="notes" maxlength="4000">${esc(t.notes)}</textarea></label><div class="planning-grid"><label>Trip<select name="tripId">${options(data.canEdit.trips?data.trips.map(t=>[t.id,t.title]):[],t.trip_id)}</select></label><label>Contact to follow up with<select name="personId">${options(data.canEdit.contacts?data.people.map(p=>[p.id,p.first_name+' '+p.last_name]):[],t.person_id)}</select></label><label>Responsible person<select name="ownerId">${options(data.owners.map(p=>[p.id,p.first_name+' '+p.last_name]),t.owner_id)}</select></label><label>Due / next contact date<input name="dueDate" type="date" value="${esc(t.due_date)}"></label></div><label>Status<select name="status">${['open','completed','canceled'].map(s=>`<option ${s===(t.status||'open')?'selected':''}>${s}</option>`).join('')}</select></label>`,async v=>{await api('/tasks',{...v,id:t.id,revision:t.revision});await reload();});}
 async function tasks(container,defaults={}){container.textContent='Loading tasks…';try{const current=await api('/dashboard');if(!container.isConnected)return;data=current;const list=current.tasks.filter(t=>(!defaults.trip_id||t.trip_id===defaults.trip_id)&&(!defaults.person_id||t.person_id===defaults.person_id));container.innerHTML=`<div class="planning-heading"><h2>${defaults.person_id?'Contact follow-up':'Tasks & follow-up'}</h2>${Object.values(current.canEdit).some(Boolean)?'<button data-new>Add task</button>':''}</div><p>Keep preparation and relationship follow-up here. Due dates appear on Home; no automatic emails are sent.</p><label>Show<select data-filter><option value="open">Open tasks</option><option value="completed">Completed</option><option value="canceled">Canceled</option><option value="all">All tasks</option></select></label><div data-tasks></div>`;
 const draw=()=>{const filter=container.querySelector('[data-filter]').value;container.querySelector('[data-tasks]').innerHTML=list.filter(t=>filter==='all'||t.status===filter).map(t=>`<article class="planning-card"><h3>${esc(t.title)}</h3><p>${esc(t.notes)}</p><p>${esc([t.trip_title,t.person_name,t.owner_name||'Unassigned',date(t.due_date)].filter(Boolean).join(' · '))}${t.status==='open'&&t.due_date&&t.due_date<new Date().toLocaleDateString('en-CA')?' · Overdue':''}</p>${t.canEdit?`<button data-edit="${esc(t.id)}">Edit / complete</button>`:''}</article>`).join('')||'<p>No tasks in this view.</p>';container.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editTask(list.find(t=>t.id===b.dataset.edit),defaults,()=>tasks(container,defaults)));};container.querySelector('[data-filter]').onchange=draw;container.querySelector('[data-new]')?.addEventListener('click',()=>editTask({},defaults,()=>tasks(container,defaults)));draw();}catch(e){container.textContent=e.message;}}
 async function home(container){try{const d=await api('/dashboard');if(!container.isConnected)return;const today=new Date().toLocaleDateString('en-CA');const upcoming=d.trips.filter(t=>t.end_date>=today).slice(0,6);const due=d.tasks.filter(t=>t.status==='open').slice(0,8);let recent=[];try{recent=JSON.parse(sessionStorage.getItem('hs-recent-trips')||'[]');}catch{}const allowed=d.trips.filter(t=>recent.includes(t.id));container.innerHTML=`<div class="planning-heading"><h2>Upcoming journeys</h2><a href="/admin/trips/">All trips</a></div><div class="planning-grid">${upcoming.map(t=>`<article class="planning-card"><h3><a href="/admin/trips/?trip=${esc(t.id)}">${esc(t.title)}</a></h3><p>${date(t.start_date)} – ${date(t.end_date)}</p>${t.status==='completed'?'<p>Check status: marked Completed before the end date.</p>':''}<p data-ready="${esc(t.id)}">Checking preparation…</p></article>`).join('')||'<p>No upcoming trips.</p>'}</div><h2>Tasks and deadlines</h2>${due.map(t=>`<p><a href="/admin/ministry/#tasks">${esc(t.title)}</a> · ${date(t.due_date)} · ${esc(t.owner_name||'Unassigned')}</p>`).join('')||'<p>No open tasks.</p>'}<a href="/admin/ministry/#tasks">Manage tasks & follow-up</a>${allowed.length?'<h2>Recently opened trips</h2>'+allowed.map(t=>`<p><a href="/admin/trips/?trip=${esc(t.id)}">${esc(t.title)}</a></p>`).join(''):''}`;
 await Promise.all(upcoming.map(async t=>{const node=container.querySelector(`[data-ready="${t.id}"]`);try{const r=await api('/trips/'+t.id+'/readiness');if(node?.isConnected)node.textContent=r.sections.filter(s=>['reviewed','not_applicable'].includes(s.state)).length+' of 4 preparation areas reviewed';}catch{if(node)node.textContent='Open trip to review preparation.';}}));}catch(e){container.textContent=e.message;}}
 window.HSPlanning={api,dialog,esc,date,tasks,home};
})();
