-- Additive bookkeeping extensions. Existing ledger and receipts remain authoritative.
CREATE TABLE finance_settings (id TEXT PRIMARY KEY CHECK(id='primary'), organization_name TEXT NOT NULL DEFAULT 'Hope Sojourns', reporting_year INTEGER NOT NULL DEFAULT 2026, contact_email TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL);
INSERT INTO finance_settings(id,updated_at) VALUES('primary',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
CREATE TABLE finance_review (ledger_id TEXT PRIMARY KEY REFERENCES ledger_entries(id) ON DELETE CASCADE, trip_id TEXT REFERENCES trips(id), ministry_id TEXT REFERENCES ministries(id), status TEXT NOT NULL DEFAULT 'included' CHECK(status IN ('included','excluded','needs_review')), accountant_review INTEGER NOT NULL DEFAULT 0, reimbursable INTEGER NOT NULL DEFAULT 0, reimbursed INTEGER NOT NULL DEFAULT 0, notes TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL, CHECK(reimbursed=0 OR reimbursable=1));
CREATE TABLE finance_rates (id TEXT PRIMARY KEY, label TEXT NOT NULL, effective_from TEXT NOT NULL, effective_to TEXT NOT NULL, rate REAL NOT NULL CHECK(rate>=0 AND rate<=100), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), CHECK(effective_to>=effective_from));
CREATE TRIGGER finance_rates_overlap_insert BEFORE INSERT ON finance_rates WHEN NEW.active=1 AND EXISTS(SELECT 1 FROM finance_rates WHERE active=1 AND effective_from<=NEW.effective_to AND effective_to>=NEW.effective_from) BEGIN SELECT RAISE(ABORT,'Mileage rate dates overlap'); END;
CREATE TRIGGER finance_rates_overlap_update BEFORE UPDATE ON finance_rates WHEN NEW.active=1 AND EXISTS(SELECT 1 FROM finance_rates WHERE id<>NEW.id AND active=1 AND effective_from<=NEW.effective_to AND effective_to>=NEW.effective_from) BEGIN SELECT RAISE(ABORT,'Mileage rate dates overlap'); END;
CREATE TABLE finance_routes (id TEXT PRIMARY KEY, name TEXT NOT NULL, origin TEXT NOT NULL, destination TEXT NOT NULL, purpose TEXT NOT NULL, miles REAL NOT NULL CHECK(miles>0), tolls REAL NOT NULL DEFAULT 0 CHECK(tolls>=0), trip_id TEXT REFERENCES trips(id), ministry_id TEXT REFERENCES ministries(id), archived INTEGER NOT NULL DEFAULT 0);
CREATE TABLE finance_mileage (id TEXT PRIMARY KEY, travel_date TEXT NOT NULL, origin TEXT NOT NULL, destination TEXT NOT NULL, purpose TEXT NOT NULL, miles REAL NOT NULL CHECK(miles>0), tolls REAL NOT NULL DEFAULT 0 CHECK(tolls>=0), trip_id TEXT REFERENCES trips(id), ministry_id TEXT REFERENCES ministries(id), status TEXT NOT NULL DEFAULT 'included' CHECK(status IN ('included','excluded','needs_review')), accountant_review INTEGER NOT NULL DEFAULT 0, notes TEXT NOT NULL DEFAULT '', batch_id TEXT, deleted_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX finance_mileage_date ON finance_mileage(travel_date);
CREATE INDEX finance_mileage_batch ON finance_mileage(batch_id);
CREATE TABLE finance_invoices (id TEXT PRIMARY KEY, number TEXT NOT NULL UNIQUE, issued_date TEXT NOT NULL, due_date TEXT NOT NULL, bill_to TEXT NOT NULL, address TEXT NOT NULL DEFAULT '', trip_id TEXT REFERENCES trips(id), ministry_id TEXT REFERENCES ministries(id), notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','issued','void')), total_cents INTEGER NOT NULL CHECK(total_cents>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE finance_invoice_lines (id TEXT PRIMARY KEY, invoice_id TEXT NOT NULL REFERENCES finance_invoices(id), description TEXT NOT NULL, quantity REAL NOT NULL CHECK(quantity>0), unit_cents INTEGER NOT NULL CHECK(unit_cents>=0), total_cents INTEGER NOT NULL CHECK(total_cents>=0), sort_order INTEGER NOT NULL);
CREATE TABLE finance_invoice_payments (id TEXT PRIMARY KEY, invoice_id TEXT NOT NULL REFERENCES finance_invoices(id), ledger_id TEXT NOT NULL UNIQUE REFERENCES ledger_entries(id) ON DELETE RESTRICT, amount_cents INTEGER NOT NULL CHECK(amount_cents>0), created_at TEXT NOT NULL);
CREATE TRIGGER finance_invoice_payment_guard BEFORE INSERT ON finance_invoice_payments WHEN NOT EXISTS(SELECT 1 FROM finance_invoices i JOIN ledger_entries l ON l.id=NEW.ledger_id WHERE i.id=NEW.invoice_id AND i.status='issued' AND l.entry_type='income' AND ROUND(l.amount*100)=NEW.amount_cents AND COALESCE((SELECT SUM(amount_cents) FROM finance_invoice_payments WHERE invoice_id=i.id),0)+NEW.amount_cents<=i.total_cents) BEGIN SELECT RAISE(ABORT,'Invoice payment exceeds balance or is invalid'); END;
CREATE TRIGGER finance_invoice_funded_guard BEFORE UPDATE ON finance_invoices WHEN EXISTS(SELECT 1 FROM finance_invoice_payments WHERE invoice_id=OLD.id) BEGIN SELECT RAISE(ABORT,'Paid invoices must retain their original total and status'); END;
CREATE TRIGGER finance_invoice_ledger_guard BEFORE UPDATE OF amount,entry_type ON ledger_entries WHEN EXISTS(SELECT 1 FROM finance_invoice_payments WHERE ledger_id=OLD.id) AND (NEW.amount<>OLD.amount OR NEW.entry_type<>OLD.entry_type) BEGIN SELECT RAISE(ABORT,'Invoice payment amount and type are locked'); END;
