'use strict';
const content=document.querySelector('#content'),notice=document.querySelector('#status'),dialog=document.querySelector('#editor'),form=document.querySelector('#editor-form');
let csrf='',config,ledgerCategories,saveEditor,rows=[],page=1,filters={},view='',generation=0;
const today=()=>new Date().toLocaleDateString('en-CA');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value)||0);
const options=(items,value='')=>items.map(([id,label])=>`<option value="${esc(id)}" ${String(id)===String(value)?'selected':''}>${esc(label)}</option>`).join('');
const field=(name,label,value='',type='text',extra='')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name,label,items,value='')=>`<label>${esc(label)}<select name="${name}">${options(items,value)}</select></label>`;
const area=(name,label,value='')=>`<label>${esc(label)}<textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;
const check=(name,label,value=false)=>`<label class="check"><input type="checkbox" name="${name}" ${value?'checked':''}>${esc(label)}</label>`;
const button=(action,label,id='',extra='')=>`<button type="button" data-action="${action}" data-id="${esc(id)}" ${extra}>${esc(label)}</button>`;
const link=(url,label)=>`<a class="button" href="${esc(url)}" data-admin-link>${esc(label)}</a>`;
const tripName=id=>config.trips.find(t=>t.id===id)?.title||'';
const ministryName=id=>config.ministries.find(t=>t.id===id)?.name||'';
const related=(row={})=>`<div class="grid">${select('trip_id','Related trip',[['','Organization-wide'],...config.trips.map(t=>[t.id,t.title])],row.linked_trip_id||row.trip_id)}${select('ministry_id','Related ministry / partner',[['','None'],...config.ministries.map(t=>[t.id,t.name])],row.ministry_id)}</div>`;
const reviewStatus=[['included','Included'],['needs_review','Needs review'],['excluded','Excluded from reports']];
const badge=value=>`<span class="tag">${esc(String(value).replaceAll('_',' '))}</span>`;
async function api(path,body,method){const response=await fetch('/api/interest'+path,{method:method||(body?'POST':'GET'),credentials:'same-origin',headers:{...(body instanceof FormData?{}:{'Content-Type':'application/json'}),'X-CSRF-Token':csrf},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const data=await response.json();window.HSPhones?.records(data);if(!response.ok)throw new Error(data.error||'Unable to complete the request.');return data;}
function message(error){notice.textContent=error.message||String(error);}
function editor(title,html,save){document.querySelector('#editor-title').textContent=title;document.querySelector('#editor-fields').innerHTML=html;document.querySelector('#editor-status').textContent='';saveEditor=save;form.querySelector('[type=submit]').hidden=!save;dialog.showModal();}
form.addEventListener('submit',async event=>{event.preventDefault();if(!saveEditor)return;const submit=form.querySelector('[type=submit]');submit.disabled=true;try{const values=Object.fromEntries(new FormData(form));form.querySelectorAll('[type=checkbox]').forEach(el=>values[el.name]=el.checked);await saveEditor(values);dialog.close();await refresh();}catch(error){document.querySelector('#editor-status').textContent=error.message;}finally{submit.disabled=false;}});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());
document.addEventListener('click',event=>{if(event.target.closest('[data-admin-link]'))sessionStorage.setItem('hope-sojourns-admin-navigation','true');const target=event.target.closest('[data-action]');if(target)Promise.resolve(action(target)).catch(message);});
document.querySelector('#refresh').onclick=()=>refresh().catch(message);
window.addEventListener('hashchange',()=>{page=1;filters={};render().catch(message);});
function metric(label,value,detail=''){return `<article class="card"><span class="metric-label">${esc(label)}</span><strong class="metric-value">${esc(value)}</strong><small>${esc(detail)}</small></article>`;}
function table(headings,body){return `<div class="table-wrap"><table><thead><tr>${headings.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headings.length}" class="empty">No records match this view.</td></tr>`}</tbody></table></div>`;}
function pager(summary){const pages=Math.max(1,Math.ceil(summary.count/100));return `<div class="actions pager"><small>${Number(summary.count)} records · Page ${page} of ${pages}</small>${button('previous','Previous','',page<=1?'disabled':'')}${button('next','Next','',page>=pages?'disabled':'')}</div>`;}
function filterForm(kind='cash'){return `<form id="filters" class="filters">${field('from','From',filters.from||'','date')}${field('to','Through',filters.to||'','date')}${select('trip','Trip',[['','All trips'],...config.trips.map(t=>[t.id,t.title])],filters.trip)}${select('ministry','Ministry',[['','All ministries'],...config.ministries.map(t=>[t.id,t.name])],filters.ministry)}${select('status','Review status',[['','All statuses'],...reviewStatus],filters.status)}${kind==='cash'?select('source','Source',[['','All sources'],['manual','Manual'],['csm','CSM'],['import','Imported']],filters.source)+(view==='reports'?select('type','Type',[['','Income and expenses'],['income','Income'],['expense','Expenses']],filters.type):'')+field('search','Search',filters.search||''):''}<button type="submit">Apply filters</button>${button('clear','Clear')}</form>`;}
function wireFilters(){document.querySelector('#filters')?.addEventListener('submit',event=>{event.preventDefault();filters=Object.fromEntries(new FormData(event.target));page=1;render().catch(message);});}
function query(extra={}){return new URLSearchParams({...filters,...extra,page}).toString();}
function ledgerRows(entries){return entries.map(r=>`<tr><td>${esc(window.HSPlanning.date(r.transaction_date))}</td><td><strong>${esc(r.name||'—')}</strong><small>${esc(r.note||'')}</small></td><td>${esc(r.expense_category||r.budget_category)}<small>${esc(r.budget_category)}</small></td><td>${esc(tripName(r.linked_trip_id)||'Organization-wide')}<small>${esc(ministryName(r.ministry_id))}</small></td><td>${badge(r.review_status)}${r.reimbursable?'<small>'+(r.reimbursed?'Reimbursed':'Awaiting reimbursement')+'</small>':''}${r.accountant_review?'<small>Accountant review</small>':''}${r.invoice_number?`<small>Invoice ${esc(r.invoice_number)}</small>`:''}</td><td class="amount">${cash(r.amount)}<small>${esc(r.payment_type)}</small></td><td>${button('ledger-edit','Edit',r.id)}${button('review','Review',r.id)}${r.entry_type==='expense'?button('receipts',`Receipts (${r.receipt_count})`,r.id):''}${r.entry_type==='income'&&r.charitable_amount>0?button('donor-splits','Split donation',r.id):''}${button('record-details','Details',r.id)}</td></tr>`).join('');}
async function render(){
  const token=++generation;view=location.hash.slice(1)||'dashboard';if(!['dashboard','income','expenses','mileage','invoices','reports','settings'].includes(view))view='dashboard';
  document.querySelector('#page-title').textContent=({dashboard:'Dashboard',income:'Income',expenses:'Expenses',mileage:'Mileage',invoices:'Invoices',reports:'Reports',settings:'Finance settings'})[view];
  document.querySelector('#page-description').textContent=({dashboard:'A clear view of the money supporting your ministry.',income:'Received payments, gifts, and other income.',expenses:'Ministry spending, receipts, and reimbursements.',mileage:'Log ministry travel and reuse your regular routes.',invoices:'Bill travelers, churches, sponsors, and organizations.',reports:'Review and export the records you need.',settings:'Organization details and mileage rates.'})[view];
  document.querySelectorAll('.finance-sidebar nav a').forEach(a=>{if(a.getAttribute('href')==='#'+view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});window.HSMmtNav?.selection();notice.textContent='';
  if(view==='dashboard'){
    const year=config.settings.reporting_year,[ledger,mileage,invoices,review]=await Promise.all([api(`/admin/finance/records?from=${year}-01-01&to=${year}-12-31&status=included`),api(`/admin/finance/mileage?from=${year}-01-01&to=${year}-12-31&status=included`),api('/admin/finance/invoices'),api('/admin/finance/records?status=needs_review')]);if(token!==generation)return;
    rows=ledger.entries;const outstanding=invoices.entries.filter(i=>i.status==='issued').reduce((sum,i)=>sum+i.total_cents-i.paid_cents,0)/100;
    content.innerHTML=`<div class="actions">${button('new-income','Add income','','class="primary"')}${button('new-expense','Add expense')}${button('new-mileage','Log mileage')}${button('new-invoice','Create invoice')}<span class="spacer"></span><small>Reporting year ${year}</small></div><div class="metrics">${metric('Gross donor gifts',cash(ledger.summary.gross_giving),'What givers donated before payment fees')}${metric('Net income received',cash(ledger.summary.income),'Cash received after payment fees')}${metric('Expenses recorded',cash(ledger.summary.expenses))}${metric('Net cash activity',cash(ledger.summary.income-ledger.summary.expenses),'Net income less expenses; not a bank balance')}${metric('Ministry miles',Number(mileage.summary.miles).toLocaleString(),`${cash(mileage.summary.mileage_value)} mileage estimate`)}</div><article class="card"><h2>Needs attention</h2><div class="links"><a href="#invoices">${cash(outstanding)} outstanding on invoices</a><a href="#reports">${review.summary.count} transactions need review</a><a href="#settings">${mileage.summary.missing_rates||0} mileage logs missing a rate</a><a href="/admin/#csm-inbox" data-admin-link>Review the payment inbox</a></div></article><h2>Recent transactions</h2>${table(['Date','Payee / payer','Category','Trip / ministry','Status','Amount','Actions'],ledgerRows(rows.slice(0,10)))}`;
  }else if(view==='income'||view==='expenses'){
    const data=await api('/admin/finance/records?'+query({type:view==='income'?'income':'expense'}));if(token!==generation)return;rows=data.entries;
    content.innerHTML=`<div class="actions">${button(view==='income'?'new-income':'new-expense',view==='income'?'Add income':'Add expense','','class="primary"')}${link('/admin/#ledger','Import spreadsheet / full ledger')}${view==='expenses'?button('unreimbursed','Awaiting reimbursement'):''}<span class="spacer"></span><strong>${cash(view==='income'?data.summary.income:data.summary.expenses)}</strong></div>${filterForm()}${table(['Date',view==='income'?'Received from':'Paid to','Category','Trip / ministry','Status','Amount','Actions'],ledgerRows(rows))}${pager(data.summary)}`;
  }else if(view==='mileage'){
    const data=await api('/admin/finance/mileage?'+query());if(token!==generation)return;rows=data.entries;
    content.innerHTML=`<div class="actions">${button('new-mileage','Log mileage','','class="primary"')}${button('new-route','Save a route')}${button('routes','Saved routes')}${button('mileage-trash',filters.trash==='1'?'View active logs':'View trash')}<span class="spacer"></span>${button('export-mileage','Export CSV')}${button('print-mileage','Print')}</div><div class="metrics">${metric('Miles logged',Number(data.summary.miles).toLocaleString())}${metric('Mileage estimate',cash(data.summary.mileage_value),'Calculated using configured rates')}${metric('Tolls logged',cash(data.summary.tolls),'Not automatically posted as expenses')}${metric('Missing rates',data.summary.missing_rates||0,'Configure rates in Settings')}</div>${filterForm('mileage')}${table(['Date','Route / purpose','Trip / ministry','Miles','Rate / estimate','Status','Actions'],rows.map(r=>`<tr><td>${esc(r.travel_date)}</td><td>${esc(r.origin)} → ${esc(r.destination)}<small>${esc(r.purpose)}</small></td><td>${esc(tripName(r.trip_id)||'Organization-wide')}<small>${esc(ministryName(r.ministry_id))}</small></td><td class="amount">${Number(r.miles)}</td><td class="amount">${r.rate==null?'Rate needed':`${cash(r.rate)} / mile<small>${cash(r.mileage_value)}</small>`}</td><td>${badge(r.status)}</td><td>${r.deleted_at?button('restore-mileage','Restore',r.id):button('edit-mileage','Edit',r.id)+button('delete-mileage','Move to trash',r.id)}</td></tr>`).join(''))}${pager(data.summary)}<p class="muted">Trip and ministry links are optional. Organization-wide travel can be logged without either. Mileage values are estimates, separate from cash expenses. Record an actual reimbursement or toll payment in Expenses when HS pays it.</p>`;
  }else if(view==='invoices'){
    const data=await api('/admin/finance/invoices');if(token!==generation)return;rows=data.entries;
    content.innerHTML=`<div class="actions">${button('new-invoice','Create invoice','','class="primary"')}<small>Recording an invoice does not record income. Match payments after receiving them.</small></div>${table(['Invoice / dates','Bill to','Trip / ministry','Status','Total','Balance','Actions'],rows.map(r=>`<tr><td><strong>${esc(r.number)}</strong><small>Issued ${esc(r.issued_date)} · Due ${esc(r.due_date)}</small></td><td>${esc(r.bill_to)}</td><td>${esc(tripName(r.trip_id)||'Organization-wide')}<small>${esc(ministryName(r.ministry_id))}</small></td><td>${badge(r.status==='issued'?(r.paid_cents===r.total_cents?'paid':r.paid_cents?'partially paid':r.due_date<today()?'overdue':'issued'):r.status)}</td><td class="amount">${cash(r.total_cents/100)}</td><td class="amount">${r.status==='void'?'—':cash((r.total_cents-r.paid_cents)/100)}</td><td>${button('view-invoice','View / print',r.id)}${!r.paid_cents?button('edit-invoice','Edit',r.id):''}${r.status==='issued'&&r.paid_cents<r.total_cents?button('invoice-payment','Apply payment',r.id):''}</td></tr>`).join(''))}`;
  }else if(view==='reports'){
    const data=await api('/admin/finance/records?'+query());if(token!==generation)return;rows=data.entries;
    content.innerHTML=`<div class="actions">${button('export-cash','Export filtered CSV','','class="primary"')}${button('print-cash','Print / save PDF')}${link('/api/interest/admin/ledger/export.xlsx','Full ledger Excel export')}<span class="spacer"></span>${button('needs-review','Needs review')}${button('missing-receipts','Missing receipts')}${button('accountant','Accountant review')}</div>${filterForm()}<p class="muted">Totals reflect the filters below. Select Included to omit records excluded from reports. Excluded records always remain in your ledger.</p><div class="metrics">${metric('Income',cash(data.summary.income))}${metric('Expenses',cash(data.summary.expenses))}${metric('Net activity',cash(data.summary.income-data.summary.expenses))}${metric('Records',data.summary.count)}</div>${table(['Date','Payee / payer','Category','Trip / ministry','Status','Amount','Actions'],ledgerRows(rows))}${pager(data.summary)}`;
  }else{
    content.innerHTML=`<article class="card"><h2>Organization</h2><p><strong>${esc(config.settings.organization_name)}</strong><br>${esc(config.settings.contact_email)}<br>Reporting year: ${config.settings.reporting_year}</p>${button('organization','Edit organization')}</article><article class="card"><div class="actions"><h2>Mileage rates</h2><span class="spacer"></span>${button('new-rate','Add rate','','class="primary"')}</div><p>Enter the rate approved for HS ministry travel. Rates apply by travel date and cannot overlap. Editing a rate recalculates mileage estimates for that period; it does not change ledger expenses.</p>${table(['Label','Effective dates','Rate per mile','Status','Actions'],config.rates.map(r=>`<tr><td>${esc(r.label)}</td><td>${esc(r.effective_from)} – ${esc(r.effective_to)}</td><td>${cash(r.rate)}</td><td>${r.active?'Active':'Inactive'}</td><td>${button('edit-rate','Edit',r.id)}</td></tr>`).join(''))}</article><article class="card"><h2>Other settings</h2>${link('/admin/#settings','Portal security & guided trip help')} ${link('/admin/#ledger','Existing categories, imports & full ledger')}</article>`;
  }
  wireFilters();
}
async function refresh(){config=await api('/admin/finance/bootstrap');await render();}
function ledgerEditor(type,row={}){
  const cats=(name,value)=>[...new Set([...(ledgerCategories[name]||[]),...(value?[value]:[])])].map(s=>[s,s]);
  editor(row.id?'Edit '+type:'Add '+type,`<div class="grid">${field('transactionDate','Date',row.transaction_date||today(),'date','required')}${field('amount','Amount',row.amount||'','number','min="0.01" step="0.01" required')}</div>${field('name',type==='income'?'Received from':'Paid to',row.name||'','text','required maxlength="160"')}<div class="grid">${select('paymentType','Payment method',cats('paymentTypes',row.payment_type),row.payment_type||'Check')}${select('budgetCategory','Category / program',cats('budgetCategories',row.budget_category),row.budget_category||'General')}</div>${type==='expense'?select('expenseCategory','Expense type',cats('expenseCategories',row.expense_category),row.expense_category||'Other'):''}${select('transactionPurpose','Purpose',[['general','General'],...(type==='income'?[['donation','Donation received'],['scholarship_contribution','Scholarship contribution'],['trip_payment','Traveler payment'],['admin_fee','Administration fee']]:[]),['reimbursement','Reimbursement'],['trip_expense','Trip expense'],['refund','Refund'],['other','Other']],row.transaction_purpose||(type==='income'?'donation':'general'))}${type==='income'?field('charitableAmount','Charitable portion (zero for traveler fees)',row.charitable_amount||0,'number','min="0" step="0.01" required'):''}${area('note','Description',row.note)}${field('checkNumber','Check / reference number',row.check_number||'')}<p class="muted">Use Review after saving to link a trip or ministry and track reimbursement.</p>`,async values=>{await api('/admin/ledger/entries'+(row.id?'/'+row.id:''),{...values,entryType:type,personId:row.person_id||null,charitableAmount:type==='income'?Number(values.charitableAmount):0},row.id?'PUT':'POST');});
}
function review(row){editor('Review transaction',`${related(row)}${select('status','Report status',reviewStatus,row.review_status)}${check('accountant_review','Needs accountant review',row.accountant_review)}${row.entry_type==='expense'?check('reimbursable','Reimbursable',row.reimbursable)+check('reimbursed','Reimbursement received',row.reimbursed):''}${area('notes','Review notes',row.review_notes)}<p class="muted">Reimbursement flags organize follow-up. Record the actual money received separately in Income.</p>`,values=>api('/admin/finance/review/'+row.id,values,'PUT'));}
function mileageEditor(row={},route=false){
  editor(route?(row.id?'Edit saved route':'Save a route'):(row.id?'Edit mileage':'Log mileage'),`${!route&&!row.id?select('saved_route','Start with a saved route',[['','Enter a new route'],...config.routes.map(r=>[r.id,r.name])]):''}${route?field('name','Route name',row.name||'','text','required'):row.id?field('travel_date','Travel date',row.travel_date,'date','required'):area('dates','Travel dates — one date per line (YYYY-MM-DD)',today())}<div class="grid">${field('origin','From',row.origin||'','text','required')}${field('destination','To',row.destination||'','text','required')}</div>${field('purpose','Ministry purpose',row.purpose||'','text','required')}<div class="grid">${field('miles','Total miles per date',row.miles||'','number','min="0.01" step="0.01" required')}${field('tolls','Tolls per date',row.tolls||0,'number','min="0" step="0.01" required')}</div>${related(row)}${route?'':select('status','Report status',reviewStatus,row.status||'included')+check('accountant_review','Needs accountant review',row.accountant_review)+area('notes','Notes',row.notes)}<p class="muted">Logging mileage or tolls does not add a cash expense.</p>`,values=>api('/admin/finance/'+(route?'routes':'mileage')+(row.id?'/'+row.id:''),{...values,...(!route&&!row.id?{dates:values.dates.split(/[\n,]+/).map(s=>s.trim()).filter(Boolean)}:{})},row.id?'PUT':'POST'));
  form.elements.saved_route?.addEventListener('change',event=>{const selected=config.routes.find(r=>r.id===event.target.value);if(selected)for(const name of ['origin','destination','purpose','miles','tolls','trip_id','ministry_id'])form.elements[name].value=selected[name]??'';});
}
function rateEditor(row={}){editor(row.id?'Edit mileage rate':'Add mileage rate',`${field('label','Rate label',row.label||'HS ministry travel','text','required')}<div class="grid">${field('effective_from','Effective from',row.effective_from||`${config.settings.reporting_year}-01-01`,'date','required')}${field('effective_to','Effective through',row.effective_to||`${config.settings.reporting_year}-12-31`,'date','required')}</div>${field('rate','Dollars per mile',row.rate??'','number','required min="0" max="100" step="0.001"')}${check('active','Active',row.active??true)}<p>Use the rate approved for Hope Sojourns. This is not an automatic tax deduction calculation.</p>`,values=>api('/admin/finance/rates'+(row.id?'/'+row.id:''),values,row.id?'PUT':'POST'));}
function invoiceLine(row={}){return `<div class="line-item">${field('description','Description',row.description||'','text','required')}${field('quantity','Quantity',row.quantity||1,'number','min="0.001" step="0.001" required')}${field('unit_amount','Unit amount',row.unit_cents!=null?(row.unit_cents/100).toFixed(2):'','number','min="0" step="0.01" required')}${button('remove-line','Remove')}</div>`;}
async function invoiceEditor(id){const data=id?await api('/admin/finance/invoices/'+id):{invoice:{},lines:[{}]},r=data.invoice;editor(id?'Edit invoice':'Create invoice',`<div class="grid">${field('number','Invoice number',r.number||'HS-'+today().replaceAll('-','')+'-'+crypto.randomUUID().slice(0,6).toUpperCase(),'text','required')}${select('status','Status',[['draft','Draft'],['issued','Issued'],['void','Void']],r.status||'draft')}</div><div class="grid">${field('issued_date','Invoice date',r.issued_date||today(),'date','required')}${field('due_date','Due date',r.due_date||today(),'date','required')}</div>${field('bill_to','Bill to — traveler, church, sponsor, or organization',r.bill_to||'','text','required')}${area('address','Billing address',r.address)}${related(r)}<div id="invoice-lines">${data.lines.map(invoiceLine).join('')}</div>${button('add-line','Add line')}${area('notes','Invoice notes',r.notes)}<p class="muted">Trips and ministries are the organizing records. An invoice does not create a traveler charge or send a message.</p>`,values=>{const lines=[...document.querySelectorAll('.line-item')].map(el=>Object.fromEntries([...el.querySelectorAll('input')].map(input=>[input.name,input.value])));return api('/admin/finance/invoices'+(id?'/'+id:''),{...values,lines},id?'PUT':'POST');});}
async function invoicePrint(id){const data=await api('/admin/finance/invoices/'+id),r=data.invoice,paid=data.payments.reduce((sum,p)=>sum+p.amount_cents,0);const html=`<h1>${esc(config.settings.organization_name)}</h1><p>${esc(config.settings.contact_email)}</p><h2>Invoice ${esc(r.number)} · ${esc(r.status)}</h2><p>Invoice date: ${esc(r.issued_date)}<br>Due date: ${esc(r.due_date)}</p><p><strong>Bill to: ${esc(r.bill_to)}</strong><br>${esc(r.address).replaceAll('\n','<br>')}</p><p>${esc(tripName(r.trip_id))} ${esc(ministryName(r.ministry_id))}</p>${table(['Description','Quantity','Unit amount','Total'],data.lines.map(l=>`<tr><td>${esc(l.description)}</td><td>${l.quantity}</td><td>${cash(l.unit_cents/100)}</td><td>${cash(l.total_cents/100)}</td></tr>`).join(''))}<p>Total: <strong>${cash(r.total_cents/100)}</strong><br>Paid: ${cash(paid/100)}<br>Balance: ${r.status==='void'?'Void':cash((r.total_cents-paid)/100)}</p><p class="details">${esc(r.notes)}</p>${data.payments.length?'<h2>Payments received</h2>'+table(['Date','Method','Amount'],data.payments.map(p=>`<tr><td>${esc(p.transaction_date)}</td><td>${esc(p.payment_type)}</td><td>${cash(p.amount_cents/100)}</td></tr>`).join('')):''}`;editor('Invoice preview',html+data.payments.map(p=>button('unlink-payment','Remove payment link: '+cash(p.amount_cents/100),p.id,`data-invoice="${esc(id)}"`)).join('')+button('print-invoice','Print / save PDF'),null);document.querySelector('#print-content').innerHTML=html;}
async function allRecords(kind,extra={}){let current=1,result=[],data;do{data=await api('/admin/finance/'+kind+'?'+new URLSearchParams({...filters,...extra,page:current}));result.push(...data.entries);current++;}while(result.length<data.summary.count&&data.entries.length);return result;}
async function paymentEditor(id){const invoice=rows.find(r=>r.id===id),received=await allRecords('records',{from:'',to:'',trip:'',ministry:'',status:'',search:'',review:'',reimbursable:'',missing:'',source:'',type:'income'}),remaining=invoice.total_cents-invoice.paid_cents,candidates=received.filter(r=>!r.invoice_number&&Math.round(r.amount*100)<=remaining),operationId=crypto.randomUUID();editor('Apply received payment',`<p>Invoice ${esc(invoice.number)} · Balance ${cash(remaining/100)}</p><p>Select money already received in the ledger. Each selection applies the whole income entry; multiple entries can pay an invoice in installments.</p>${select('ledger_id','Received payment',[['','Choose a payment'],...candidates.map(r=>[r.id,`${r.transaction_date} · ${r.name||'Income'} · ${cash(r.amount)} · ${r.note||r.payment_type}`])])}<p>If the payment is not listed, add it in Income first. Payments already applied to another invoice and amounts above this balance are excluded.</p>`,values=>api('/admin/finance/invoices/'+id+'/payments',{...values,operationId}));}
async function receipts(id){const data=await api('/admin/ledger/entries/'+id+'/receipts');editor('Receipts',`${(data.receipts||[]).map(r=>`<p>${link('/api/interest/admin/ledger/entries/'+id+'/receipts/'+r.id+'/file',r.originalFileName||r.original_file_name||'Receipt')} ${button('delete-receipt','Delete',r.id,`data-ledger="${esc(id)}"`)}</p>`).join('')||'<p>No receipts attached.</p>'}${field('file','Upload receipt','','file','required accept=".pdf,.png,.jpg,.jpeg,.webp"')}`,()=>api('/admin/ledger/entries/'+id+'/receipts',new FormData(form)));}
function csvCell(value){let s=String(value??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
async function exportReport(kind,print=false){const data=await allRecords(kind==='mileage'?'mileage':'records'),headers=kind==='mileage'?['Date','From','To','Purpose','Miles','Rate','Mileage estimate','Tolls','Trip','Ministry','Status','Notes']:['Date','Type','Payee / payer','Category','Amount','Method','Trip','Ministry','Review status','Reimbursable','Reimbursed','Receipt count','Invoice','Description'];const body=data.map(r=>kind==='mileage'?[r.travel_date,r.origin,r.destination,r.purpose,r.miles,r.rate??'Rate needed',r.mileage_value??'',r.tolls,tripName(r.trip_id),ministryName(r.ministry_id),r.status,r.notes]:[r.transaction_date,r.entry_type,r.name,r.expense_category||r.budget_category,r.amount,r.payment_type,tripName(r.linked_trip_id),ministryName(r.ministry_id),r.review_status,r.reimbursable?'Yes':'No',r.reimbursed?'Yes':'No',r.receipt_count,r.invoice_number,r.note]);if(print){document.querySelector('#print-content').innerHTML=`<h1>${esc(config.settings.organization_name)}</h1><h2>${kind==='mileage'?'Mileage':'Ledger'} report</h2><p>${esc(filters.from||'Beginning')} through ${esc(filters.to||'present')} · ${data.length} records</p>${table(headers,body.map(r=>'<tr>'+r.map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>').join(''))}`;window.print();return;}const url=URL.createObjectURL(new Blob(['\uFEFF'+[headers,...body].map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`HS-${kind}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function action(b){const id=b.dataset.id,row=rows.find(r=>r.id===id);switch(b.dataset.action){
case'donor-splits':await window.DonationSplits.open({load:()=>api('/admin/ledger/entries/'+id+'/donor-splits'),save:body=>api('/admin/ledger/entries/'+id+'/donor-splits',body,'PUT'),onSaved:()=>render()});break;
case'new-income':ledgerEditor('income');break;case'new-expense':ledgerEditor('expense');break;case'ledger-edit':ledgerEditor(row.entry_type,row);break;case'review':review(row);break;
case'record-details':editor('Full record',`<div class="details">${Object.entries(row).map(([key,value])=>`<p><strong>${esc(key.replaceAll('_',' '))}</strong>: ${esc(value??'—')}</p>`).join('')}</div>${row.invoice_number?'<p>This income is linked to an invoice. Its amount and type are protected.</p>':button('delete-ledger','Delete transaction',row.id)}`,null);break;
case'delete-ledger':if(confirm('Permanently delete this transaction and its receipts?')){await api('/admin/ledger/entries/'+id,{},'DELETE');dialog.close();await render();}break;
case'receipts':await receipts(id);break;case'delete-receipt':if(confirm('Delete this receipt?')){await api('/admin/ledger/entries/'+b.dataset.ledger+'/receipts/'+id,{},'DELETE');dialog.close();await receipts(b.dataset.ledger);}break;
case'new-mileage':mileageEditor();break;case'edit-mileage':mileageEditor(row);break;case'new-route':mileageEditor({},true);break;case'edit-route':dialog.close();mileageEditor(config.routes.find(r=>r.id===id),true);break;
case'routes':editor('Saved routes',config.routes.map(r=>`<article class="card"><strong>${esc(r.name)}</strong><p>${esc(r.origin)} → ${esc(r.destination)} · ${r.miles} miles</p>${button('edit-route','Edit',r.id)} ${button('archive-route','Archive',r.id)}</article>`).join('')||'<p>No saved routes yet. Use Save a route to create one.</p>',null);break;
case'archive-route':if(confirm('Archive this saved route? Existing mileage logs are kept.')){await api('/admin/finance/routes/'+id,{},'DELETE');dialog.close();await refresh();}break;
case'delete-mileage':if(confirm('Move this mileage log to trash?')){await api('/admin/finance/mileage/'+id,{},'DELETE');await render();}break;case'restore-mileage':await api('/admin/finance/mileage/'+id,{},'PATCH');await render();break;
case'mileage-trash':filters.trash=filters.trash==='1'?'':'1';page=1;await render();break;case'new-rate':rateEditor();break;case'edit-rate':rateEditor(config.rates.find(r=>r.id===id));break;
case'organization':editor('Organization settings',field('organization_name','Organization name',config.settings.organization_name,'text','required')+field('contact_email','Contact email',config.settings.contact_email,'email')+field('reporting_year','Reporting year',config.settings.reporting_year,'number','required min="2000" max="2200" step="1"'),values=>api('/admin/finance/settings',values,'PUT'));break;
case'unlink-payment':if(confirm('Remove this invoice payment link? The income stays in the ledger and can be matched again.')){await api('/admin/finance/invoices/'+b.dataset.invoice+'/payments/'+id,{},'DELETE');dialog.close();await render();}break;
case'new-invoice':await invoiceEditor();break;case'edit-invoice':await invoiceEditor(id);break;case'add-line':document.querySelector('#invoice-lines').insertAdjacentHTML('beforeend',invoiceLine());break;case'remove-line':if(document.querySelectorAll('.line-item').length>1)b.closest('.line-item').remove();break;case'view-invoice':await invoicePrint(id);break;case'print-invoice':window.print();break;case'invoice-payment':await paymentEditor(id);break;
case'previous':page--;await render();break;case'next':page++;await render();break;case'clear':filters={};page=1;await render();break;
case'needs-review':filters={status:'needs_review'};page=1;await render();break;case'missing-receipts':filters={missing:'1'};page=1;await render();break;case'accountant':filters={review:'1'};page=1;await render();break;case'unreimbursed':filters={reimbursable:'1'};page=1;await render();break;
case'export-mileage':await exportReport('mileage');break;case'print-mileage':await exportReport('mileage',true);break;case'export-cash':await exportReport('cash');break;case'print-cash':await exportReport('cash',true);break;
}}
async function start(){try{const session=await api('/admin/session');csrf=session.csrfToken;const [bootstrap,ledger]=await Promise.all([api('/admin/finance/bootstrap'),api('/admin/ledger?pageSize=10')]);config=bootstrap;ledgerCategories=ledger.categories;document.querySelector('#environment').textContent=['127.0.0.1','localhost'].includes(location.hostname)?'Local preview · sample data':location.hostname==='hopesojourns.com'?'Live ministry records':'Test environment';await render();}catch(error){content.innerHTML='<p>Open the main portal to sign in, then return to Finances.</p>'+link('/admin/','Open sign in');message(error);}}
start();
