/* Trip-wide funding and batch cost review. Existing cost APIs remain authoritative. */
(() => {
  const cents = value => Math.round(Number(value || 0) * 100);
  const cash = value => new Intl.NumberFormat('en-US', {style:'currency',currency:'USD'}).format(value);
  const el = (tag, text, cls) => { const e=document.createElement(tag); if(text!==undefined)e.textContent=text; if(cls)e.className=cls; return e; };
  const active = w => w.costs.filter(c=>c.payment_status!=='canceled');
  const allocated = (w,id) => w.allocations.filter(a=>a.cost_item_id===id&&a.status!=='canceled').reduce((s,a)=>s+cents(a.amount),0);
  const target = (c,basis) => basis==='actual'&&(Number(c.actual_total)>0||c.payment_status==='paid')?cents(c.actual_total):cents(c.estimated_total);
  const fingerprint = w => JSON.stringify({costs:w.costs,allocations:w.allocations,count:w.trip.paying_traveler_count});
  
  function button(text,run){const b=el('button',text,'trip-button trip-button-outline');b.type='button';b.onclick=run;return b;}
  function cell(row,content,heading=false){const c=el(heading?'th':'td');if(heading)c.scope='col';c.append(content instanceof Node?content:document.createTextNode(content));row.append(c);return c;}
  function table(headers){const wrap=el('div',undefined,'trip-budget-table-scroll');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Budget comparison and editing table');const t=el('table',undefined,'trip-budget-table'),head=el('thead'),r=el('tr');headers.forEach(h=>cell(r,h,true));head.append(r);const body=el('tbody');t.append(head,body);wrap.append(t);return {wrap,body};}
  function modal(title){const d=el('dialog',undefined,'trip-budget-dialog');d.setAttribute('aria-label',title);const heading=el('h2',title),content=el('div'),status=el('p',undefined,'trip-form-status');status.setAttribute('role','status');const close=button('Close',()=>d.close());d.append(heading,content,status,close);d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();return {d,content,status,close};}
  function input(name,value,type='number'){const i=el('input');i.type=type;i.setAttribute('aria-label',name);if(type==='checkbox')i.checked=!!Number(value);else i.value=value??'';if(type==='number'){i.min='0';i.step='0.01';i.required=true;}return i;}
  function option(select,value,label){const o=el('option',label);o.value=value;select.append(o);}
  function readonly(){const u=window.MmtUser;return u&&!u.is_admin&&u.permissions?.trips!=='edit';}
  function comparison(w){const {wrap,body}=table(['Budget item','Estimated','Actual recorded','Allocated','Over / under budget','Still to allocate']);active(w).forEach(c=>{const r=el('tr'),a=allocated(w,c.id),t=target(c,'actual'),hasActual=Number(c.actual_total)>0||c.payment_status==='paid';[c.description,cash(c.estimated_total),hasActual?cash(c.actual_total):'Not recorded',cash(a/100),hasActual?cash((cents(c.actual_total)-cents(c.estimated_total))/100):'Not recorded',a>t?`${cash((a-t)/100)} overallocated`:cash((t-a)/100)].forEach(v=>cell(r,v));body.append(r);});return wrap;}
  function render(ctx){const host=document.querySelector('#trip-budget-tools');host.replaceChildren();const w=ctx.workspace;host.append(el('h3','Budget, actual costs & funding'),el('p','Positive variance means over budget; negative means under budget. Funding includes planned, confirmed and paid allocations. Remaining funding uses actual costs when recorded, otherwise estimates.'));const totals=el('div',undefined,'trip-finance-summary');for(const [label,val] of [['Estimated',active(w).reduce((s,c)=>s+cents(c.estimated_total),0)],['Actual recorded',active(w).reduce((s,c)=>s+cents(c.actual_total),0)],['Allocated',active(w).reduce((s,c)=>s+allocated(w,c.id),0)]]){const card=el('article');card.append(el('span',label),el('strong',cash(val/100)));totals.append(card);}host.append(totals,comparison(w));const actions=el('div',undefined,'trip-card-actions');const bulk=button('Edit multiple budget items',()=>bulkEdit(ctx)),fund=button('Fund the entire budget',()=>fundBudget(ctx));bulk.disabled=fund.disabled=readonly()||!active(w).length;actions.append(bulk,fund);host.append(actions);}
  async function fresh(ctx){return ctx.api(`/admin/trips/${ctx.workspace.trip.id}`);}
  async function save(ctx,resource,body){return ctx.api(`/admin/trips/${ctx.workspace.trip.id}/${resource}`,{method:'POST',body:JSON.stringify(body)});}
  function bulkEdit(ctx){const {d,content,status,close}=modal('Edit multiple budget items');content.append(el('p','Update the fields you need, then review and save once. Estimates remain separate from actual costs. Paid through HS costs require a paid date and may update the expense ledger. Saving costs reopens the budget for review.'));
    const form=el('form'),{wrap,body}=table(['Item','Quantity','Estimated each','Actual total','Needs estimate','Payment status','Paid date','Payment method']);const rows=[];
    active(ctx.workspace).forEach(c=>{const r=el('tr');cell(r,c.description);const fields={quantity:input(`${c.description}: Quantity`,c.quantity),estimatedUnitCost:input(`${c.description}: Estimated each`,c.estimated_unit_cost),actualTotal:input(`${c.description}: Actual total`,c.actual_total),needsEstimate:input(`${c.description}: Needs estimate`,c.needs_estimate,'checkbox'),paymentStatus:el('select'),paidDate:input(`${c.description}: Paid date`,c.paid_date,'date'),paymentMethod:input(`${c.description}: Payment method`,c.payment_method,'text')};fields.quantity.min='0.01';fields.paymentMethod.maxLength=80;fields.paymentStatus.setAttribute('aria-label',`${c.description}: Payment status`);['planned','committed','partially_paid','paid'].forEach(s=>option(fields.paymentStatus,s,{planned:'Planned',committed:'Committed',partially_paid:'Partially paid',paid:'Paid'}[s]));fields.paymentStatus.value=c.payment_status;if(c.calculation_method==='percentage_of_individual'){fields.quantity.disabled=fields.estimatedUnitCost.disabled=true;fields.estimatedUnitCost.title='Calculated percentage; use the item editor to change the rate.';}Object.values(fields).forEach(i=>cell(r,i));body.append(r);const read=()=>Object.fromEntries(Object.entries(fields).map(([key,i])=>[key,i.type==='checkbox'?i.checked:i.value]));rows.push({c,fields,read,original:read()});});
    const review=el('p');review.setAttribute('role','status');let pending=null;const submit=el('button','Review changes','trip-button trip-button-primary');submit.type='submit';form.append(wrap,review,submit);content.append(form);form.oninput=()=>{pending=null;submit.textContent='Review changes';review.textContent='';status.textContent='';};form.onsubmit=async event=>{event.preventDefault();if(readonly())return;const changed=rows.filter(r=>JSON.stringify(r.original)!==JSON.stringify(r.read()));if(!changed.length){status.textContent='No changes to save.';return;}if(!pending){pending=changed;review.textContent=`Ready to save ${changed.length} item(s): ${changed.map(r=>r.c.description).join(', ')}. ${changed.filter(r=>r.read().paymentStatus==='paid'&&r.c.settlement_route==='through_hs').length} paid-through-HS item(s) will be synchronized with the ledger.`;submit.textContent='Save all changes';return;}
      // Check every row before any writes; keep successful rows out of later retries.
      for(const row of changed){const v=row.read();if(v.paymentStatus==='paid'&&row.c.settlement_route==='through_hs'&&Number(v.actualTotal)>0&&!v.paidDate){status.textContent=`${row.c.description}: enter the paid date before saving.`;row.fields.paidDate.focus();return;}}
      submit.disabled=close.disabled=true;rows.forEach(row=>Object.values(row.fields).forEach(i=>i.disabled=true));d.oncancel=e=>e.preventDefault();let saved=0,writing=false;try{const current=await fresh(ctx);if(fingerprint(current)!==fingerprint(ctx.workspace))throw Error('The budget changed since this screen opened. Close this window and refresh before saving. Your entries remain visible here.');for(const row of changed){const payload=Object.fromEntries(Object.entries(row.c).map(([k,v])=>[k.replace(/_([a-z])/g,(_,l)=>l.toUpperCase()),v]));Object.assign(payload,row.read());if(row.c.calculation_method==='fixed'&&(payload.quantity!==row.original.quantity||payload.estimatedUnitCost!==row.original.estimatedUnitCost))payload.estimatedTotal=Number(payload.quantity)*Number(payload.estimatedUnitCost);writing=true;await save(ctx,'cost-items',payload);saved++;row.original=row.read();status.textContent=`Saved ${saved} of ${changed.length} items.`;}await ctx.reload();d.close();}catch(e){status.textContent=`${saved} item(s) confirmed saved. ${e.message}${writing?' Close and refresh to verify the remaining items before trying again. No further items were submitted.':''}`;submit.hidden=true;}finally{close.disabled=false;d.oncancel=null;}
    };
  }
  function fundBudget(ctx){const {d,content,status,close}=modal('Fund the entire budget');content.append(el('p','Assign the uncovered amount on each active budget item to one funding source. Existing allocations are preserved. New allocations are Planned; this does not record income, expenses or traveler payments.'));
    const source=el('select');source.setAttribute('aria-label','Funding source');option(source,'','Choose a funding source');ctx.sources.filter(s=>s.status==='active').forEach(s=>option(source,s.id,s.name));const basis=el('select');basis.setAttribute('aria-label','Funding amount basis');option(basis,'estimate','Original estimated budget');option(basis,'actual','Actual costs where recorded; estimates otherwise');const preview=el('div');let plan=[];const submit=button('Save funding allocations',async()=>{if(!source.value||!plan.length||readonly())return;submit.disabled=close.disabled=true;source.disabled=basis.disabled=true;d.oncancel=e=>e.preventDefault();let saved=0,writing=false;try{const current=await fresh(ctx);if(fingerprint(current)!==fingerprint(ctx.workspace))throw Error('The budget or funding changed. Close this window and refresh to review the new amounts.');for(const p of plan){writing=true;await save(ctx,'allocations',{costItemId:p.id,fundingSourceId:source.value,amount:p.amount/100,status:'planned',notes:'Trip-wide funding allocation'});saved++;status.textContent=`Saved ${saved} of ${plan.length} allocations.`;}await ctx.reload();d.close();}catch(e){status.textContent=`${saved} allocation(s) confirmed saved. ${e.message}${writing?' Close and refresh before trying again so saved allocations are not duplicated.':''}`;submit.hidden=true;}finally{close.disabled=false;d.oncancel=null;}});
    function update(){plan=active(ctx.workspace).map(c=>({id:c.id,name:c.description,amount:Math.max(0,target(c,basis.value)-allocated(ctx.workspace,c.id))})).filter(p=>p.amount>0);preview.replaceChildren();const {wrap,body}=table(['Budget item','Additional planned funding']);plan.forEach(p=>{const r=el('tr');cell(r,p.name);cell(r,cash(p.amount/100));body.append(r);});preview.append(wrap,el('p',`${plan.length} item(s) · ${cash(plan.reduce((s,p)=>s+p.amount,0)/100)} to allocate. Items already fully funded are skipped; excess allocations are not reduced.`));submit.disabled=!source.value||!plan.length||readonly();}source.onchange=basis.onchange=update;const sourceLabel=el('label','Funding source ');sourceLabel.append(source);const basisLabel=el('label','Amount to cover ');basisLabel.append(basis);content.append(sourceLabel,basisLabel,preview,submit);update();
  }
  window.TripBudgetTools={render};
})();
