(()=>{
 let generation=0;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
 const area=(name,label,value='',max=12000)=>`<label>${label}<textarea name="${name}" rows="5" maxlength="${max}">${esc(value)}</textarea></label>`;
 const check=(name,label,yes=false)=>`<label class="memory-check"><input type="checkbox" name="${name}" ${yes?'checked':''}>${label}</label>`;
 const readOnly=()=>!!window.MmtUser&&!window.MmtUser.is_admin&&window.MmtUser.permissions?.trips!=='edit';
 const button=(label,type='submit',action='')=>`<button class="trip-button trip-button-outline" type="${type}" ${readOnly()&&action!=='close'?'disabled title="Read-only access"':''} ${action?`data-memory-action="${action}"`:''}>${label}</button>`;
 function values(form){const v=Object.fromEntries(new FormData(form));v.portal_visible=!!form.elements.portal_visible?.checked;return v;}
 function message(panel,text){panel.querySelector('.memory-status').textContent=text;}
 async function call(tripId,path='',body,method){return api(`/admin/trips/${tripId}/memories${path}`,{method:method||(body?'POST':'GET'),...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});}
 async function optimized(file){if(file.size>25*1024*1024)throw Error('Choose an original photo smaller than 25 MB.');let bitmap;try{bitmap=await createImageBitmap(file);}catch{throw Error('This photo could not be opened. Export it as JPEG, PNG, or WebP and try again.');}try{const scale=Math.min(1,2000/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.88));if(!blob)throw Error('Could not prepare the photo.');return new File([blob],file.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'});}finally{bitmap.close();}}
 async function open(tab){const tripId=state.tripId;if(!tripId)return;const panel=document.querySelector(tab==='story'?'#trip-story-panel':'#trip-memories-panel');const token=++generation;panel.innerHTML='<p role="status">Loading trip memories…</p>';try{const data=await call(tripId);if(token!==generation||tripId!==state.tripId)return;if(tab==='story')renderStory(panel,data,tripId);else renderMemories(panel,data,tripId);}catch(e){if(token===generation)panel.textContent=e.message;}}
 function renderMemories(panel,data,tripId){panel.innerHTML=`<h2>Photos &amp; memories</h2><p>Add photos and dated journal notes throughout the trip. Choose what travelers can see. Public sharing is managed separately in Past-trip story.</p><p class="memory-status" role="status"></p><div class="memory-editor-grid"><form id="trip-photo-upload"><h3>Add photos</h3><label>Photos<input name="files" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple required></label>${field('event_date','Date','','date')}${field('caption','Caption for these photos','','text','maxlength="1000"')}${field('credit','Photo credit','','text','maxlength="180"')}${check('portal_visible','Show in traveler portal',true)}${button('Upload photos')}<small>Photos are resized for viewing. You can edit each title and image description below.</small></form><form id="trip-note-add"><h3>Add a trip note</h3>${field('title','Title','','text','required maxlength="180"')}${field('event_date','Date','','date')}${area('content','Reflection or journal note')}${field('credit','Author or credit','','text','maxlength="180"')}${check('portal_visible','Show in traveler portal',true)}${button('Save trip note')}</form></div><h3>Your collection</h3>${check('show_deleted','Show removed items')}<div class="memory-editor-list"></div>`;
 const list=panel.querySelector('.memory-editor-list');function renderList(){list.innerHTML=data.memories.filter(m=>panel.querySelector('[name=show_deleted]').checked?m.deleted_at:!m.deleted_at).map(m=>`<form data-memory-id="${esc(m.id)}">${m.kind==='photo'?`<img src="${esc(m.image_url)}" alt="${esc(m.alt_text)}" loading="lazy">`:''}${field('title','Title',m.title,'text','required maxlength="180"')}${field('event_date','Date',m.event_date,'date')}${m.kind==='photo'?field('caption','Caption',m.caption,'text','maxlength="1000"')+field('alt_text','Image description',m.alt_text,'text','required maxlength="300"'):area('content','Trip note',m.content)}${field('credit','Credit',m.credit,'text','maxlength="180"')}${check('portal_visible','Show in traveler portal',m.portal_visible)}<div class="memory-actions">${m.deleted_at?button('Restore','button','restore'):button('Save changes')+button('Remove','button','remove')}</div></form>`).join('')||'<p>No memories in this view.</p>';}
 panel.querySelector('[name=show_deleted]').onchange=renderList;renderList();
 panel.querySelector('#trip-photo-upload').onsubmit=async e=>{e.preventDefault();const form=e.target,files=[...form.elements.files.files];if(files.length>30){message(panel,'Upload up to 30 photos at a time.');return;}form.querySelector('button').disabled=true;let done=0;try{for(const file of files){message(panel,`Preparing photo ${done+1} of ${files.length}…`);const upload=new FormData(),v=values(form);upload.set('file',await optimized(file));upload.set('title',file.name.replace(/\.[^.]+$/,'').slice(0,180)||'Trip photo');upload.set('alt_text',String(v.caption||file.name).slice(0,300));for(const key of ['caption','credit','event_date','portal_visible'])upload.set(key,String(v[key]||''));await call(tripId,'',upload);done++;}if(state.tripId!==tripId)return;await open('memories');message(panel,`${done} photo${done===1?'':'s'} added.`);}catch(err){message(panel,`${done} photos added. ${err.message} Refresh the collection before retrying to avoid duplicates.`);}finally{form.querySelector('button').disabled=false;}};
 panel.querySelector('#trip-note-add').onsubmit=async e=>{e.preventDefault();await saveAction(panel,e.submitter,async()=>{await call(tripId,'',values(e.target));await open('memories');message(panel,'Trip note saved.');});};
 list.onsubmit=async e=>{e.preventDefault();const m=data.memories.find(m=>m.id===e.target.dataset.memoryId);await saveAction(panel,e.submitter,async()=>{await call(tripId,'/'+m.id,{...values(e.target),revision:m.revision},'PUT');await open('memories');message(panel,'Memory saved. Existing public stories keep their reviewed version until you publish an update.');});};
 list.onclick=async e=>{const b=e.target.closest('[data-memory-action]');if(!b)return;const m=data.memories.find(m=>m.id===b.closest('form').dataset.memoryId),restore=b.dataset.memoryAction==='restore';await saveAction(panel,b,async()=>{await call(tripId,'/'+m.id+(restore?'/restore':''),{revision:m.revision},restore?'POST':'DELETE');await open('memories');message(panel,restore?'Memory restored.':'Memory removed from this collection. A published story keeps its reviewed copy until you update or unpublish it.');});};
 }
 async function saveAction(panel,b,action){if(b)b.disabled=true;try{await action();}catch(e){message(panel,e.message);}finally{if(b)b.disabled=false;}}
 function renderStory(panel,data,tripId){const draft=data.publication?.draft,t=state.workspace.trip,eligible=state.workspace.content.filter(c=>c.publication_status==='published'&&['public','travelers'].includes(c.visibility)),memories=data.memories.filter(m=>!m.deleted_at);panel.innerHTML=`<h2>Past-trip story</h2><p>Choose the material to share publicly after the trip. Saving a preview does not publish it. Financial records, team contact details, and admin-only content are excluded.</p><p class="memory-status" role="status">${data.publication?.published_at?'A public version is live. Changes below stay private until you publish an update.':'No public story has been published.'}</p><form class="memory-story-form"><label>Destination<select name="destination_id" required><option value="">Choose a destination</option>${data.destinations.map(d=>`<option value="${esc(d.id)}" ${d.id===(draft?.destination.id||t.opportunity_id)?'selected':''}>${esc(d.title)}</option>`).join('')}</select></label>${field('title','Public story title',draft?.title||t.title,'text','required maxlength="180"')}${area('summary','Short summary',draft?.summary||t.public_summary||'',2000)}${area('story','Trip story',draft?.story||'',20000)}<fieldset><legend>Devotionals and trip resources</legend><p>Only published traveler/public content can be selected. Use the Content tab to prepare additional material.</p>${eligible.map(c=>`<label class="memory-check"><input type="checkbox" name="content_ids" value="${esc(c.id)}" ${draft?.content.some(x=>x.id===c.id)?'checked':''}>${esc([c.event_date,c.title].filter(Boolean).join(' · '))}</label>`).join('')||'<p>No eligible trip content yet.</p>'}</fieldset><fieldset><legend>Photos and trip notes</legend>${memories.map(m=>`<label class="memory-check"><input type="checkbox" name="memory_ids" value="${esc(m.id)}" ${draft?.memories.some(x=>x.id===m.id)?'checked':''}>${esc([m.event_date,m.kind==='photo'?'Photo':'Note',m.title].filter(Boolean).join(' · '))}</label>`).join('')||'<p>Add photos or notes in Photos &amp; memories.</p>'}</fieldset><div class="memory-actions">${button('Save and preview')}</div></form><div class="memory-actions">${data.publication?.published_at?`<a class="trip-button trip-button-outline" href="/past-trips/story/?trip=${encodeURIComponent(t.slug)}" target="_blank" rel="noopener">View public story</a>${button('Unpublish story','button','unpublish')}`:''}</div><p>Publishing is available after the end date when the trip is marked Completed. You can prepare and preview the story at any time.</p>`;
 panel.querySelector('form').onsubmit=async e=>{e.preventDefault();await saveAction(panel,e.submitter,async()=>{const f=e.target,body=values(f);body.content_ids=[...f.querySelectorAll('[name=content_ids]:checked')].map(i=>i.value);body.memory_ids=[...f.querySelectorAll('[name=memory_ids]:checked')].map(i=>i.value);body.revision=data.publication?.revision||0;const result=await call(tripId,'/publication/draft',body);data.publication={...data.publication,revision:result.revision,draft:result.snapshot};preview(result,tripId,t,panel);});};
 panel.querySelector('[data-memory-action=unpublish]')?.addEventListener('click',async e=>{if(!confirm('Remove this trip story from the public site? Your private trip memories and draft will remain.'))return;await saveAction(panel,e.target,async()=>{await call(tripId,'/publication/unpublish',{revision:data.publication.revision});await open('story');message(panel,'Public story removed.');});});
 }
 function preview(result,tripId,t,panel){const d=document.createElement('dialog');d.className='memory-preview';d.setAttribute('aria-label','Preview public trip story');d.innerHTML=`<header><h2>Public story preview</h2>${button('Close preview','button','close')}</header><p>This is the exact version that will be published. Later trip edits do not change it automatically.</p><div class="trip-story"></div><p role="status"></p><div class="memory-actions">${button('Publish this version','button','publish')}</div>`;document.body.append(d);window.HSTripMemoriesView.story(d.querySelector('.trip-story'),result.snapshot);d.querySelector('[data-memory-action=close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());const b=d.querySelector('[data-memory-action=publish]');b.disabled=readOnly()||t.status!=='completed'||!t.end_date||t.end_date>new Date().toISOString().slice(0,10);if(b.disabled)d.querySelector('[role=status]').textContent='Preview only: publish after the trip ends and its status is Completed.';b.onclick=async()=>{b.disabled=true;try{await call(tripId,'/publication/publish',{revision:result.revision});d.close();await open('story');message(panel,'Trip story published to the destination and Past trips.');}catch(e){d.querySelector('[role=status]').textContent=e.message;b.disabled=false;}};d.showModal();}
 window.HSMemories={open};
})();
