import {afterEach,expect,it} from 'vitest';
import {ministryFixture} from './ministry-fixture';
import {handleAdminRequest} from '../src/admin';
const fixtures:Awaited<ReturnType<typeof ministryFixture>>[]=[];
afterEach(()=>fixtures.splice(0).forEach(f=>f.sqlite.close()));
it('links both ways, reverses parent and child, preserves contacts and giving, and prevents duplicates',async()=>{
 const f=await ministryFixture();fixtures.push(f);
 const ids=[crypto.randomUUID(),crypto.randomUUID()];
 for(const [i,id] of ids.entries())f.sqlite.prepare("INSERT INTO people(id,first_name,last_name,first_name_normalized,last_name_normalized,email,email_normalized,created_at,updated_at) VALUES(?,?,'Example',?,'example','family@example.test','family@example.test','now','now')").run(id,'Person'+i,'person'+i);
 const path=(i:number)=>`/admin/people/${ids[i]}/relationships`;
 const call=(i:number,body?:unknown,method?:string)=>handleAdminRequest(f.request(path(i),body,method),f.env,path(i));
 expect((await call(0,{personId:ids[0],relationship:'spouse'}))?.status).toBe(422);
 expect((await call(0,{personId:ids[1],relationship:'parent'}))?.status).toBe(200);
 const view=await (await call(1))!.json() as any;expect(view.relationships[0]).toMatchObject({id:ids[0],relationship:'child'});
 expect((await call(1,{personId:ids[0],relationship:'spouse'}))?.status).toBe(200);
 expect(f.sqlite.prepare('SELECT COUNT(*) n FROM contact_relationships').get()?.n).toBe(1);
 expect((await (await call(0))!.json() as any).relationships[0].relationship).toBe('spouse');
 expect((await call(0,{emailShared:true},'PUT'))?.status).toBe(200);
 expect((await (await call(0))!.json() as any).emailShared).toBe(true);
 expect((await call(1,{personId:ids[0]},'DELETE'))?.status).toBe(200);
 expect((await (await call(0))!.json() as any).relationships).toEqual([]);
 expect(f.sqlite.prepare('SELECT COUNT(*) n FROM people').get()?.n).toBe(2);
 expect(f.sqlite.prepare('SELECT COUNT(*) n FROM ledger_entries').get()?.n).toBe(0);
 expect(f.sqlite.prepare('SELECT COUNT(*) n FROM contact_types').get()?.n).toBe(0);
 const noCsrf=f.request(path(0),{personId:ids[1],relationship:'sibling'});noCsrf.headers.delete('x-csrf-token');expect((await handleAdminRequest(noCsrf,f.env,path(0)))?.status).toBe(403);
 expect((await handleAdminRequest(new Request('http://localhost'+path(0)),f.env,path(0)))?.status).toBe(401);
 f.sqlite.exec(`INSERT INTO mmt_users(id,username,first_name,last_name,email,must_change_password,permissions_json,registered_at,updated_at) VALUES('reader','reader','Read','Only','read@example.test',0,'{"contacts":"read"}','now','now');UPDATE admin_sessions SET user_id='reader'`);
 expect((await call(0,{personId:ids[1],relationship:'sibling'}))?.status).toBe(403);
 expect((await (await call(0))!.json() as any).canEdit).toBe(false);
});
