import {afterEach,expect,it,vi} from 'vitest';
import {ministryFixture} from './ministry-fixture';
import {receiveInterest} from '../src/interest-review';
import {validateSubmissionPayload} from '../src/index';
import {handleInquiries} from '../src/inquiries';
import {handleAdminRequest} from '../src/admin';
import {handleMinistryAdminRequest} from '../src/ministry-admin';
import {handleTripAdminRequest} from '../src/trip-platform';
import {deliverInquiryEmail} from '../src/inquiry-email';
afterEach(()=>vi.unstubAllGlobals());
async function setup(){const f=await ministryFixture();f.env.ENVIRONMENT='test';const input=validateSubmissionPayload({firstName:'Test',lastName:'Inquiry',email:'inquiry@example.test',phone:'9725550123',contactPreference:'email',fieldOfStudy:'Service',preferredTiming:'Next year',message:'I would like to help',opportunities:['trip-athens'],consent:true,idempotencyKey:crypto.randomUUID()});const receipt=await receiveInterest(f.env,input,'new-'+crypto.randomUUID(),[{id:'trip-athens'}],null,null);const id=receipt.submissionId;const call=(body?:unknown)=>handleInquiries(f.request('/admin/inquiries/'+id,body),f.env,'/admin/inquiries/'+id);return {...f,id,call};}
const update=(revision=1)=>({path:'future',futureList:'Greece ministry',preferredTiming:'Next spring',stage:'exploring',ownerId:'primary',dueDate:'2027-01-05',nextAction:'Discuss timing',notes:'Likes teaching',closeReason:'',revision});
it('captures one acknowledgment and retains an open assigned inquiry without financial accounts',async()=>{const f=await setup();expect(f.sqlite.prepare('SELECT status FROM inquiry_emails').get()?.status).toBe('captured');expect(f.sqlite.prepare('SELECT owner_id,stage FROM inquiry_workflows').get()).toMatchObject({owner_id:'primary',stage:'new'});expect(f.sqlite.prepare('SELECT count(*) n FROM trip_accounts').get()?.n).toBe(0);expect((await f.call(update())).status).toBe(200);const path='/admin/ministry/inbox';const data=await(await handleMinistryAdminRequest(f.request(path),f.env,path)).json() as any;expect(data.items.find((i:any)=>i.id==='request:'+f.id).status).toBe('action');expect((await handleMinistryAdminRequest(f.request(path,{itemId:'request:'+f.id,action:'complete'}),f.env,path)).status).toBe(409);});
it('requires ownership, date and closure reason; detects stale updates; preserves future-list history when linked',async()=>{const f=await setup();expect((await f.call({...update(),ownerId:''})).status).toBe(422);expect((await f.call({...update(),dueDate:'2026-02-31'})).status).toBe(422);expect((await f.call({...update(),stage:'closed'})).status).toBe(422);expect((await f.call(update())).status).toBe(200);expect((await f.call(update())).status).toBe(409);const trip=crypto.randomUUID();f.sqlite.prepare("INSERT INTO trips(id,code,slug,title,location,created_at,updated_at) VALUES(?,? ,?,'Greece','Athens','2026','2026')").run(trip,trip,trip);expect((await f.call({...update(2),path:'journey',tripId:trip,stage:'invited'})).status).toBe(200);expect(f.sqlite.prepare('SELECT status FROM trip_members').get()?.status).toBe('invited');expect(f.sqlite.prepare('SELECT future_list FROM inquiry_workflows').get()?.future_list).toBe('Greece ministry');expect(f.sqlite.prepare('SELECT count(*) n FROM trip_accounts').get()?.n).toBe(0);});
it('creates charges only after confirmation; all inquiry and waitlist stages remain free of billing',async()=>{const f=await setup();const trip=crypto.randomUUID();f.sqlite.prepare("INSERT INTO trips(id,code,slug,title,location,created_at,updated_at) VALUES(?,? ,?,'Greece','Athens','2026','2026')").run(trip,trip,trip);const personId=f.sqlite.prepare('SELECT person_id FROM interest_submissions WHERE id=?').get(f.id)!.person_id;const path='/admin/trips/'+trip+'/members';for(const status of ['interested','invited','applied','approved','waitlisted']){expect((await handleTripAdminRequest(f.request(path,{personId,status}),f.env,path)).status).toBe(200);expect(f.sqlite.prepare('SELECT count(*) n FROM trip_accounts').get()?.n).toBe(0);}expect((await handleTripAdminRequest(f.request(path,{personId,status:'confirmed'}),f.env,path)).status).toBe(200);expect(f.sqlite.prepare('SELECT count(*) n FROM trip_accounts').get()?.n).toBe(1);});
it('sends from portal once, protects a reused send ID, and does not close the inquiry',async()=>{const f=await setup();Object.assign(f.env,{ENVIRONMENT:'production',MMT_EMAIL_PROVIDER:'resend',MMT_EMAIL_DELIVERY_MODE:'live',RESEND_API_KEY:'test-only'});const fetch=vi.fn(async(_url:unknown,_init?:RequestInit)=>Response.json({id:'provider-test'}));vi.stubGlobal('fetch',fetch);const path='/admin/submissions/'+f.id+'/replies',body={sendId:crypto.randomUUID(),subject:'Your inquiry',message:'Thank you!'};for(let i=0;i<2;i++)expect((await handleAdminRequest(f.request(path,body),f.env,path)).status).toBe(200);expect(fetch).toHaveBeenCalledTimes(1);expect(JSON.parse(fetch.mock.calls[0][1]!.body as string).from).toContain('admin@hopesojourns.com');expect(f.sqlite.prepare('SELECT stage FROM inquiry_workflows').get()?.stage).toBe('contacted');expect((await handleAdminRequest(f.request(path,{...body,message:'Changed'}),f.env,path)).status).toBe(409);});
it('uncertain delivery retries the frozen payload and key, and refuses a late unsafe retry',async()=>{const f=await setup();Object.assign(f.env,{ENVIRONMENT:'production',MMT_EMAIL_PROVIDER:'resend',MMT_EMAIL_DELIVERY_MODE:'live',RESEND_API_KEY:'test-only'});const fetch=vi.fn().mockRejectedValueOnce(new Error('timeout')).mockResolvedValueOnce(Response.json({id:'accepted'}));vi.stubGlobal('fetch',fetch);const path='/admin/submissions/'+f.id+'/replies',sendId=crypto.randomUUID();await handleAdminRequest(f.request(path,{sendId,subject:'Hello',message:'Please reply'}),f.env,path);expect(f.sqlite.prepare('SELECT status FROM inquiry_emails WHERE id=?').get(sendId)?.status).toBe('uncertain');expect((await deliverInquiryEmail(f.env,sendId)).status).toBe('sent');expect(fetch.mock.calls[0][1].headers['Idempotency-Key']).toBe(fetch.mock.calls[1][1].headers['Idempotency-Key']);expect(fetch.mock.calls[0][1].body).toBe(fetch.mock.calls[1][1].body);f.sqlite.prepare("UPDATE inquiry_emails SET status='uncertain',started_at='2020-01-01' WHERE id=?").run(sendId);await expect(deliverInquiryEmail(f.env,sendId)).rejects.toMatchObject({status:409});});
it('rejects inquiry edits by read-only users and requires CSRF',async()=>{const f=await setup();const path='/admin/inquiries/'+f.id;const req=new Request('http://localhost:4188/api/interest'+path,{method:'POST',headers:{cookie:'hs_admin_session='+f.token,'content-type':'application/json'},body:JSON.stringify(update())});expect((await handleInquiries(req,f.env,path)).status).toBe(403);f.sqlite.prepare("INSERT INTO mmt_users(id,username,first_name,last_name,email,password_hash,is_org_admin,registered_at,updated_at) VALUES('other-admin','other-admin','Other','Admin','admin@example.org','test',1,'2026','2026')").run();f.sqlite.prepare("UPDATE mmt_users SET is_admin=0,is_org_admin=0,permissions_json=? WHERE id='primary'").run('{"contacts":"read"}');expect((await f.call()).status).toBe(200);expect((await f.call(update())).status).toBe(403);});
