import {expect,it} from 'vitest';
import {ministryFixture} from './ministry-fixture';
import {findContactMatches,receiveInterest,handleInterestReview} from '../src/interest-review';
import {handleMinistryAdminRequest} from '../src/ministry-admin';
import {validateSubmissionPayload} from '../src/index';
import type {InterestSubmission} from '../src/index';
import {readFileSync} from 'node:fs';
const raw=(v:Record<string,unknown>={})=>({firstName:'New',lastName:'Traveler',email:'test@example.org',phone:'(972) 555-0100',contactPreference:'email',fieldOfStudy:'Service',preferredTiming:'Fall',message:'Interested',opportunities:['trip-athens'],consent:true,idempotencyKey:crypto.randomUUID(),...v});
function person(f:Awaited<ReturnType<typeof ministryFixture>>,email:string,phone:string,first='Existing',last='Contact'){const id=crypto.randomUUID();f.sqlite.prepare('INSERT INTO people(id,first_name,last_name,first_name_normalized,last_name_normalized,email,email_normalized,phone,phone_normalized,created_at,updated_at,notes,organization) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,first,last,first.toLowerCase(),last.toLowerCase(),email,email.trim().toLowerCase(),phone,phone,'2026-01-01','2026-01-01','Keep unrelated notes','Original ministry');return id;}
async function setup(){const f=await ministryFixture();const review=(id:string,body?:unknown)=>{const path='/admin/interest-reviews/'+id;return handleInterestReview(f.request(path,body),f.env,path);};const submit=async(input:InterestSubmission,fingerprint:string=crypto.randomUUID())=>receiveInterest(f.env,input,fingerprint,[{id:'trip-athens'}],null,'/interest/');return {...f,review,submit};}
it('matches email OR phone regardless of name; normalizes values and excludes empty matches',async()=>{const f=await setup();const a=person(f,'  TEST@Example.org  ','2145550199'),b=person(f,'different@example.org','+1 (972) 555-0100');const m=await findContactMatches(f.env,{email:'test@example.ORG ',phone:'972-555-0100'});expect(m.matches.map(c=>[c.id,c.matchBy])).toEqual(expect.arrayContaining([[a,'email'],[b,'phone']]));expect((await findContactMatches(f.env,{email:'',phone:''})).matches).toHaveLength(0);expect((await findContactMatches(f.env,{email:'different@example.org',phone:'1 972 555 0100'})).matches[0].matchBy).toBe('both');});
it('stages conflicting matches without touching contacts or relationships and creates one inbox item on retries',async()=>{const f=await setup();person(f,'test@example.org','2145550100');person(f,'other@example.org','9725550100');const input=validateSubmissionPayload(raw()),fingerprint='fingerprint-1';const before=f.sqlite.prepare('SELECT * FROM people ORDER BY id').all();const r=await f.submit(input,fingerprint);expect(await f.submit(input,fingerprint)).toEqual(r);expect(f.sqlite.prepare('SELECT * FROM people ORDER BY id').all()).toEqual(before);for(const t of ['interests','contact_types','trip_members','interest_submissions'])expect(f.sqlite.prepare(`SELECT COUNT(*) n FROM ${t}`).get()?.n).toBe(0);const path='/admin/ministry/inbox';const inbox=await (await handleMinistryAdminRequest(f.request(path),f.env,path)).json() as any;expect(inbox.items.filter((i:any)=>i.kind==='Contact match review')).toHaveLength(1);const d=await (await f.review(r.submissionId)).json() as any;expect(d.matches).toHaveLength(2);expect((await handleMinistryAdminRequest(f.request(path,{itemId:'duplicate:'+r.submissionId,action:'complete'}),f.env,path)).status).toBe(409);});
it('allows intentional separate contact with identical name and email; applies decision only once',async()=>{const f=await setup();person(f,'test@example.org','9725550100','New','Traveler');const r=await f.submit(validateSubmissionPayload(raw()));const d=await (await f.review(r.submissionId)).json() as any;const decision={action:'new',confirmSeparate:true,revision:d.revision};const result=await f.review(r.submissionId,decision);expect(result.status).toBe(200);expect((await f.review(r.submissionId,decision)).status).toBe(200);expect(f.sqlite.prepare('SELECT count(*) n FROM people').get()?.n).toBe(2);expect(f.sqlite.prepare('SELECT count(*) n FROM interests').get()?.n).toBe(1);expect(f.sqlite.prepare('SELECT count(*) n FROM interest_intake_decisions').get()?.n).toBe(1);const audit=f.sqlite.prepare("SELECT metadata_json FROM audit_events WHERE entity_type='interest_intake' AND event_type='review_decision'").get()!;expect(JSON.parse(String(audit.metadata_json))).toMatchObject({reviewerId:'primary',decision:'new'});expect((await f.review(r.submissionId,{action:'reject'})).status).toBe(409);});
it('updates only selected submitted fields and preserves unrelated history and existing interests',async()=>{const f=await setup();const id=person(f,'test@example.org','2145550100');f.sqlite.prepare("INSERT INTO contact_types VALUES(?,'donor','2026-01-01')").run(id);const r=await f.submit(validateSubmissionPayload(raw()));const d=await (await f.review(r.submissionId)).json() as any;expect((await f.review(r.submissionId,{action:'update',personId:id,fields:['phone','fieldOfStudy'],revision:d.revision})).status).toBe(200);expect(f.sqlite.prepare('SELECT * FROM people WHERE id=?').get(id)).toMatchObject({first_name:'Existing',email:'test@example.org',phone:'9725550100',notes:'Keep unrelated notes',organization:'Original ministry',field_of_study:'Service'});expect(f.sqlite.prepare('SELECT contact_type FROM contact_types WHERE person_id=?').all(id).map(t=>t.contact_type)).toEqual(expect.arrayContaining(['donor','prospective_traveler']));});
it('rejects without changing contacts; resolved item remains in inbox history',async()=>{const f=await setup();person(f,'test@example.org','9725550100');const before=f.sqlite.prepare('SELECT * FROM people').all();const r=await f.submit(validateSubmissionPayload(raw()));expect((await f.review(r.submissionId,{action:'reject'})).status).toBe(200);expect((await f.review(r.submissionId,{action:'reject'})).status).toBe(200);expect(f.sqlite.prepare('SELECT * FROM people').all()).toEqual(before);expect(f.sqlite.prepare('SELECT count(*) n FROM interests').get()?.n).toBe(0);const path='/admin/ministry/inbox',d=await (await handleMinistryAdminRequest(f.request(path),f.env,path)).json() as any;expect(d.items.find((i:any)=>i.id==='duplicate:'+r.submissionId).status).toBe('completed');});
it('keeps normal unmatched intake and public confirmation identical, rejects key reuse, and rechecks approval matches',async()=>{const f=await setup();const input=validateSubmissionPayload(raw()),r=await f.submit(input,'normal');expect(f.sqlite.prepare('SELECT count(*) n FROM people').get()?.n).toBe(1);const pending=await f.submit(validateSubmissionPayload(raw({firstName:'Other'})));expect(pending.message).toBe(r.message);const d=await (await f.review(pending.submissionId)).json() as any;person(f,'newmatch@example.org','9725550100');expect((await f.review(pending.submissionId,{action:'new',confirmSeparate:true,revision:d.revision})).status).toBe(409);await expect(f.submit(input,'changed-payload')).rejects.toMatchObject({status:409});});
it('preserves contacts, cascading children, notes and nullable links through the uniqueness migration',async()=>{const f=await ministryFixture('0035_ministry_planning.sql');const id=person(f,'preserve@example.org','9725550100');f.sqlite.prepare("INSERT INTO contact_types VALUES(?,'donor','2026')").run(id);f.sqlite.prepare("INSERT INTO contact_languages VALUES(?,'English','english','2026')").run(id);f.sqlite.prepare("INSERT INTO contact_areas VALUES(?,'mission','2026')").run(id);f.sqlite.prepare("INSERT INTO contact_trips VALUES(?,'trip-athens','2026')").run(id);f.sqlite.prepare("INSERT INTO ministry_tasks(id,title,person_id,created_at,updated_at) VALUES('t','Follow up',?,'2026','2026')").run(id);const before=f.sqlite.prepare('SELECT * FROM people').get();f.sqlite.exec('BEGIN;'+readFileSync(new URL('../migrations/0036_interest_duplicate_review.sql',import.meta.url),'utf8')+'COMMIT;');expect(f.sqlite.prepare('SELECT * FROM people').get()).toMatchObject(before!);for(const table of ['contact_types','contact_languages','contact_areas','contact_trips','ministry_tasks'])expect(f.sqlite.prepare(`SELECT count(*) n FROM ${table} WHERE person_id=?`).get(id)?.n).toBe(1);expect(f.sqlite.prepare('PRAGMA foreign_key_check').all()).toHaveLength(0);});
it('does not permit review without contact edit access and protects decisions with CSRF',async()=>{const f=await setup();person(f,'test@example.org','9725550100');const r=await f.submit(validateSubmissionPayload(raw()));const path='/admin/interest-reviews/'+r.submissionId;const noCsrf=new Request('http://localhost:4188/api/interest'+path,{method:'POST',headers:{cookie:'hs_admin_session='+f.token,'content-type':'application/json'},body:JSON.stringify({action:'reject'})});expect((await handleInterestReview(noCsrf,f.env,path)).status).toBe(403);f.sqlite.prepare("INSERT INTO mmt_users(id,username,first_name,last_name,email,password_hash,is_org_admin,registered_at,updated_at) VALUES('other-admin','other-admin','Other','Admin','admin@example.org','test',1,'2026','2026')").run();f.sqlite.prepare("UPDATE mmt_users SET is_admin=0,is_org_admin=0,permissions_json=? WHERE id='primary'").run('{"contacts":"read"}');expect((await f.review(r.submissionId)).status).toBe(200);expect((await f.review(r.submissionId,{action:'reject'})).status).toBe(403);});
it('catches a newly inserted match between lookup and the normal-contact insert',async()=>{const f=await setup(),batch=f.env.DB.batch.bind(f.env.DB);let raced=false;f.env.DB.batch=(async(statements:any[])=>{if(!raced){raced=true;person(f,'test@example.org','9725550100');}return batch(statements);}) as any;const r=await f.submit(validateSubmissionPayload(raw()));expect(f.sqlite.prepare('SELECT count(*) n FROM people').get()?.n).toBe(1);expect(f.sqlite.prepare('SELECT status FROM interest_intake WHERE id=?').get(r.submissionId)?.status).toBe('pending');});
it('retains accepted contact links across a matching approval even when an existing interest already exists',async()=>{const f=await setup();const input=validateSubmissionPayload(raw()),first=await f.submit(input);const personId=f.sqlite.prepare('SELECT person_id FROM interest_intake WHERE id=?').get(first.submissionId)?.person_id;f.sqlite.prepare("UPDATE interests SET status='exploring'").run();const r=await f.submit(validateSubmissionPayload(raw({message:'More information'})));const d=await (await f.review(r.submissionId)).json() as any;expect((await f.review(r.submissionId,{action:'update',personId,fields:[],revision:d.revision})).status).toBe(200);expect(f.sqlite.prepare('SELECT count(*) n FROM interests').get()?.n).toBe(1);expect(f.sqlite.prepare('SELECT status FROM interests').get()?.status).toBe('exploring');expect(f.sqlite.prepare('SELECT count(*) n FROM interest_submissions').get()?.n).toBe(2);});

it('preserves financial and restricted trip relationships during migration',async()=>{const f=await ministryFixture('0035_ministry_planning.sql');const id=person(f,'history@example.org','9725550100');
f.sqlite.prepare("INSERT INTO trips(id,code,slug,title,location,created_at,updated_at) VALUES('history-trip','HISTORY','history','History','Test','2026','2026')").run();
f.sqlite.prepare("INSERT INTO trip_members(trip_id,person_id,created_at,updated_at) VALUES('history-trip',?,'2026','2026')").run(id);
f.sqlite.prepare("INSERT INTO trip_accounts(id,trip_id,account_type,name,person_id,created_at,updated_at) VALUES('history-account','history-trip','individual','Original',?,'2026','2026')").run(id);
f.sqlite.prepare("INSERT INTO trip_funding_sources(id,name,name_normalized,person_id,created_at,updated_at) VALUES('history-source','Original','original',?,'2026','2026')").run(id);
f.sqlite.prepare("INSERT INTO ledger_entries(id,source_type,import_key,content_fingerprint,transaction_date,entry_type,payment_type,budget_category,amount,person_id,created_at,updated_at) VALUES('history-ledger','manual','history','history','2026-01-01','income','cash','general',10,?,'2026','2026')").run(id);
const tables=['people','trip_members','trip_accounts','trip_funding_sources','ledger_entries'];const before=tables.map(t=>f.sqlite.prepare('SELECT * FROM '+t+' ORDER BY rowid').all());
f.sqlite.exec('BEGIN;'+readFileSync(new URL('../migrations/0036_interest_duplicate_review.sql',import.meta.url),'utf8')+'COMMIT;');
for(let i=1;i<tables.length;i++)expect(f.sqlite.prepare('SELECT * FROM '+tables[i]+' ORDER BY rowid').all()).toEqual(before[i]);expect(f.sqlite.prepare('PRAGMA foreign_key_check').all()).toHaveLength(0);});
it('defers dated-trip relationships until approval and attaches them only once',async()=>{const f=await setup();const id=person(f,'test@example.org','9725550100');f.sqlite.prepare("INSERT INTO trips(id,code,slug,title,location,created_at,updated_at) VALUES('dated','DATED','dated','Dated','Test','2026','2026')").run();const input=validateSubmissionPayload(raw());const r=await receiveInterest(f.env,input,'dated-fingerprint',[{id:'trip-athens'}],{id:'dated',invite_id:null},'/interest/');expect(f.sqlite.prepare('SELECT count(*) n FROM trip_members').get()?.n).toBe(0);const d=await (await f.review(r.submissionId)).json() as any;const decision={action:'update',personId:id,fields:[],revision:d.revision};expect((await f.review(r.submissionId,decision)).status).toBe(200);expect((await f.review(r.submissionId,decision)).status).toBe(200);for(const t of ['trip_members','trip_interests'])expect(f.sqlite.prepare('SELECT count(*) n FROM '+t+' WHERE person_id=?').get(id)?.n).toBe(1);});
