import {describe,it,expect} from 'vitest';
import {ministryFixture} from './ministry-fixture';
import {handleTripAdminRequest,handleTripPublicRequest} from '../src/trip-platform';
import {handleMinistryAdminRequest,documentMedia} from '../src/ministry-admin';
import {allocatePayment} from '../src/ministry-budget';

async function setup(){const f=await ministryFixture();const call=async(path:string,body?:unknown,method?:string)=>{
 const r=await(path.startsWith('/admin/ministry')?handleMinistryAdminRequest:handleTripAdminRequest)(f.request(path,body,method),f.env,path);const data=await r.json() as Record<string,any>;return {status:r.status,data};};
 const created=await call('/admin/trips',{title:'Test trip',location:'Athens',startDate:'2027-01-10',endDate:'2027-01-12',publicEnabled:true,status:'recruiting'});
 expect(created.status,JSON.stringify(created.data)).toBe(201);return {...f,call,tripId:created.data.id};}
async function traveler(f:Awaited<ReturnType<typeof setup>>){const personId=crypto.randomUUID();f.sqlite.prepare(`INSERT INTO people(id,first_name,last_name,first_name_normalized,last_name_normalized,email,email_normalized,created_at,updated_at) VALUES(?,'Test','Traveler','test','traveler','test@example.com','test@example.com','2026-01-01','2026-01-01')`).run(personId);return personId;}
describe('Ministry Management integration',()=>{
 it('creates standard drafts atomically and keeps private content off public pages',async()=>{const f=await setup();expect(f.sqlite.prepare('SELECT COUNT(*) n FROM trip_cost_items').get()?.n).toBe(12);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM trip_content').get()?.n).toBe(8);const trip=f.sqlite.prepare('SELECT slug FROM trips').get();const response=await handleTripPublicRequest(f.request('/public/trips/'+trip?.slug),f.env,'/public/trips/'+trip?.slug);expect(await response.json()).toMatchObject({content:[],ministries:[]});});
 it('calculates eligible travel contributions, supports overrides, and does not compound fees',async()=>{const f=await setup();const cost=f.sqlite.prepare("SELECT id FROM trip_cost_items WHERE template_key='airfare'").get();const updated=await f.call('/admin/trips/'+f.tripId+'/cost-items',{id:cost?.id,categoryId:'category-airfare',description:'Airfare',calculationMethod:'per_traveler',quantity:1,estimatedUnitCost:1000,budgetGroup:'traveler',travelEligible:true});expect(updated.status).toBe(200);expect(f.sqlite.prepare("SELECT estimated_total FROM trip_cost_items WHERE template_key='hs-leadership'").get()?.estimated_total).toBe(100);
 const fee=f.sqlite.prepare("SELECT id FROM trip_cost_items WHERE template_key='hs-leadership'").get();expect((await f.call('/admin/trips/'+f.tripId+'/cost-items',{id:fee?.id,categoryId:'category-hs-leadership',description:'HS Travel',calculationMethod:'percentage_of_individual',percentageRate:12,budgetGroup:'hs'})).status).toBe(200);expect(f.sqlite.prepare("SELECT estimated_total FROM trip_cost_items WHERE template_key='hs-leadership'").get()?.estimated_total).toBe(120);});
 it('assigns budget once, splits installments over items, rejects overpayment and retries safely',async()=>{const f=await setup();f.sqlite.exec("UPDATE trip_cost_items SET needs_estimate=0,estimated_unit_cost=100,estimated_total=100 WHERE template_key IN ('airfare','lodging')");const personId=await traveler(f);const assignment={personId,role:'traveler',status:'confirmed'};expect((await f.call('/admin/trips/'+f.tripId+'/members',assignment)).status).toBe(200);await f.call('/admin/trips/'+f.tripId+'/members',assignment);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM trip_accounts').get()?.n).toBe(1);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM trip_charges').get()?.n).toBe(2);const accountId=f.sqlite.prepare('SELECT id FROM trip_accounts').get()?.id;
 await f.call('/admin/ministry/accounts/'+accountId+'/plan',{plan:'self_funded'});const operationId=crypto.randomUUID();const payment={accountId,operationId,amount:150,paymentMethod:'Check',transactionDate:'2026-09-17',autoApply:true,installment:true};expect((await f.call('/admin/trips/'+f.tripId+'/payments',payment)).status).toBe(201);expect((await f.call('/admin/trips/'+f.tripId+'/payments',payment)).data.alreadyRecorded).toBe(true);expect(f.sqlite.prepare('SELECT SUM(amount) n FROM trip_payment_applications').get()?.n).toBe(150);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM ledger_entries').get()?.n).toBe(1);expect((await f.call('/admin/trips/'+f.tripId+'/payments',{...payment,operationId:crypto.randomUUID(),amount:60})).status).toBe(409);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM trip_payments').get()?.n).toBe(1);
 const source=f.sqlite.prepare('SELECT id FROM trip_funding_sources LIMIT 1').get()?.id;expect((await f.call('/admin/ministry/accounts/'+accountId+'/support',{operationId:crypto.randomUUID(),amount:50,fundingSourceId:source,reason:'HS scholarship'})).status).toBe(200);const data=await f.call('/admin/ministry/accounts/'+accountId);expect(data.data.charges.reduce((sum:number,c:any)=>sum+c.amount-c.applied,0)).toBe(0);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM ledger_entries').get()?.n).toBe(1);});
 it('previews revised budgets and blocks lowering already paid items',async()=>{const f=await setup();f.sqlite.exec("UPDATE trip_cost_items SET needs_estimate=0,estimated_unit_cost=100,estimated_total=100 WHERE template_key='airfare'");const personId=await traveler(f);await f.call('/admin/trips/'+f.tripId+'/members',{personId,role:'traveler'});const accountId=f.sqlite.prepare('SELECT id FROM trip_accounts').get()?.id;await f.call('/admin/trips/'+f.tripId+'/payments',{accountId,amount:100,paymentMethod:'Check',transactionDate:'2026-09-17',autoApply:true});f.sqlite.exec("UPDATE trip_cost_items SET estimated_total=50 WHERE template_key='airfare'");const path='/admin/ministry/trips/'+f.tripId+'/budget-review';const preview=await f.call(path);expect((await f.call(path,{revision:preview.data.revision})).status).toBe(409);expect((await f.call(path,{revision:'stale'})).status).toBe(409);});
 it('stores private document versions, supports trash and restore, and requires auth',async()=>{const f=await setup();const upload=()=>{const form=new FormData();form.set('title','Board minutes');form.set('category','Board Minutes');form.set('file',new File(['%PDF-1.4\nboard minutes'],'minutes.pdf',{type:'application/pdf'}));return form;};const first=await f.call('/admin/ministry/documents',upload());expect(first.status,JSON.stringify(first.data)).toBe(201);const path='/admin/ministry/documents/'+first.data.id;expect((await f.call(path,upload())).status).toBe(201);expect(f.files.size).toBe(2);expect((await f.call(path,{},'DELETE')).status).toBe(200);const download=path+'/versions/'+first.data.versionId;expect((await f.call(download)).status).toBe(404);expect((await f.call(path,{},'PATCH')).status).toBe(200);const response=await handleMinistryAdminRequest(f.request(download),f.env,download);expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toContain('no-store');const denied=await handleMinistryAdminRequest(new Request('https://example.test/api/interest/admin/ministry/documents'),f.env,'/admin/ministry/documents');expect(denied.status).toBe(401);});
 it('returns one central queue and distinguishes approvals from completed payments',async()=>{const f=await setup();const result=await f.call('/admin/ministry/inbox');expect(result.status,JSON.stringify(result.data)).toBe(200);expect(result.data.items[0].kind).toBe('Trip preparation');});
 it('allocates cents exactly and rejects active HTML uploads',()=>{expect(allocatePayment(.3,[{id:'a',amount:.1,applied:0},{id:'b',amount:.2,applied:0}])).toEqual([{chargeId:'a',amount:.1},{chargeId:'b',amount:.2}]);expect(()=>documentMedia('x.pdf',new TextEncoder().encode('<script>alert(1)</script>'))).toThrow();});
 it('applies previously recorded funding without duplicating cash income',async()=>{const f=await setup();f.sqlite.exec("UPDATE trip_cost_items SET needs_estimate=0,estimated_total=100 WHERE template_key='airfare'");const personId=await traveler(f);await f.call('/admin/trips/'+f.tripId+'/members',{personId});const accountId=f.sqlite.prepare('SELECT id FROM trip_accounts').get()?.id;const payment=await f.call('/admin/trips/'+f.tripId+'/payments',{accountId,amount:100,paymentMethod:'Check',transactionDate:'2026-09-17'});const path='/admin/ministry/accounts/'+accountId+'/apply-existing';const payload={operationId:crypto.randomUUID(),sourceId:payment.data.id,amount:100};expect((await f.call(path,payload)).status).toBe(200);expect((await f.call(path,payload)).data.alreadyRecorded).toBe(true);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM ledger_entries').get()?.n).toBe(1);expect(f.sqlite.prepare('SELECT status FROM trip_charges').get()?.status).toBe('paid');});
 it('cancels and restores unpaid budget charges without duplicates',async()=>{const f=await setup();f.sqlite.exec("UPDATE trip_cost_items SET needs_estimate=0,estimated_total=100 WHERE template_key='airfare'");const personId=await traveler(f);await f.call('/admin/trips/'+f.tripId+'/members',{personId});const path='/admin/ministry/trips/'+f.tripId+'/budget-review';f.sqlite.exec("UPDATE trip_cost_items SET payment_status='canceled' WHERE template_key='airfare'");let preview=await f.call(path);expect((await f.call(path,{revision:preview.data.revision})).status).toBe(200);expect(f.sqlite.prepare('SELECT status FROM trip_charges').get()?.status).toBe('canceled');f.sqlite.exec("UPDATE trip_cost_items SET payment_status='planned' WHERE template_key='airfare'");preview=await f.call(path);expect((await f.call(path,{revision:preview.data.revision})).status).toBe(200);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM trip_charges').get()?.n).toBe(1);expect(f.sqlite.prepare('SELECT status FROM trip_charges').get()?.status).toBe('open');});
 it('rejects overpayments without creating records and enforces CSRF on file changes',async()=>{const f=await setup();const denied=await handleMinistryAdminRequest(new Request('http://localhost/api/interest/admin/ministry/documents',{method:'POST',headers:{cookie:'hs_admin_session='+f.token}}),f.env,'/admin/ministry/documents');expect(denied.status).toBe(403);f.sqlite.exec("UPDATE trip_cost_items SET needs_estimate=0,estimated_total=100 WHERE template_key='airfare'");const personId=await traveler(f);await f.call('/admin/trips/'+f.tripId+'/members',{personId});const accountId=f.sqlite.prepare('SELECT id FROM trip_accounts').get()?.id;const chargeId=f.sqlite.prepare('SELECT id FROM trip_charges').get()?.id;expect((await f.call('/admin/trips/'+f.tripId+'/payments',{accountId,chargeId,amount:200,appliedAmount:200,paymentMethod:'Check',transactionDate:'2026-09-17'})).status).toBe(409);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM ledger_entries').get()?.n).toBe(0);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM trip_payments').get()?.n).toBe(0);});
});
