import {it,expect} from 'vitest';
import {ministryFixture} from './ministry-fixture';
import {handleMinistryAdminRequest} from '../src/ministry-admin';
import {handleTripAdminRequest} from '../src/trip-platform';
async function setup(){const f=await ministryFixture(),path='/admin/ministry/inbox';const r=await handleTripAdminRequest(f.request('/admin/trips',{title:'Inbox test',location:'Athens',status:'draft'}),f.env,'/admin/trips');const trip=await r.json() as {id:string};expect(r.status).toBe(201);const call=async(body?:unknown)=>{const r=await handleMinistryAdminRequest(f.request(path,body),f.env,path);return {status:r.status,data:await r.json() as any}};return {...f,path,call,itemId:'budget:'+trip.id,tripId:trip.id};}
it('completes, reopens, trashes and restores notices without changing trip or financial records',async()=>{const f=await setup();expect((await f.call()).data.items.find((i:any)=>i.id===f.itemId).status).toBe('action');expect((await f.call({itemId:f.itemId,action:'complete'})).status).toBe(200);expect((await f.call()).data.items.find((i:any)=>i.id===f.itemId).status).toBe('completed');expect(f.sqlite.prepare('SELECT budget_completed_at FROM trips WHERE id=?').get(f.tripId)?.budget_completed_at).toBeNull();await f.call({itemId:f.itemId,action:'delete'});await f.call({itemId:f.itemId,action:'delete'});expect((await f.call()).data.items.find((i:any)=>i.id===f.itemId).status).toBe('deleted');await f.call({itemId:f.itemId,action:'restore'});expect((await f.call()).data.items.find((i:any)=>i.id===f.itemId).status).toBe('completed');await f.call({itemId:f.itemId,action:'reopen'});expect((await f.call()).data.items.find((i:any)=>i.id===f.itemId).status).toBe('action');expect(f.sqlite.prepare('SELECT COUNT(*) n FROM ledger_entries').get()?.n).toBe(0);});
it('retains completed trip notices after the source budget is finished',async()=>{const f=await setup();await f.call({itemId:f.itemId,action:'complete'});f.sqlite.prepare('UPDATE trips SET budget_completed_at=? WHERE id=?').run('2026-09-18',f.tripId);expect((await f.call()).data.items.find((i:any)=>i.id===f.itemId).status).toBe('completed');await f.call({itemId:f.itemId,action:'reopen'});expect((await f.call()).data.items.find((i:any)=>i.id===f.itemId).status).toBe('completed');});
it('rejects unknown IDs, invalid actions and missing CSRF',async()=>{const f=await setup();expect((await f.call({itemId:'budget:missing',action:'delete'})).status).toBe(404);expect((await f.call({itemId:f.itemId,action:'approve'})).status).toBe(422);const r=f.request(f.path,{itemId:f.itemId,action:'delete'});r.headers.delete('x-csrf-token');expect((await handleMinistryAdminRequest(r,f.env,f.path)).status).toBe(403);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM ministry_inbox_states').get()?.n).toBe(0);});
it('enforces inbox edit permission and original section visibility',async()=>{const f=await setup();f.sqlite.exec("INSERT INTO mmt_users(id,username,first_name,last_name,email,phone,country,is_admin,permissions_json,status,must_change_password,registered_at,updated_at) VALUES('limited','limited','Limited','User','limited@example.test','','US',0,'{\"inbox\":\"read\",\"trips\":\"read\"}','active',0,'2026','2026'); UPDATE admin_sessions SET user_id='limited'");expect((await f.call()).data.canManage).toBe(false);expect((await f.call({itemId:f.itemId,action:'complete'})).status).toBe(403);f.sqlite.prepare('UPDATE mmt_users SET permissions_json=? WHERE id=?').run(JSON.stringify({inbox:'edit'}),'limited');expect((await f.call()).data.items.some((i:any)=>i.id===f.itemId)).toBe(false);expect((await f.call({itemId:f.itemId,action:'delete'})).status).toBe(404);});
