import {expect,it} from 'vitest';
import {ministryFixture} from './ministry-fixture';
import {handleCsmDelivery,handleCsmAdminRequest} from '../src/csm-distribution';
import {parseDistributionMessage} from '../src/csm-distribution-contract';
import {csmAuthority} from '../src/shared-signin';
async function setup(){const f=await ministryFixture();const donor=crypto.randomUUID(),holder=crypto.randomUUID();for(const [id,first] of [[donor,'Original'],[holder,'Holder']])f.sqlite.prepare('INSERT INTO people(id,first_name,last_name,first_name_normalized,last_name_normalized,email,email_normalized,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,first,'Person',first.toLowerCase(),'person',first+'@example.test',first.toLowerCase()+'@example.test','2026','2026');Object.assign(f.env,{CSM_DISTRIBUTION_SECRET:'test-secret',ENVIRONMENT:'test'});return{...f,donor,holder};}
function message(id:string){const key=crypto.randomUUID();return {schemaVersion:1,messageId:key,idempotencyKey:'HopeSojourns:personal:'+key,sourceRevision:1,sentAt:'2026-09-23',destination:'HopeSojourns',product:'HopeSojourns',displayName:'Original Person',masterDonorId:'hs-contact:'+id,party:{role:'donor',displayName:'Original Person',email:'original@example.test',phone:null,address:null},transaction:{sourceRecordId:'personal:'+key,paypalTransactionId:key,eventCode:'PERSONAL_GIFT',eventDate:'2026-09-23T12:00:00.000Z',status:'Completed',direction:'received',currency:'USD',gross:250,fee:-5,net:245,itemName:'CSM — Hope Sojourns'},personalGift:{contactId:id,receivedBy:'Brent Kern',method:'Personal Zelle',reference:'zelle-1',designation:'Hope Sojourns',movements:[{id:crypto.randomUUID(),kind:'fee',date:'2026-09-23',amountCents:500,reference:'fee-1',description:'Payment fee',clearedDate:null},{id:crypto.randomUUID(),kind:'expense',date:'2026-09-23',amountCents:2000,reference:'receipt-1',description:'Ministry supplies',clearedDate:null},{id:crypto.randomUUID(),kind:'transfer',date:'2026-09-23',amountCents:22500,reference:'bank-1',description:'CSM bank',clearedDate:'2026-09-24'}]}};}
const delivery=(b:unknown)=>new Request('https://internal/internal/csm-distribution',{method:'POST',headers:{'Content-Type':'application/json','X-CSM-Distribution-Secret':'test-secret'},body:JSON.stringify(b)});
it('receives once, preserves selected donor and actual method, and records linked expenses once',async()=>{const f=await setup(),m=message(f.donor);const received=await (await handleCsmDelivery(delivery(m),f.env)).json() as any;expect(received.status).toBe('pending');expect((await (await handleCsmDelivery(delivery(m),f.env)).json() as any).duplicate).toBe(true);const path='/admin/csm-inbox/'+received.inboxId+'/approve';expect((await handleCsmAdminRequest(f.request(path,{personId:f.holder}),f.env,path)).status).toBe(409);expect((await handleCsmAdminRequest(f.request(path,{personId:f.donor}),f.env,path)).status).toBe(200);await handleCsmAdminRequest(f.request(path,{personId:f.donor}),f.env,path);expect(f.sqlite.prepare("SELECT person_id,payment_type,amount,charitable_amount FROM ledger_entries WHERE entry_type='income'").get()).toEqual({person_id:f.donor,payment_type:'Personal Zelle',amount:245,charitable_amount:250});expect(f.sqlite.prepare("SELECT count(*) n,SUM(amount) total FROM ledger_entries WHERE entry_type='expense'").get()).toEqual({n:1,total:20});expect(f.sqlite.prepare('SELECT count(*) n FROM financial_transactions').get()?.n).toBe(1);});
it('rejects JBB routing, unreconciled totals, malformed metadata, and missing authorization',async()=>{const f=await setup(),m=message(f.donor);expect(()=>parseDistributionMessage({...m,product:'JoshBeyondBorders',destination:'JoshBeyondBorders'})).toThrow();expect(()=>parseDistributionMessage({...m,transaction:{...m.transaction,net:250}})).toThrow();expect(()=>parseDistributionMessage({...m,personalGift:undefined})).toThrow();const r=new Request('https://internal/internal/csm-distribution',{method:'POST',body:JSON.stringify(m)});expect((await handleCsmDelivery(r,f.env)).status).toBe(401);});
it('allows HS contacts only through an authenticated CSM session with both portal permissions',async()=>{const f=await setup();Object.assign(f.env,{SHARED_SIGNIN:'enabled'});f.sqlite.exec("INSERT INTO mmt_users(id,username,first_name,last_name,email,is_org_admin,is_admin,password_hash,registered_at,updated_at) VALUES('other-admin','other-admin','Other','Admin','admin@example.test',1,1,'configured','2026','2026'); UPDATE admin_sessions SET portal='csm'; UPDATE mmt_users SET csm_access=1,csm_is_admin=0,is_org_admin=0,is_admin=0,permissions_json='{\"contacts\":\"read\"}',csm_permissions_json='{\"giving\":\"read\"}' WHERE id='primary'");const req=new Request('https://identity.internal/personal-gift-contacts?q=Original',{headers:{cookie:'hs_admin_session='+f.token}});const r=await csmAuthority(req,f.env);expect(r.status).toBe(200);expect((await r.json() as any).contacts[0].id).toBe(f.donor);f.sqlite.exec("UPDATE mmt_users SET permissions_json='{}'");expect((await csmAuthority(req,f.env)).status).toBe(403);expect((await csmAuthority(new Request('https://identity.internal/personal-gift-contacts?q=Original'),f.env)).status).toBe(401);});
