import {afterEach,expect,it} from 'vitest';
import {ministryFixture} from './ministry-fixture';
import {handleAdminRequest,hashText} from '../src/admin';
import {handleAccountPublic} from '../src/mmt-users';
import {csmAuthority,sharedSwitch} from '../src/shared-signin';
// Exercise the authority protocol directly. CSM tests cover its HTTP adapter;
// this suite remains runnable from an independent HS checkout.
async function sharedRoutes(r:Request,env:any,path:string){
 if(r.method!=='GET'&&r.headers.get('origin')!=='http://localhost:4189')throw Object.assign(new Error('Origin rejected'),{status:403});
 const headers=new Headers(r.headers);headers.set('cookie',(headers.get('cookie')||'').replace('cs_admin_session=','hs_admin_session='));
 let body=r.method==='GET'?undefined:await r.text();if(path==='/login'){const b=JSON.parse(body!);body=JSON.stringify({...b,username:b.userId});}
 const response=await env.IDENTITY.fetch(new Request('http://identity.internal'+(path.startsWith('/public/')?path:'/admin'+path),{method:r.method,headers,body}));
 const outputHeaders=new Headers(response.headers);if(outputHeaders.has('set-cookie'))outputHeaders.set('set-cookie',outputHeaders.get('set-cookie')!.replace('hs_admin_session=','cs_admin_session='));
 return new Response(response.body,{status:response.status,headers:outputHeaders});
}
async function sharedAuthorize(r:Request,env:any){const headers=new Headers(r.headers);headers.set('cookie',(headers.get('cookie')||'').replace('cs_admin_session=','hs_admin_session='));headers.set('content-type','application/json');const response=await env.IDENTITY.fetch(new Request('http://identity.internal/authorize',{method:'POST',headers,body:JSON.stringify({path:new URL(r.url).pathname.replace('/api/admin',''),method:r.method})}));const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error),{status:response.status});return data;}

const fixtures:Awaited<ReturnType<typeof ministryFixture>>[]=[];
afterEach(()=>fixtures.splice(0).forEach(f=>f.sqlite.close()));
const password='Original!Password123';
const profile={username:'member',first_name:'Test',last_name:'Person',email:'member@example.test',phone:'9725550123',country:'US'};
const membership=(permissions:Record<string,string>={},is_admin=false,enabled=true)=>({permissions,is_admin,enabled});
async function setup(){const f=await ministryFixture();fixtures.push(f);Object.assign(f.env,{ADMIN_PASSWORD:password,ADMIN_SESSION_SECRET:'test-shared-secret',SHARED_SIGNIN:'enabled',HS_PORTAL_ORIGIN:'http://localhost:4188',CSM_PORTAL_ORIGIN:'http://localhost:4189'});const csEnv={SHARED_SIGNIN:'enabled',ALLOWED_ORIGINS:'http://localhost:4189',IDENTITY:{fetch:(r:Request)=>csmAuthority(r,f.env)}} as any;
 const request=(path:string,b?:unknown,method?:string,cookie='hs_admin_session='+f.token,csrf=f.csrf)=>new Request('http://localhost:4188/api/interest'+path,{method:method||(b?'POST':'GET'),headers:{cookie,'x-csrf-token':csrf,'content-type':'application/json',origin:'http://localhost:4188'},body:b?JSON.stringify(b):undefined});
 const call=(p:string,b?:unknown,m?:string,c?:string,t?:string)=>handleAdminRequest(request(p,b,m,c,t),f.env,p);
 const cs=(path:string,b?:unknown,method?:string,cookie='',csrf='')=>sharedRoutes(new Request('http://localhost:4189/api/admin'+path,{method:method||(b?'POST':'GET'),headers:{cookie,'x-csrf-token':csrf,'content-type':'application/json',origin:'http://localhost:4189'},body:b?JSON.stringify(b):undefined}),csEnv,path) as Promise<Response>;
 async function create(extra:unknown={}){const r=await call('/admin/account/users',{...profile,memberships:{hs:membership({contacts:'read'}),csm:membership({finances:'read'})},...extra as any});expect(r.status).toBe(201);const data=await r.json() as any;const token=data.setupLink.split('#token=')[1];expect((await handleAccountPublic(request('/public/account/reset',{token,password,confirmPassword:password}),f.env,'/public/account/reset')).status).toBe(200);return data.user;}
 return {...f,csEnv,request,call,cs,create};
}
async function credentials(response:Response){expect(response.status).toBe(200);return {cookie:response.headers.get('set-cookie')!.split(';')[0],...await response.json() as any};}
it('keeps existing HS identity IDs and grants only Brent initial CSM access',async()=>{const f=await setup();expect(f.sqlite.prepare("SELECT id,username,is_org_admin,hs_access,csm_access FROM mmt_users WHERE id='primary'").get()).toEqual({id:'primary',username:'admin',is_org_admin:1,hs_access:1,csm_access:1});const u=await f.create({memberships:{hs:membership({contacts:'read'})}});expect(u.memberships.csm.enabled).toBe(false);expect((await f.cs('/login',{userId:'member',password})).status).toBe(401);});
it('signs into either portal with one password and isolates session audiences',async()=>{const f=await setup();await f.create();const hs=await credentials(await f.call('/admin/login',{username:'member',password})),cs=await credentials(await f.cs('/login',{userId:'member',password}));expect(cs.user.id).toBe(hs.user.id);expect(cs.user.portal).toBe('csm');expect((await f.call('/admin/session',undefined,'GET',cs.cookie.replace('cs_admin_session','hs_admin_session'))).status).toBe(401);});
it('enforces CSM blocked/read/edit access on the server',async()=>{const f=await setup();await f.create();const cs=await credentials(await f.cs('/login',{userId:'member',password}));const req=(path:string,method='GET')=>new Request('http://localhost:4189/api/admin'+path,{method,headers:{cookie:cs.cookie,origin:'http://localhost:4189','x-csrf-token':cs.csrfToken}});expect((await sharedAuthorize(req('/data'),f.csEnv)).user_id).toBe(cs.user.id);await expect(sharedAuthorize(req('/records/expenses','POST'),f.csEnv)).rejects.toMatchObject({status:403});await expect(sharedAuthorize(req('/donors'),f.csEnv)).rejects.toMatchObject({status:403});});
it('limits a Portal Administrator to their portal and forbids shared identity or password takeover',async()=>{const f=await setup();const admin=await f.create({username:'localadmin',email:'local@example.test',memberships:{hs:membership({},true),csm:membership({},false,false)}});const target=await f.create();const a=await credentials(await f.call('/admin/login',{username:'localadmin',password}));const path='/admin/account/users/'+target.id;const call=(b:any,m='PUT',suffix='')=>f.call(path+suffix,b,m,a.cookie,a.csrfToken);for(const body of [{is_org_admin:true},{memberships:{csm:membership({},true)}},{email:'attacker@example.test'},{status:'disabled'}])expect((await call({...body,revision:2})).status).toBe(403);expect((await call({},'POST','/temporary-password')).status).toBe(403);expect((await call({confirmUsername:'member',revision:2},'DELETE')).status).toBe(403);expect((await f.call('/admin/account/users/primary',{memberships:{hs:membership({},false,false)},revision:1},'PUT',a.cookie,a.csrfToken)).status).toBe(403);expect((await call({memberships:{hs:membership({},false,false)},revision:2})).status).toBe(200);expect(f.sqlite.prepare('SELECT csm_access FROM mmt_users WHERE id=?').get(target.id)?.csm_access).toBe(1);expect(admin.is_org_admin).toBe(false);});
it('protects the last Organization Administrator from demotion, suspension, and loss of both memberships',async()=>{const f=await setup();for(const b of [{is_org_admin:false},{status:'disabled'},{memberships:{hs:membership({},false,false),csm:membership({},false,false)}}])expect((await f.call('/admin/account/users/primary',{...b,revision:1},'PUT')).status).toBe(409);});
it('revokes both portals on shared suspension while preserving historical identity',async()=>{const f=await setup(),u=await f.create(),hs=await credentials(await f.call('/admin/login',{username:'member',password})),cs=await credentials(await f.cs('/login',{userId:'member',password}));expect((await f.call('/admin/account/users/'+u.id,{status:'disabled',revision:2},'PUT')).status).toBe(200);expect((await f.call('/admin/session',undefined,'GET',hs.cookie)).status).toBe(401);expect((await f.cs('/session',undefined,'GET',cs.cookie)).status).toBe(401);expect(f.sqlite.prepare('SELECT id FROM mmt_users WHERE id=?').get(u.id)).toBeTruthy();});
it('switches through a target-browser challenge exactly once without another password',async()=>{const f=await setup();await f.create();const hs=await credentials(await f.call('/admin/login',{username:'member',password}));const start=await f.cs('/switch/start',{}),verifierCookie=start.headers.get('set-cookie')!.split(';')[0],startBody=await start.json() as any,challenge=new URL(startBody.url).hash.split('=')[1];const issue=await sharedSwitch(f.request('/admin/switch/issue',{challenge},'POST',hs.cookie,hs.csrfToken),f.env,'/admin/switch/issue');expect(issue.status).toBe(200);const code=new URL((await issue.json() as any).url).hash.split('=')[1];expect((await f.cs('/switch/finish',{code},'POST','mmt_switch='+'x'.repeat(43))).status).toBe(403);const finish=await f.cs('/switch/finish',{code},'POST',verifierCookie);const cs=await credentials(finish);expect(cs.user.id).toBe(hs.user.id);expect((await f.cs('/switch/finish',{code},'POST',verifierCookie)).status).toBe(403);expect((await f.cs('/session',undefined,'GET',cs.cookie)).status).toBe(200);});
it('refuses switching after source logout, disabled target, or temporary password',async()=>{const f=await setup();await f.create();const hs=await credentials(await f.call('/admin/login',{username:'member',password}));const challenge=await hashText('x'.repeat(43)),issue=await sharedSwitch(f.request('/admin/switch/issue',{challenge},'POST',hs.cookie,hs.csrfToken),f.env,'/admin/switch/issue'),code=new URL((await issue.json() as any).url).hash.split('=')[1];await f.call('/admin/logout',{},'POST',hs.cookie,hs.csrfToken);expect((await f.cs('/switch/finish',{code},'POST','mmt_switch='+'x'.repeat(43))).status).toBe(403);});
it('stores CSM requests in the shared inbox without granting immediate access',async()=>{const f=await setup();const r=await f.cs('/public/account/request',profile);expect(r.status).toBe(202);expect(f.sqlite.prepare('SELECT portal,status FROM mmt_access_requests').get()).toEqual({portal:'csm',status:'pending'});expect(f.sqlite.prepare("SELECT id FROM mmt_users WHERE username='member'").get()).toBeUndefined();});
it('grants an existing account the other portal without replacing its password',async()=>{const f=await setup(),u=await f.create({memberships:{hs:membership({contacts:'read'})}});const before=f.sqlite.prepare('SELECT password_hash FROM mmt_users WHERE id=?').get(u.id)?.password_hash;expect((await f.call('/admin/account/users/'+u.id,{revision:2,memberships:{csm:membership({finances:'edit'})}},'PUT')).status).toBe(200);expect(f.sqlite.prepare('SELECT password_hash FROM mmt_users WHERE id=?').get(u.id)?.password_hash).toBe(before);expect((await f.cs('/login',{userId:'member',password})).status).toBe(200);});
it('changes a password from CSM and invalidates the HS session',async()=>{const f=await setup();await f.create();const hs=await credentials(await f.call('/admin/login',{username:'member',password})),cs=await credentials(await f.cs('/login',{userId:'member',password}));const next='Replacement!Password456';expect((await f.cs('/password',{currentPassword:password,newPassword:next,confirmPassword:next},'POST',cs.cookie,cs.csrfToken)).status).toBe(200);expect((await f.call('/admin/session',undefined,'GET',hs.cookie)).status).toBe(401);expect((await f.call('/admin/login',{username:'member',password:next})).status).toBe(200);});
it('creates CSM-only users from CSM without granting HS access',async()=>{const f=await setup(),admin=await credentials(await f.cs('/login',{userId:'admin',password}));const r=await f.cs('/account/users',{...profile,memberships:{csm:membership({finances:'read'})}},'POST',admin.cookie,admin.csrfToken);expect(r.status).toBe(201);const data=await r.json() as any;expect(data.user.memberships.hs.enabled).toBe(false);expect(data.setupLink).toMatch(/^http:\/\/localhost:4189\/admin\/access/);});
it('approves a CSM request from HS and preserves existing identity when linking',async()=>{const f=await setup(),u=await f.create({memberships:{hs:membership({contacts:'read'})}});await f.cs('/public/account/request',profile);const request=f.sqlite.prepare('SELECT id FROM mmt_access_requests').get()!;const b={action:'approve',user_id:u.id,identityVerified:true,memberships:{csm:membership({finances:'read'})}};expect((await f.call('/admin/account/requests/'+request.id,{...b,identityVerified:false},'PUT')).status).toBe(422);const r=await f.call('/admin/account/requests/'+request.id,b,'PUT');expect(r.status).toBe(200);expect(await r.json()).not.toHaveProperty('setupLink');expect(f.sqlite.prepare('SELECT hs_access,csm_access,permissions_json FROM mmt_users WHERE id=?').get(u.id)).toMatchObject({hs_access:1,csm_access:1});expect((await f.cs('/login',{userId:'member',password})).status).toBe(200);});
it('approves a new CSM request without granting HS access',async()=>{const f=await setup();await f.cs('/public/account/request',profile);const request=f.sqlite.prepare('SELECT id FROM mmt_access_requests').get()!;expect((await f.call('/admin/account/requests/'+request.id,{action:'approve',memberships:{csm:membership({giving:'read'})}},'PUT')).status).toBe(200);expect(f.sqlite.prepare("SELECT hs_access,csm_access FROM mmt_users WHERE username='member'").get()).toEqual({hs_access:0,csm_access:1});});
it('does not return setup tokens to Portal Administrators resetting an existing user',async()=>{const f=await setup();await f.create({username:'localadmin',email:'local@example.test',memberships:{hs:membership({},true)}});const target=await f.create(),a=await credentials(await f.call('/admin/login',{username:'localadmin',password}));const r=await f.call('/admin/account/users/'+target.id+'/invite',{},'POST',a.cookie,a.csrfToken);expect(r.status).toBe(200);expect(await r.json()).not.toHaveProperty('setupLink');});
it('checks CSRF and origin before processing CSM user changes',async()=>{const f=await setup(),a=await credentials(await f.cs('/login',{userId:'admin',password}));expect((await f.cs('/account/users',profile,'POST',a.cookie,'wrong')).status).toBe(403);await expect(sharedRoutes(new Request('http://localhost:4189/api/admin/account/users',{method:'POST',headers:{origin:'https://untrusted.example','content-type':'application/json',cookie:a.cookie},body:JSON.stringify(profile)}),f.csEnv,'/account/users')).rejects.toMatchObject({status:403});});
it('rejects expired tickets and tickets after target access is removed',async()=>{const f=await setup();const u=await f.create(),a=await credentials(await f.call('/admin/login',{username:'member',password})),challenge=await hashText('x'.repeat(43));const issue=()=>sharedSwitch(f.request('/admin/switch/issue',{challenge},'POST',a.cookie,a.csrfToken),f.env,'/admin/switch/issue');let code=new URL((await (await issue()).json() as any).url).hash.split('=')[1];f.sqlite.exec("UPDATE mmt_switch_codes SET expires_at='2000-01-01'");expect((await f.cs('/switch/finish',{code},'POST','mmt_switch='+'x'.repeat(43))).status).toBe(403);code=new URL((await (await issue()).json() as any).url).hash.split('=')[1];await f.call('/admin/account/users/'+u.id,{revision:2,memberships:{csm:membership({},false,false)}},'PUT');expect((await f.cs('/switch/finish',{code},'POST','mmt_switch='+'x'.repeat(43))).status).toBe(403);});

it('restricts donor search to the selected field and preserves direct donor lookup',async()=>{
 const f=await setup();await f.create({memberships:{hs:membership({contacts:'read'}),csm:membership({giving:'read'})}});
 const session=await credentials(await f.cs('/login',{userId:'member',password}));
 const headers={cookie:session.cookie.replace('cs_admin_session=','hs_admin_session=')};
 for(const [id,first,last,email,phone] of [['joy','Joy','Kern','joykern47@example.test','972-555-0100'],['ed','Ed','Lorenz','ed@example.test','(214) 555-4747']])f.sqlite.prepare('INSERT INTO people(id,first_name,last_name,first_name_normalized,last_name_normalized,email,email_normalized,phone,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,first,last,first.toLowerCase(),last.toLowerCase(),email,email,phone,'2026','2026');
 const search=async(q:string,field?:string)=>csmAuthority(new Request('https://identity.internal/personal-gift-contacts?'+new URLSearchParams({q,...field?{field}:{}}),{headers}),f.env);
 const ids=async(r:Response)=>{expect(r.status).toBe(200);return ((await r.json()) as any).contacts.map((c:any)=>c.id);};
 expect(await ids(await search(' JOYKERN47@example.test ','email'))).toEqual(['joy']);
 expect(await ids(await search('joykern47@example.test'))).toEqual(['joy']);
 expect(await ids(await search('47','email'))).toEqual(['joy']);
 expect(await ids(await search('47','phone'))).toEqual(['ed']);
 expect(await ids(await search('214-555','phone'))).toEqual(['ed']);
 expect(await ids(await search('Joy Kern','name'))).toEqual(['joy']);
 expect(await ids(await search('ed@example.test','name'))).toEqual([]);
 expect((await search('joykern47@example.test','phone')).status).toBe(422);
 expect((await search('anything','unknown')).status).toBe(422);
 expect(await ids(await search('','phone'))).toEqual([]);
 expect(await ids(await csmAuthority(new Request('https://identity.internal/personal-gift-contacts?id=ed',{headers}),f.env))).toEqual(['ed']);
});
