"""Build preview pathway pages with shared navigation; illustrative catalog stays separate from MMT."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def build_paths(out):
 nav='''<header class="path-header"><a href="/in-motion/" aria-label="Hope Sojourns home"><img src="/assets/hope-sojourns-logo.png" alt="Hope Sojourns"></a><nav aria-label="Main navigation"><a href="/mission-journeys/">Mission journeys</a><a href="/internships/">Internships</a><a href="/corporate/">Corporate journeys</a><a href="/in-motion/#encounters">Our stories</a></nav></header>'''
 footer='''<footer class="path-footer"><a href="/in-motion/">Hope Sojourns · Go with Hope. Serve with Faith.</a><a href="https://hopesojourns.com/schedule/">Talk with Brent ↗</a></footer>'''
 pages={
 'internships':('Find your place to serve', '''<section class="path-hero intern-hero"><img src="/assets/kenya.jpg" alt="A community gathering in Kenya"><div><p class="overline">Internships · Stay & grow</p><h1>A place for your skills.<br><em>A purpose for your season.</em></h1><p>Start with the people you hope to serve. Find a ministry by where it works, what it does, and how you could contribute.</p><a class="path-button" href="#explore">Find a ministry ↓</a></div></section>
<aside class="sample-notice"><strong>Explore a sample experience.</strong> Ministry names, roles, and durations below are fictional examples—not confirmed partners or available placements. Photos illustrate destinations, not these sample ministries.</aside>
<section class="explorer" id="explore" aria-labelledby="explorer-title"><div class="explorer-heading"><div><p class="overline">Follow a place. Follow a purpose.</p><h2 id="explorer-title">Who would you like<br>to serve alongside?</h2></div><p>Combine a destination with an area of work, or leave either open. Save examples that interest you as you explore.</p></div>
<div class="explorer-layout"><aside class="explorer-filters"><label for="ministry-search">Search ministries or skills</label><input id="ministry-search" type="search" placeholder="Try teaching, outreach, or languages"><label for="destination-filter">Destination</label><select id="destination-filter"><option value="">All destinations</option></select><fieldset><legend>Area of service</legend><div id="area-filters"></div></fieldset><button class="reset-filters" type="button">Clear filters</button></aside><div><div class="results-bar"><p id="results-status" role="status">Loading sample ministries…</p><button type="button" id="shortlist-filter" aria-pressed="false">My shortlist (0)</button></div><div class="ministry-grid" id="ministry-results"></div><noscript><p>Enable JavaScript to filter sample ministries, or <a href="https://hopesojourns.com/schedule/">talk with Brent about internships</a>.</p></noscript></div></div></section>
<section class="path-next"><p class="overline">A conversation before a commitment</p><h2>Your interests are the starting point.</h2><p>We can talk about your skills, timing, and the kind of work that matters to you. A real placement would depend on the ministry’s needs and a conversation about fit.</p><a class="path-button" href="https://hopesojourns.com/schedule/">Talk about an internship ↗</a></section>
<dialog id="ministry-dialog" aria-labelledby="ministry-dialog-title"><button class="dialog-close" type="button" aria-label="Close ministry details">Close ×</button><div id="ministry-dialog-content"></div></dialog>''','internships.js'),
 'corporate':('A shared purpose for your team','''<section class="path-hero corporate-hero"><img src="/assets/ministry-gathering-athens-with-brent.png" alt="Illustrative group portrait"><div><p class="overline">Corporate humanitarian journeys · Bring your team</p><h1>Build connection.<br><em>Contribute together.</em></h1><p>Bring your team’s skills and willingness to learn. Explore a service journey shaped with local partners around work that matters to their community.</p><a class="path-button" href="#team-planner">Imagine your journey ↓</a></div></section>
<section class="corporate-intro"><p class="overline">Purpose beyond the office</p><h2>Start with the community.<br>Make room for your people.</h2><div class="principle-grid"><article><span>01</span><h3>Listen first</h3><p>Begin with local priorities and a conversation about what your team can usefully contribute.</p></article><article><span>02</span><h3>Bring your strengths</h3><p>Explore practical service, skills sharing, or support for a community program.</p></article><article><span>03</span><h3>Grow together</h3><p>Make room for shared reflection, relationship, and learning beyond the day’s activities.</p></article></div><p>Hope Sojourns is rooted in Christian faith. We’ll discuss your team’s expectations and the host ministry’s context as we explore the right fit.</p></section>
<section class="team-planner" id="team-planner"><div><p class="overline">Build a conversation starter</p><h2>What could your<br><em>team bring?</em></h2><p>This is an exploratory planner, not a booking or confirmed itinerary. Your choices stay on this page until you choose to copy or share them.</p><label for="team-size">Team size</label><select id="team-size"><option>5–10 people</option><option>11–20 people</option><option>21+ people</option><option>Still exploring</option></select><label for="team-focus">What interests your team?</label><select id="team-focus"><option>Practical community service</option><option>Skills sharing and mentoring</option><option>Supporting a local outreach program</option></select><label for="team-place">Where would you like to explore?</label><select id="team-place"><option>Open to a recommendation</option><option>Mexico City</option><option>England</option><option>Athens</option><option>Another destination</option></select></div><div class="team-brief"><p class="overline">Your starting point</p><h3>A journey to discuss</h3><p id="brief-intro" aria-live="polite"></p><p>Next, we would explore local partner needs, suitable roles, timing, accessibility, and costs together.</p><textarea id="team-brief-text" aria-label="Your editable conversation notes" rows="7"></textarea><button class="path-button" id="copy-brief" type="button">Copy my conversation notes</button><p id="copy-status" role="status"></p><a href="https://hopesojourns.com/schedule/">Book a conversation with Brent ↗</a><small>No trip availability or partner commitment is implied by these choices.</small></div></section>''','corporate.js'),
 'mission-journeys':('Go with hope. Serve with faith.','''<section class="path-hero mission-hero"><img src="/assets/athens-team-2026.jpg" alt="Travelers together in Athens"><div><p class="overline">Mission journeys · Go & serve</p><h1>A journey of faith.<br><em>A meeting of lives.</em></h1><p>Serve alongside local ministries. Listen to people’s stories. Discover how faith and relationship can shape the way you travel.</p><a class="path-button" href="#trips">Explore the destinations ↓</a></div></section><section class="mission-destinations" id="trips"><p class="overline">Current public opportunities</p><h2>Where could you go?</h2><p>Explore current destination descriptions and planning dates managed by Hope Sojourns.</p><div class="destination-links featured-destinations"><a href="https://hopesojourns.com/#trips">View current mission journeys ↗</a></div><h2 class="more-heading">More places to serve.</h2><div class="destination-links other-destinations"></div></section><section class="path-next"><h2>Begin by listening.</h2><p>A red juice box. A conversation on a park bench. Two encounters that shaped the heart of Hope Sojourns.</p><a class="path-button" href="/in-motion/#encounters">Walk through the stories →</a></section>''','destinations.js')}
 routes=[]
 for slug,(title,body,script) in pages.items():
  page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{title} · Hope Sojourns</title><link rel="icon" href="/assets/hope-sojourns-icon.png"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/pathways.css"><script src="/{script}" defer></script></head><body class="path-page"><a class="path-skip" href="#main">Skip to content</a>{nav}<main id="main">{body}</main>{footer}</body></html>'''
  directory=out/slug;directory.mkdir(exist_ok=True);(directory/'index.html').write_text(page,encoding='utf-8');routes.append(f'{slug}/index.html')
 return routes
