"""Generate five independently reviewable public design directions."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'preview'

options = [
    ('open-door', 'The open door', 'A warm, spacious welcome', 'The clearest starting point: an inviting photograph, a plain explanation, and room to explore.', 'Come with us.<br><em>See what unfolds.</em>', 'athens.jpg'),
    ('field-journal', 'The field journal', 'A journey you can leaf through', 'An editorial approach with photographs, handwritten-feeling notes, and stories woven into the page.', 'A little farther<br>from the familiar.', 'ministry-gathering-athens-with-brent.png'),
    ('people-first', 'People first', 'Begin with a personal welcome', 'Meet Brent and the people behind the invitation before exploring places or reading a story.', 'There’s room<br>for you here.', 'athens-team-2026.jpg'),
    ('wide-horizon', 'The wide horizon', 'A sense of place and possibility', 'An expansive photographic opening, followed by a clear introduction and a gentle path into the encounters.', 'Go with Hope.<br><em>Serve with Faith.</em>', 'athens.jpg'),
    ('your-next-step', 'Your next step', 'A welcome that listens', 'A simple choice helps visitors find the information they want, with both stories always available.', 'Where would you<br>like to begin?', 'ministry-gathering-athens-with-brent.png'),
]

def head(title, css='/directions.css', script=True):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="Hope Sojourns invites you on Christian mission journeys alongside trusted local ministries."><title>{title} · Hope Sojourns preview</title><link rel="icon" href="/assets/hope-sojourns-icon.png"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="{css}">{'<script src="/directions.js" defer></script>' if script else ''}</head>'''

def header(n, name):
    return f'''<div class="review-bar"><a href="/">← Compare all five</a><span>Direction {n:02} · {name}</span><a href="/{options[n%5][0]}/">Next direction →</a></div><a class="skip-link" href="#main">Skip to content</a><header class="direction-header"><a href="#" aria-label="Hope Sojourns home"><img src="/assets/hope-sojourns-logo.png" alt="Hope Sojourns" width="170" height="95"></a><nav aria-label="Main navigation"><a href="#approach">Who we are</a><a href="#journeys">The journeys</a><a href="#stories">The stories</a><a class="nav-contact" href="https://hopesojourns.com/schedule/">Let’s talk ↗</a></nav></header>'''

intro='Hope Sojourns invites you on Christian mission journeys alongside trusted local ministries. Come ready to serve, build relationships, and discover what God is doing in the lives around you.'
actions='<div class="actions"><a class="primary" href="#journeys">Explore the journeys <span aria-hidden="true">↗</span></a><a class="quiet" href="#approach">Get to know Hope Sojourns →</a></div>'

red='''<p>The evening settled slowly over Athens. Heat still rose from the pavement. Between two apartment buildings, the Acropolis appeared again, then slipped behind the city.</p><p>There were twelve of us walking that night. I shifted a canvas bag from one hand to the other. Inside were sandwiches, snacks, and juice boxes. Every few blocks, someone stopped to talk. Relationships set the rhythm.</p><h4>A moment on the street</h4><p>When I looked up, a woman was standing directly in front of me. She was already speaking, her hands moving as much as her voice. We didn’t understand each other.</p><p>I handed her a sandwich, a snack, and a juice box. She accepted the food. Then she shook her head and pushed the drink back. She pointed inside the bag.</p><p>Artur came back, listened, and said quietly, “She wants a red juice box.”</p><p>I looked again. Blue, blue, nothing else.</p><p>Finally, she took only the sandwich and walked away. I stood there with the drink in my hand. Honestly, I didn’t know what else I could have done. A quiet old thought slipped in.</p><blockquote>Sometimes you just get what you get…</blockquote><p>We kept walking. The streets kept introducing us to people. By the time we headed back to the apartment, that encounter had slipped into the background.</p><h4>Back at the apartment</h4><p>Stories started to move around the room. Who did you meet? What was it like?</p><p>“You all are not gonna believe what happened to me tonight,” I said. I told them about the woman and the drink I couldn’t give her. I thought I was about to tell the strangest story in the room.</p><p>Amanda had been listening.</p><blockquote>“Brent… she wanted a red juice box.”</blockquote><p>I gave a little laugh. Of course I knew that. Amanda didn’t move on. Same gentle voice, same steady eyes. She said my name and stopped.</p><p>In that pause, something began to happen inside me. I had always thought compassion was mainly about doing, serving, helping, fixing. Suddenly I saw that before any of that, there’s just noticing. Actually seeing a person.</p><p>I hadn’t done that. I had turned a person into a need to meet, and missed her own preferences. Amanda’s voice brought me back.</p><blockquote>“She just wanted a red juice box.”</blockquote>'''
john='''<p>We followed Artur into the park as the evening light began to thin. At one bench, he introduced me to John, a man from England who had lived in Greece for about thirty years.</p><p>Artur offered to finish the walk with the team and return in twenty minutes. Would I like to sit with John?</p><p>“That would be perfect. I’d love that.”</p><h4>A little time together</h4><p>We talked about ordinary things. A little about himself, a little about England. There was no great unfolding of his life that evening. It was simply the sort of conversation two people have when they have just been introduced and find that they enjoy talking.</p><p>I enjoyed talking with John.</p><p>The next night wasn’t my turn to go on the walk. I asked to go anyway. With Artur’s agreement, I went ahead to the park.</p><p>John was there. He was surprised that I had come back. Pleased, too.</p><blockquote>I sat down again.</blockquote><h4>The bench he called his office</h4><p>We had about an hour this time, though I wasn’t keeping track of it that way. The bench was his office. That was what he called it. He usually had a novel to read.</p><p>Little by little, he told me more. Leaving England. Building a life in Greece. Marriage and divorce. The routines and arrangements that helped him get through each day.</p><p>Then he told me about his daughter and granddaughter. His daughter wanted nothing to do with him, and he wasn’t part of their lives. That hurt him.</p><p>I couldn’t fill in everything that had happened. I was hearing John’s part of it, sitting beside him while he told me what it was like to be outside those relationships. I stayed and listened.</p><h4>When it was time to go</h4><p>The team returned. I reached out and shook his hand. I told him I would try to visit again, though I couldn’t promise when.</p><p>Until I saw him again, I said, take care of yourself.</p><p>He looked at me.</p><blockquote>“Brent, the problem isn’t taking care of myself.”</blockquote><blockquote>“The problem is loneliness.”</blockquote>'''

def stories():
    return f'''<section class="stories preview-section" id="stories"><div class="story-heading"><p class="eyebrow">The heart behind the journeys</p><h2>Some encounters<br><em>stay with you.</em></h2><p>Two personal stories from Brent’s time in Athens. Each began with an ordinary evening walk. Take a moment to step inside.</p></div><div class="story-list"><details class="encounter" id="red-story"><summary><span class="story-number">01</span><span><span class="eyebrow">Athens · From Brent’s book</span><strong>The red juice box</strong><span class="story-tease">An encounter I thought I understood.</span></span><span class="open-label">Read the story <b aria-hidden="true">+</b></span></summary><div class="reading"><p class="reading-credit">An abridged account from Chapter 1 · Brent Kern</p>{red}<div class="pause"><p class="eyebrow">A question to carry with you</p><p>When have you discovered there was more to someone’s story than you first understood?</p></div><a class="quiet next-story" href="#john-story">Spend an evening with John →</a><button class="close-story" type="button">Close this story ↑</button></div></details><details class="encounter" id="john-story"><summary><span class="story-number">02</span><span><span class="eyebrow">Athens · From Brent’s book</span><strong>An evening with John</strong><span class="story-tease">A park bench. A conversation. A reason to return.</span></span><span class="open-label">Read the story <b aria-hidden="true">+</b></span></summary><div class="reading"><p class="reading-credit">An abridged account from Chapter 2 · Brent Kern</p>{john}<div class="pause"><p class="eyebrow">Stay with the moment</p><p>Perhaps there is someone whose story you have only begun to hear.</p></div><a class="quiet" href="https://hopesojourns.com/schedule/">Talk with Brent about a journey ↗</a><button class="close-story" type="button">Close this story ↑</button></div></details></div></section>'''

def lower():
    return '''<section class="approach preview-section" id="approach"><div><p class="eyebrow">Who we are</p><h2>We begin<br><em>with relationship.</em></h2></div><div class="approach-copy"><p>Hope Sojourns is a Christian mission travel ministry working in partnership with Christian Steps Ministries. We bring willing people alongside local ministries that know and serve their own communities.</p><p>You arrive ready to listen, learn, and contribute. The work takes its shape from the people and partners already there.</p><a class="quiet" href="https://hopesojourns.com/about/">More about the ministry ↗</a></div><ol class="principles"><li><span>01</span><h3>Listen first.</h3><p>Learn from the people who call this place home.</p></li><li><span>02</span><h3>Serve alongside.</h3><p>Join practical work shaped by local ministry partners.</p></li><li><span>03</span><h3>Carry it home.</h3><p>Let what you learn change how you notice people every day.</p></li></ol></section>'''

def journeys():
    return '''<section class="journeys preview-section" id="journeys"><div class="section-top"><div><p class="eyebrow">Places to begin</p><h2>Where might hope<br><em>take you?</em></h2></div><p>Explore the ministry and possibilities in each place.<br>Current plans and trip details are on our main website.</p></div><div class="journey-list"><a href="https://hopesojourns.com/trips/athens/"><img src="/assets/athens.jpg" alt="A view across Athens" loading="lazy"><span>Greece</span><h3>Athens <b>↗</b></h3><p>Walk alongside ministries serving people experiencing homelessness and displacement.</p></a><a href="https://hopesojourns.com/trips/kenya/"><img src="/assets/kenya.jpg" alt="Students gathered outdoors in Kenya" loading="lazy"><span>East Africa</span><h3>Kenya <b>↗</b></h3><p>Explore relationships with local ministries supporting girls and their futures.</p></a><a href="https://hopesojourns.com/trips/mexico-city/"><img src="/assets/mexico-city.jpg" alt="Architecture in Mexico City" loading="lazy"><span>Mexico</span><h3>Mexico City <b>↗</b></h3><p>Learn about serving with ministry partners responding to homelessness.</p></a></div><div class="journey-more"><a class="quiet" href="https://hopesojourns.com/#trips">See all journey possibilities ↗</a><a class="quiet" href="https://hopesojourns.com/internships/">Explore student internships ↗</a></div></section>'''

def footer():
    return '''<section class="closing"><p class="eyebrow">Your invitation</p><h2>Let’s begin<br><em>with a conversation.</em></h2><p>You can bring your questions. We can explore what a journey might look like for you, your church, or your group.</p><a class="primary" href="https://hopesojourns.com/schedule/">Talk with Brent ↗</a></section></main><footer class="direction-footer"><span>Hope Sojourns · Go with Hope. Serve with Faith.</span><a href="/">Compare the five directions</a><a href="https://hopesojourns.com/">Main website ↗</a></footer>'''

for n, (slug, name, subtitle, description, title, photo) in enumerate(options,1):
    hero=f'''<section class="welcome"><div class="welcome-copy"><p class="eyebrow">Christian mission journeys · You are invited</p><h1>{title}</h1><p class="welcome-intro">{intro}</p>{actions}<a class="story-invitation" href="#red-story">An encounter in Athens changed how I understood serving. <span>Read the story →</span></a></div><figure class="welcome-photo"><img src="/assets/{photo}" alt="{'Hope Sojourns team members gathered in Athens' if n in (2,3,5) else 'A view across Athens'}"><figcaption>Athens, Greece · One place a journey can begin</figcaption></figure></section>'''
    if n==2:
        hero=f'''<section class="journal-welcome"><div class="journal-title"><p class="eyebrow">Hope Sojourns · Christian mission journeys</p><h1>{title}</h1><p class="journal-note">Faith. People. Places that stay with you.</p></div><div class="journal-grid"><figure><img src="/assets/{photo}" alt="Ministry companions gathered in Athens"><figcaption>From the journey / Athens, Greece</figcaption></figure><div><p class="welcome-intro">{intro}</p>{actions}<div class="journal-excerpt"><span>From Brent’s notebook</span><p>“Relationships set the rhythm, not an itinerary.”</p><a class="quiet" href="#red-story">Step into an evening in Athens →</a></div></div></div></section>'''
    if n==3:
        hero=f'''<section class="people-welcome"><div class="people-copy"><p class="eyebrow">Christian mission journeys · Hope Sojourns</p><h1>{title}</h1><p class="welcome-intro">{intro}</p>{actions}</div><div class="people-images"><img class="team" src="/assets/athens-team-2026.jpg" alt="Hope Sojourns team together in Athens"><img class="founder-portrait" src="/assets/brent-kern-headshot-casual-color.png" alt="Brent Kern, founder of Hope Sojourns"><span class="portrait-label">Brent Kern<br><small>Founder, Hope Sojourns</small></span></div></section><section class="personal-note preview-section"><p class="eyebrow">A personal invitation</p><p>“You don’t need all the answers before you begin. You just need enough courage to say yes to the first small invitation.”</p><span>— From the prologue of Brent’s book</span><a class="quiet" href="#stories">Meet the encounters behind the invitation →</a></section>'''
    if n==4:
        hero=f'''<section class="horizon-welcome"><img src="/assets/athens.jpg" alt="A wide view over Athens"><div><p class="eyebrow">Hope Sojourns · Christian mission journeys</p><h1>{title}</h1><p>{intro}</p><div class="actions"><a class="primary" href="#journeys">Find your next journey ↗</a><a class="quiet" href="#approach">Meet the ministry ↓</a></div></div><span class="horizon-caption">Athens, Greece</span></section><section class="horizon-bridge preview-section"><span>Before a journey is a destination,<br>it’s an invitation.</span><p>To listen. To contribute. To meet someone whose story you haven’t heard.<br><a class="quiet" href="#stories">Two encounters from Athens →</a></p></section>'''
    if n==5:
        hero=f'''<section class="path-welcome"><p class="eyebrow">Hope Sojourns · Christian mission journeys</p><h1>{title}</h1><p class="welcome-intro">{intro}</p><div class="path-choices" aria-label="Find a starting point"><button type="button" data-path="travel" aria-pressed="true">I’m curious about going <span>↗</span></button><button type="button" data-path="people" aria-pressed="false">I’d like to know you first <span>↗</span></button><button type="button" data-path="story" aria-pressed="false">I want to hear a story <span>↗</span></button></div><section class="path-answer" aria-live="polite" aria-atomic="true"><div><p class="eyebrow">Start with a possibility</p><h2>There’s a place<br>to bring your questions.</h2><p>Explore the journeys, then talk with us about your interests and the opportunities taking shape.</p><a class="primary" href="#journeys">Explore the journeys →</a></div><img src="/assets/ministry-gathering-athens-with-brent.png" alt="People gathering together in Athens"></section><noscript><p>Choose a starting point below: <a href="#journeys">Journeys</a> · <a href="#approach">Who we are</a> · <a href="#stories">Stories</a></p></noscript></section>'''
    page=head(name)+f'<body class="direction {slug}">'+header(n,name)+'<main id="main">'+hero
    page += lower()+ (stories()+journeys() if n in (2,3) else journeys()+stories()) + footer()+'</body></html>'
    folder=DEST/slug;folder.mkdir(exist_ok=True);(folder/'index.html').write_text(page,encoding='utf-8')

cards=''.join(f'''<a class="compare-option sample-{n}" href="/{slug}/"><div class="sample"><img src="/assets/{photo}" alt=""><span>{title}</span></div><div class="compare-copy"><span class="eyebrow">Direction {n:02}{' · Suggested starting point' if n==1 else ''}</span><h2>{name}</h2><h3>{subtitle}</h3><p>{description}</p><span class="compare-open">Explore this direction <b>↗</b></span></div></a>''' for n,(slug,name,subtitle,description,title,photo) in enumerate(options,1))
(DEST/'index.html').write_text(head('Five ways to begin',script=False)+f'''<body class="comparison"><header class="compare-header"><img src="/assets/hope-sojourns-logo.png" alt="Hope Sojourns"><span>Design exploration · Round two</span><a href="https://hopesojourns.com/">Main website ↗</a></header><main id="main"><section class="compare-intro"><p class="eyebrow">A fresh look at the invitation</p><h1>Five ways<br><em>to begin.</em></h1><p>A clearer welcome. More room to breathe.<br>Two stories with space to unfold.</p><div class="compare-guidance">Start with <a href="/open-door/">The open door</a>, then explore whichever direction draws you in. Each is a working page, with both Athens stories and links to the existing journeys.</div></section><section class="compare-grid" aria-label="Five design directions">{cards}</section><section class="compare-bottom"><h2>What feels most like Hope Sojourns?</h2><p>Consider the welcome, the sense of place, and how naturally you find your way into a story. We can combine the strongest parts.</p><a href="/first-draft.html">Revisit the first draft →</a></section></main><footer class="direction-footer"><span>Hope Sojourns · Preview only</span><span>The main website and MMT portal are unchanged.</span></footer></body></html>''',encoding='utf-8')
print('Generated comparison and five complete directions.')
